### ISSUE TITLE
Epic: Subnavigation component enhancements

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/bedrock#10036]
## Description

**What is the overall outcome we aim to achieve?** 
Add new features to the subnav component for better user experience and page linking.  

_Note that these features are all not final. This issue can serve as a discussion for the refinements._ 

---

**Features include:** 
- #10037: Tertiary navigation (including collapsed on mobile) 
- #10038: Styling applied to active page element
- ~Add _n_ link items on Left sidebar~
- Breadcrumb-style behavoior (Display parent/child/sibling page relationships)

## Screenshots

Mobile:
![image](https://user-images.githubusercontent.com/2692333/112200242-09993180-8bdd-11eb-8e22-95db114d65c6.png)

Desktop: 
![image](https://user-images.githubusercontent.com/2692333/112200245-0aca5e80-8bdd-11eb-85e8-135bddc783df.png)

**Comment by maxxcrawford** [comment]
cc/ @rraue @craigcook

**Comment by maxxcrawford** [comment]
Curious if having a breadcrumb component would be an alternate to altering the subnav component?

**Comment by craigcook** [comment]
We have a design for breadcrumbs in the footer, but we ended up punting on it because generating those links automatically on every page is A Whole Thing. Since we weren't going to roll it out yet I never even built the component to house it. But we could do so now and treat it like we do the subnav as hand-made, sometimes-present element. And if we want top-of-page breadcrumbs (where humans will see it) we'll want to rethink the design.

Design here: https://github.com/mozilla/bedrock/issues/9286#issuecomment-698557086

![image](https://user-images.githubusercontent.com/205591/112342676-a9a79700-8c7f-11eb-9f73-339efe41153a.png)

**Comment by rraue** [comment]
> Curious if having a breadcrumb component would be an alternate to altering the subnav component?

It would be if it would be just about crawling. But I think a breadcrumb serves different needs than a subnav. The breadcumb should be all logical about parent - child connections. In the subnav while doing the same if not otherwise set, we should be able to do connections for a given page to pages somewhere completely else on our site or even external.

A good example would be linking in the subnav to the sumo page for users searching for help/how to.

**Comment by alexgibson** [comment]
I'm not sure if we have an immediate need for a tertiary level of navitation, at least for the VPN pages. We can revisit this in the future if a need arises.
