### ISSUE TITLE
Pass attribution from /whatsnew pages to the VPN landing page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10053]
## Description

Right now if we build a /whatsnew page that links people to /products/vpn/, we can use GA to tell how many people click through to the landing page, and how many of those people go on to register a goal on the landing page. However once someone clicks a subscription button and goes onto purchase, well lose that they originally came from the /whatsnew page. All we'll know is they came from the landing page.

To remedy this (at least in the short term) we should add some functionality to the landing page that checks for a query parameter (e.g. `?campaign=whatsnew-88`), or alternatively a cookie, and then passes that info along to the subscription buttons (e.g. populating `utm_campaign=whatsnew-88`).

---

#### Success Criteria
- [x] Attribution from /whatsnew pages can passsed along to vpn.m.o.

**Comment by gkabbz** [comment]
Yes we'll definitely need the whatsnew attribution to be passed given it's importance as an acquisition channel for owned media. I'd recommend utm_source=whatsnew or utm_source=mozilla.org-whatsnew (depending on which of these will be accepted by the FxA regex). I think it's helpful if the source does not have the whatsnew version number as it makes it easier to aggregate across multiple whatsnew pages. Then we can have the specific whatsnew version number in the campaign field utm_campaign=whatsnew88 (structure again defined so that it doesn't get stripped by FxA).

**Comment by alexgibson** [comment]
Sounds good, thanks @gkabbz!

**Comment by alexgibson** [comment]
Given the above recommendations, let's use something like:

Source URL: https://www.mozilla.org/products/vpn/?source=whatsnew88

Leads to subscription URL params like so:

- entrypoint=www.mozilla.org-whatsnew
- utm_source=www.mozilla.org-whatsnew
- utm_campaign=whatsnew88

@gkabbz I'm assuming here that `entrypoint` should always be the same as `utm_source`, which is a rule we generally stick to. Let me know if that asumption is not correct here and we should keep it different?
