### ISSUE TITLE
Incorrect # of countries on VPN page w/ waitlist

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla/bedrock#10197]
## Description

• The number of countries on the VPN page for the waitlist is incorrect.

### Steps to reproduce

URL: https://www.mozilla.org/en-US/products/vpn/

VPN into an unsupported country like Spain and observe the region count.

![Screenshot_20210511-194024.png](https://user-images.githubusercontent.com/17863082/117897681-44d8e800-b291-11eb-8dce-7c6a35acc132.png)

### Expected result

The text should say 8 countries.

### Actual result

The text says 6 countries.

### Environment

* Firefox Nightly v90 (2015809803) on Android

source: https://www.reddit.com/r/firefox/comments/na6qk6/lets_learn_to_count_with_mozilla_vpn_us_uk/

**Comment by alexgibson** [comment]
Thanks for reporting this! The value should have been behind a feature flag that got updated. I’ll take a look as to what’s up.

**Comment by alexgibson** [comment]
The number is correct on [dev](https://www-dev.allizom.org/en-US/products/vpn/?geo=es), so my assumption is the switch didn't work quite right in production because this particular switch is in the [settings file](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1364-L1367), and not the view. Either way, this should be fixed by https://github.com/mozilla/bedrock/pull/10174

Thanks for reporting.
