### ISSUE TITLE
mozilla.org/contribute's link for contributing to the mozilla codebase redirects from MDN to an archived github index

### ISSUE THREAD

**Issue by chutten** [mozilla/bedrock#10244]
## Description

Clicking on "Contribute to the mozilla codebase" at https://www.mozilla.org/contribute/ ends you up at https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/developer_guide/introduction

### Steps to reproduce

1. https://www.mozilla.org/contribute/
2. Click on "Contribute to the Mozilla Codebase"

### Expected result

Should be sent to codetribute or https://firefox-source-docs.mozilla.org/contributing/contribution_quickref.html or something? Maybe?

### Actual result

Get sent to a Github page for an archived piece of MDN

### Environment

Firefox Nightly 90 on Linux

**Comment by alexgibson** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1714434

But there are two different links suggested in each bug. Which one is better?

- https://firefox-source-docs.mozilla.org/setup/getting_set_up.html 
- https://firefox-source-docs.mozilla.org/contributing/contribution_quickref.html

**Comment by gabrielesvelto** [comment]
The first link is broader in what it covers so I think it's a better fit to replace the old page (which covered multiple topics). That being said I'd add a link to the second link in that page and update its contents (e.g. it still uses the Fenix/Firefox Preview name but I guess that should be changed to Firefox for Android now).

**Comment by jgraham** [comment]
FWIW the "getting set up" page (apart from being outdated as you note) seems like a bit of a dead end to me. It tells you that there are a bunch of projects using different languages, but doesn't really tell you how to contribute to any of them, and if you click "next" you're suddenly in detailed docs for building Firefox on Windows. I also somewhat wonder about the model where we assume people are coming in with a predetermined set of skills but no specific idea what they want to work on. Whilst I see some people who fit that model, I also see a lot of people who are more in the category of "I want to fix a bug in [project] and need help with the mechanics of that".

I think if we want to use that page as the main entrypoint, we should rework it so that it clearly links to matrix (since that's necessary for almost any non-trivial contribution), and links directly to the project-specific ontributing docs.

**Comment by gabrielesvelto** [comment]
> FWIW the "getting set up" page (apart from being outdated as you note) seems like a bit of a dead end to me. It tells you that there are a bunch of projects using different languages, but doesn't really tell you how to contribute to any of them, and if you click "next" you're suddenly in detailed docs for building Firefox on Windows.

We could add a paragraph "I just want to dive into Firefox code" that points to the quickref. That being said the page is at the top of our detailed build and contribution instructions (such as https://firefox-source-docs.mozilla.org/setup/contributing_code.html) so maybe we should re-org that to more clearly point to the additional resources.

> I think if we want to use that page as the main entrypoint, we should rework it so that it clearly links to matrix (since that's necessary for almost any non-trivial contribution), and links directly to the project-specific ontributing docs.

It's in the second paragraph (it's a link to the #introduction channel) but maybe we should make it stand out more?

**Comment by alexgibson** [comment]
What was the resolution here, do we have a recommended URL to use instead of what's currently linked?

**Comment by alexgibson** [comment]
Fixed by https://github.com/mozilla/bedrock/pull/10344
