### ISSUE TITLE
Add pricing to the subheader for EN at the top of the VPN landing page

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10286]
## Description

target: EN-US only

Add this copy above the CTA:

"US $4.99/mo - This introductory offer ends soon."

Updated Mock:

![image (10)](https://user-images.githubusercontent.com/2030656/122953059-46d3a380-d333-11eb-8a06-187a00ce420b.png)

---

#### Success Criteria
- [x] Copy is confirmed and approve by creative studio (Mary)
- [x] Confirm these changes are for English and supported countries.
- [ ] Coded on Demo
- [ ] Launch

**Comment by slightlyoffbeat** [comment]
Copy is not final yet.

**Comment by slightlyoffbeat** [comment]
This is a request from product marketing. 

@alexgibson Any flags since we are showing price here? Could we do this as an english-only update?

**Comment by alexgibson** [comment]
@slightlyoffbeat the landing page design has several blocks for conditional content based on country, where we can swap things out easily enough. If you want to keep this change really simple, I'd suggest adding this new line of copy inside the conditional block here:

![image](https://user-images.githubusercontent.com/400117/122356116-64c39180-cf4a-11eb-8caf-7743a913c484.png)

If not, this will require custom logic to ensure that only people in wave 1 countries where VPN is available will see the copy. It will also need to be hidden if the switch called `vpn-variable-pricing-wave-1` is `True`.

It should be fine to hard code in English, since wave-1 countries are all English speaking.

**Comment by alexgibson** [comment]
> It should be fine to hard code in English, since wave-1 countries are all English speaking.

Oh actually no, this will need translating. Unless we just want to wrap it in an `en` conditional and only people seeing the page in English would see it.

**Comment by alexgibson** [comment]
@slightlyoffbeat I would also suggest we make it clearer in the copy that 4.99 is a monthly subscription, as that may not be so obvious until someone goes through the signup flow?

**Comment by slightlyoffbeat** [comment]
Copy and direction is approved by creative & PMM (includes adding /mo per suggestion by @alexgibson )

This is now ready to be worked on.

**Comment by alexgibson** [comment]
@slightlyoffbeat 

I figured this was maybe overkill for a demo server? Here's a screenshot of the copy in place:

![image](https://user-images.githubusercontent.com/400117/122957544-f0d61e80-d379-11eb-9942-c8c664de8d9f.png)

Note: I used Inter for the font instead of Zilla Slab as at this size the latter gets a little harder to read (hence why we only tend to use it for headings).

Does this look ok?

**Comment by slightlyoffbeat** [comment]
@alexgibson  👍. LGTM. I agree that Inter looks better here.

**Comment by Dev-muse** [comment]
Hi , 
If it's not too late I was wondering if this change to the colour would fit with what you're trying to do with the landing page?
![chrome-capture](https://user-images.githubusercontent.com/13288580/123283693-88b34400-d503-11eb-8be3-b04536b64f07.jpg)

**Comment by slightlyoffbeat** [comment]
@alexgibson is this coming straight from an approved color palette? If so, this looks good to me. I'm not sure if the contrast fits our accessibility requirements?

**Comment by slightlyoffbeat** [comment]
We will leave black. Thanks for the suggestion though.
