### ISSUE TITLE
Get Mozilla VPN link on Contentful home page goes to getpocket.com

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10447]
## Description

The "Get Mozilla VPN" link on Contentful home page goes to `getpocket.com` instead of `/products/vpn/`.

### Steps to reproduce

1. https://www-dev.allizom.org/en-US/
2. Scroll down the the "Protection for your whole device, on every device" section.
3. Click "Get Mozilla VPN".

Screenshot: 

![image](https://user-images.githubusercontent.com/400117/133110062-b3b25e87-f33f-4a8f-8ff0-ad693f3e225c.png)

### Expected result

The page should navigate to https://www-demo1.allizom.org/en-US/products/vpn/

### Actual result

The link goes to https://getpocket.com/?utm_source=www.mozilla.org-home&utm_medium=referral&utm_campaign=home

### Environment

N/A

**Comment by pmac** [comment]
Related to #10443

**Comment by alexgibson** [comment]
This particular issue seems to be because these are the only current choices for CTA links:

![image](https://user-images.githubusercontent.com/400117/133111572-6e158e1d-7ae3-42ad-91f2-4f85554ddbb0.png)

The corresponding code in bedrock also only checks for these three product types:

https://github.com/mozilla/bedrock/blob/master/bedrock/contentful/templates/includes/contentful/cta.html

**Comment by slightlyoffbeat** [comment]
@alexgibson Yes, this was my mistake. I meant to file something for this.

The split component should be depreciated in general, but I think whatever replaces it should be able to choose between either a dropdown of links (that make it easy to have the correct parameters) or a custom field that will override.

For now, it seems best to add VPN so that we can ship.
