### ISSUE TITLE
Do not show the Firefox iOS App Store banner when using Firefox iOS

### ISSUE THREAD

**Issue by st3fan** [mozilla/bedrock#10571]
## Description

When I visit www.mozilla.org from an iPhone running Firefox for iOS, the website is showing me a banner asking me to install Firefox for iOS from the App Store.

I don't think this happened before. It is possible that something changed in iOS 15 or recently in Firefox iOS that caused the browser detection to fail?

### Steps to reproduce

Visit https://www.mozilla.org using Firefox iOS.

### Expected result

The banner should not appear.

### Actual result

The banner appeared.

### Environment

Firefox iOS 38.1 on iOS 15.

![image](https://user-images.githubusercontent.com/28052/136585455-1eb27a8a-afbb-49c3-8f2f-5f83b45303dd.png)

**Comment by Ingi-Hong** [comment]
Is this something you'd still like to discuss/see resolved? Was thinking about tackling this with UA but unsure if that's satisfactory.

**Comment by stephaniehobson** [comment]
Fixed in #13331

**Comment by stephaniehobson** [comment]
Oops, not fixed, that branch was closed.

**Comment by janbrasna** [comment]
Oh I thought this was some form of a _smartbanner_ ala https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners (that changes depending on whether the app is installed, is supported by the OS or available in the local store etc.) — but I haven't thought of how it would interact with a UIWebView inside the app ID it's actually targeting;D … and now I see it's a bespoke component here. That one really needs the extra condition to hide if already using the browser, as it looks weird offering you a new browser when you may have just downloaded it;)

For the record, there's nothing extra for Focus — the logic is basically:
_(not caring what UA is used, Focus or not, Firefox or not)_
- show Firefox mobile banner on homepage, /firefox/browsers/ and /firefox/browsers/mobile/
- show Focus banner on /firefox/browsers/mobile/focus/

I'll look into improving it (ideally maybe promoting the other browser…), but since Firefox mobile and Focus both identify alike, there's probably no chance telling them apart, and showing only the banner for the "other" browser. So in the end, this may only be resolved by not showing any of the mobile banners for any FxiOS (or Firefox/Mobile on 🤖) client.
