### ISSUE TITLE
[contentful] Home page has inconsistent content margins

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10668]
## Description

https://www-dev.allizom.org/en-US/contentful-preview/01i30zNjYwlPkmcAoc1hy0/

This might just be something that triggers my OCD, but the lack of clear/consistent content margins makes my brain struggle with the natural flow of the home page. It feels like each section is floating in its own, almost random space. It's particularly noticable when scrolling down on a smaller laptop screen, vs a large monitor. This is partly due to mismatching of Protocol components and recent churn, but is also compounded by some variable / inconsistent image sizing.

See red margin guide in screenshot below:

![page-margins](https://user-images.githubusercontent.com/400117/139859369-3df971ca-2572-4eef-a11e-ff8433e5eb70.png)

**Comment by craigcook** [comment]
The big MR2 promo has a deliberate inset because that was specified in the design, but I didn't push back on that or ask for the reasoning, so maybe we'd be fine with losing that padding.

The others are all using the Hero component that lets images overflow their container, so they'll never align on the outer edges. Hero was made for big decorative images at the top of a page and really isn't suited for this use case. It's making all the images larger than they probably should be.

They should also probably alternate direction, not all be stacked the same way like this.

The "Firefox is for (internet) lovers" one looks especially wonky since the image is a solid rectangle, so it has a distinct edge. The others don't have edges so even though they also overflow it's not creating such a clear line. That image is probably more suitable for a card than a hero.

**Comment by craigcook** [comment]
It also looks like the VPN image is aligned right but should probably be centered.

**Comment by maureenlholland** [comment]
Closing as completed with the switch to Split components: https://github.com/mozilla/bedrock/pull/11712
