### ISSUE TITLE
[contentful] Home page billboard images are too large / blurry

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10667]
## Description

Contentful home page: https://www-dev.allizom.org/en-US/contentful-preview/01i30zNjYwlPkmcAoc1hy0/

![image](https://user-images.githubusercontent.com/400117/139855847-904e24f1-adb2-47d0-bff0-42569b71eb69.png)

Protocol component: https://protocol.mozilla.org/demos/billboard.html

![image](https://user-images.githubusercontent.com/400117/139855939-7cf4993e-115f-4a19-afbd-84b35673e35e.png)

**Comment by maureenlholland** [comment]
Still an issue with Split-based homepage. I tested changing the "Image Pop" field value to "Top" instead of "Both". It was an improvement on the medium screen sizes imo, but looked pretty bizarre on larger screens.
![medium](https://user-images.githubusercontent.com/19650432/221197434-c8d376d6-e711-4388-9a6d-4ab932e3d277.png)
![large](https://user-images.githubusercontent.com/19650432/221197436-5542a7d5-1190-4d9e-a924-b08437301e2f.png)

Since billboard is deprecated and split doesn't exactly fit the existing image size expectations, we probably need to get a larger image asset to keep clarity on larger screens.

**Comment by alexgibson** [comment]
No longer relevant now Contentful home page is removed in https://github.com/mozilla/bedrock/pull/13447
