### ISSUE TITLE
[contentful] Home page hero components render nested <p> elements

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10677]
## Description

https://www-dev.allizom.org/en-US/contentful-preview/01i30zNjYwlPkmcAoc1hy0/

This might go away once the page no longer uses the Hero component, but I noticed the descriptions all render using double nested `<p>` elements, which is invalid markup:

```
<p><p>Super fast and fiercely independent. Get the only browser that works to make the internet better for everyone.</p></p>```

**Comment by maureenlholland** [comment]
This is Hero-specific, due to the way we wrap the description in <p> tags in the [hero macro ](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/macros-protocol.html#L46) and [include external HTML in the desc argument](https://github.com/mozilla/bedrock/blob/master/bedrock/contentful/templates/includes/contentful/all.html#L23).

It will not be a problem once we upgrade to Split, as that macro already expects external HTML

**Comment by maureenlholland** [comment]
![Screenshot 2023-02-24 at 1 56 08 PM](https://user-images.githubusercontent.com/19650432/221196202-5d1c0881-56a4-4571-8c02-33feb19d2350.png)
confirmed fixed after split-based homepage update
