### ISSUE TITLE
[Contentful] Unnecessary class is being added to some elements

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10768]
## Description

I am seeing the class `mzp-c-cta-link` being added to empty paragraphs. It is also  being added to one specific paragraph and I cannot figure out why.

What is in Contentful:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/2030656/142077372-d8d21d4f-c561-4dd7-a5fd-e8e35b4fc282.png">

What is rendered:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/2030656/142077407-47b7a362-fa0f-43c2-a55b-42dea745f7d0.png">

these paragraphs have the `mzp-c-cta-link` class added.

### Steps to reproduce

I am editing this resource in the compose view: `the-difference-between-a-vpn-and-a-web-proxy`

I scroll down to the paragraph that starts with: Firefox Private Network is an easy to install browser extension that provides a secure

I can delete that paragraph and create another one. As long as I start the paragraph with a link, that class is added.

That class is also added for blank paragraphs.

**Comment by alexgibson** [comment]
I took a lookinto this and it seems like we apply some logic to paragraph formatting here: https://github.com/mozilla/bedrock/blob/master/bedrock/contentful/api.py#L305-L309

the logic asumes we should apply the `.mzp-c-cta-link` class to any paragraph that contains only one link, which feels a little too magic to me. I'm not sure that logic should really imply any special styling, so I think it's probably better to remove this condition altogether.

If we want to use `mzp-c-cta-link` in Contentful then I think we should add this as another CTA option, instead of try to infer it using logic that is invisible to content publishers.
