### ISSUE TITLE
[Dec 21] Enable home page fundraising banner for EOY

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10793]
## Description

Enable morning of Dec 21st

- `SWITCH_FUNDRAISING_BANNER_EOY2021=on`
- `SWITCH_FUNDRAISING_BANNER_GIVING_TUESDAY_2021=off`

Can be turned off Jan 1st.

---

#### Success Criteria
- [x] Fundraising banner is live for EOY period.

**Comment by Ayushsunny** [comment]
Hello @alexgibson I wanted to know more about this issue, please

**Comment by craigcook** [comment]
Fixed with https://github.com/mozmeao/www-config/commit/c4d879c6bba9919762f24688fbf1de81c714fb28

@Ayushsunny We often control some parts of the site with a "switch," which is a configuration setting that lets us quickly enable/disable a feature without needing to do a full code deployment ([see bedrock docs](https://bedrock.readthedocs.io/en/latest/install.html#feature-flipping-aka-switches)). The fundraising banner was added previously but hidden by a switch, and this issue was just so we didn't forget to activate it on the appointed date.
