### ISSUE TITLE
Privacy notice for Klar is incomplete

### ISSUE THREAD

**Issue by flodolo** [mozilla/bedrock#10850]
Klar used to have a separate file for German, but they were unified recently in a single file.

https://www.mozilla.org/de/privacy/firefox-klar/

This shows the right title, but:
* The date shows the month, while it should show `14. Oktober 2021`
* The entire first paragraph is missing.

See the original source doc
https://github.com/mozilla/legal-docs/blob/master/de/focus_privacy_notice.md

**Comment by flodolo** [comment]
I compared the file for de and other locales, and couldn't spot anything strange. I wonder if there's code that treats German in a different way for that specific file.

**Comment by alexgibson** [comment]
I took a look at this locally and I think I might have figured out what's happening. Because the file is markdown, the date formatting is being interpreted as a list item:

`14. Oktober 2021`

Resolves to 

`<li datetime="2021-10-14">Oktober 2021</li>`

This them also messes up the lead-in paragraph, because the next sibling is assumed to be a paragraph, but it's actually the list parent.

Is it possible to try escaping the period?

`14\. Oktober 2021`

**Comment by flodolo** [comment]
> Is it possible to try escaping the period?

Absolutely, done in https://github.com/mozilla/legal-docs/commit/3507636a0bd6296640b9abcfe70ed8ec4fec92b2 (and noticed there's at least another doc where that's done)

**Comment by flodolo** [comment]
Thanks, that worked
https://www-dev.allizom.org/de/privacy/firefox-klar/

I wonder if there's a way to make the parser deal in a more robust way with this? With that said, if it happens again, at least we know.

**Comment by alexgibson** [comment]
> I wonder if there's a way to make the parser deal in a more robust way with this? With that said, if it happens again, at least we know.

I'm not really sure here. The parser is working in that it's interpreting markdown correctly. But I'm not sure we can easily tell between an intentional list and an unintentional one, if they are both formatted in the same way.

But at least for now, we have figured out the issue and solved it in this case. I'm going to close this for now, but we can always try and figure something better out if it catches us again.

Thanks @flodolo!
