### ISSUE TITLE
eslint error in mozilla-cookie-helper.js

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#11148]
## Description

With the pre-commit updates in https://github.com/mozilla/bedrock/commit/74d40595e2841e40caa6da7933fb84ca66cd66fd there is now an eslint error that should be fixed or looked into at some point.

The output from `pre-commit run --all-files` shows this error

```
/Users/rob/git/bedrock/media/js/base/mozilla-cookie-helper.js
  147:17  error  Backreference '\1' will be ignored. It references group '((?:^|\s*;)[^=]+)' which is in another alternative  no-useless-backreference
```

**Comment by alexgibson** [comment]
It looks like https://github.com/mozilla/bedrock/commit/74d40595e2841e40caa6da7933fb84ca66cd66fd updated the version of ESLint the Git hook uses to v8. However the code base still uses ESLint v7 (the version in package.json), which is why this wasn’t picked up in CI.

We can fix the linting error, however we should really make sure we’re not using mismatching versions of the library, else we might start to run into more errors. It’s a shame the git hook can’t just use the same version of ESLint we use in the rest of the project.

**Comment by robhudson** [comment]
Thanks @alexgibson! I can change the pre-commit hook version back to v7.x. I simply ran `pre-commit autoupdate` to bump up the libraries.

**Comment by robhudson** [comment]
https://github.com/mozilla/bedrock/commit/02925d5d01c17b1bce112f13141e5e91b5ff42ad
