### ISSUE TITLE
download.mozilla.org serving months-old download as "latest"

### ISSUE THREAD

**Issue by wonbug** [mozilla/bedrock#11173]
### Steps to reproduce

Try to download the latest Firefox APK for Android from https://download.mozilla.org/?product=fennec-beta-latest&os=android
This link has worked well for years.

### Expected result

I get the latest version of Firefox for Android.

### Actual result

I get Firefox 68, which is months out of date, without any warning or indication it isn't the "latest" version available.

### Environment

Android 11

**Comment by Ayushsunny** [comment]
@alexgibson what do you think about this issue?

**Comment by alexgibson** [comment]
@wonbug the link you reference above is for Fennec, which is the old version of Firefox on Android. Fenix is the latest version, for which you can find APKs for here: https://github.com/mozilla-mobile/fenix/releases

Since https://github.com/mozilla/bedrock/issues/8938, we no longer provide APK links for Android on www.mozilla.org, because right now there is no automation built to support this. Instead, we provide direct links to the Play Store. That may change in the future.

**Comment by wonbug** [comment]
> @wonbug the link you reference above is for Fennec, which is the old version of Firefox on Android

Users don't know that's the "old version" - and Firefox itself makes no indication it's out of date. If the APKs are not for use, don't offer them for download, especially at a URL titled "latest".

**Comment by wonbug** [comment]
> Users will always get the latest version from there.

You're making assumptions. Have you checked server logs for how many requests for `fennec-beta-latest` have been received in the last month? Have you seen if download URLs to Github are available on www.mozilla.org? (They are not.) Have you downloaded and used "fennec-latest" to apprehend there's no indication to the user they're using a browser months out of date? I'm asking you consider this from other users' points of view and at a minimum remove "fennec" downloads which no one except you know mean "an old version we don't support but still offer to download and install".

**Comment by alexgibson** [comment]
@wonbug as far as www.mozilla.org goes there are no links to the fennec download URL you provide above. It’s no longer possible to download it from our public facing web pages. Yes, you can still download it directly from download.mozilla.org if someone happens across the URL somewhere else. Hopefully we can get that fixed in the future, but like I previously mentioned the Fenix APKs are not yet available directly via download.mozilla.org.

**Comment by alexgibson** [comment]
@wonbug i filed a bug for download.Mozilla.org for you here: https://bugzilla.mozilla.org/show_bug.cgi?id=1756697

**Comment by alexgibson** [comment]
@wonbug the most helpful thing you can do here is to move the discussion into the bug I filed for you. If you can provide examples of public websites that are still offering this outdated download link, then that would be a really helpful thing for the team responsible to use for prioritisation.

**Comment by wonbug** [comment]
Would it be possible to query your web server logs for requests for the outdated installer? If it's sufficiently low, the point is probably moot. But I suspect it may be in the thousands.

**Comment by alexgibson** [comment]
@wonbug again as previously requested, please move questions and discussion on this into the bug I linked above for you. This is not the right place to try and get this issue fixed. If you can also provide examples of sites where this link is still present and add that to the bug, that would be very helpful.
