### ISSUE TITLE
The fundraising banner size

### ISSUE THREAD

**Issue by denisgon** [mozilla/bedrock#11216]
## Description
The fundraising banner on https://www-dev.allizom.org/ occupies the whole screen in Russian localization because of the long text and long numbers in roubles (₽). There is no way to short the text, so one of the methods to solve the problem is to miniaturize the size of the button paddings. Also it would be grate if you could suggest some other solutions of the problem.

![изображение](https://user-images.githubusercontent.com/93614255/154498121-c61bb8a8-5912-4d5f-8014-bfef64616c6d.png)

### Steps to reproduce

Miniaturize the size of the button paddings in the fundraising banner on https://www-dev.allizom.org/
Suggest and realize some other solutions of the problem.

### Expected result

The fundraising banner on https://www-dev.allizom.org/ occupies no more than 60% of the screen in Russian localization.

### Environment

The problem doesn't seem to depend on environment.
The problem was confirmed in Firefox (v. 97.0) and Chrome (v. 98,0) on Windows 7.

**Comment by craigcook** [comment]
We could do some language-specific styling to reduce the font-size of the headline for those languages where it runs especially long. Note that this banner isn't currently in use, it just appears on the dev server because it's controlled by a feature switch that defaults to "on" in dev mode.

Next time we run the fundraising banner we should be mindful of how the main headline will flow in some languages.
