### ISSUE TITLE
Document latest CSS bundles update

### ISSUE THREAD

**Issue by reemhamz** [mozilla/bedrock#11382]
## Description

We've updated how we use Protocol imports in Bedrock. This update enables us to use bundle imports rather than direct imports in the CSS files. We've done this because we had close to ~650 CSS imports, and we'd have a lot of HTTP requests when loading pages, AKA it was a tad heavier on the performance side of things.

With this update, we were able to reduce some load time because only necessary CSS imports would be triggered based on what the page was requesting. Not to mention it's made remembering how to import easier imho.

Hence, we're going to need to document how we newly import Protocol components into respective templates.

The issue related to this is #11032 

---

#### Success Criteria
- [x] Update Bedrock documentation to reflect recent changes

cc: @alexgibson should we keep the parts detailing [how to import Protocol components in CSS files](https://bedrock.readthedocs.io/en/latest/coding.html#working-with-protocol), or should we remove that from the docs?

**Comment by alexgibson** [comment]
> We've done this because we had close to ~650 CSS imports, and we'd have a lot of HTTP requests when loading pages, AKA it was a tad heavier on the performance side of things.

This is sort of along the right lines, but not quite. We did have a large number of CSS imports that we had to process at build time, so we’ve now reduced those by using more common pre-built CSS bundles. The result is we now have faster site build times and improved caching between page navigations when browsing the site, but at the cost of a few extra HTTP requests for CSS files when loading pages. So it’s a performance trade-off really, rather than a straight up improvement.

> With this update, we were able to reduce some load time because only necessary CSS imports would be triggered based on what the page was requesting. Not to mention it's made remembering how to import easier imho.

We’ve improved our build time for processing all the CSS files the site needs. But we’ve likely decreased our performance a little (not a high amount thanks to HTTP/2). It’s a trade off we have to be sensible about.

**Comment by alexgibson** [comment]
> cc: @alexgibson should we keep the parts detailing [how to import Protocol components in CSS files](https://bedrock.readthedocs.io/en/latest/coding.html#working-with-protocol), or should we remove that from the docs?

Up to you if you think it’s useful. Personally I think it’s probably enough just to mention that we have pre-build bundles for our most common components.
