### ISSUE TITLE
Evaluate Jasmine Browser Runner

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11398]
## Description

[Jasmine](https://jasmine.github.io) now offers it's own [browser runner](https://www.npmjs.com/package/jasmine-browser-runner) package. Might this be an alternative [Karma](https://karma-runner.github.io/l) (less dependencies, with tighter coupling to the test framework)?

We should try it out to see how it works with bedrock's test suite.

**Comment by nathan-barrett** [comment]
Been spending the last few days on this - but I'm not sure it has everything that we need to use it in bedrock - a few pain points that I noticed from my time working on it:

 - For javascript files to be treated as es modules they currently need to end in the extension `.mjs` [source](https://github.com/jasmine/jasmine-browser-runner/blob/e96564f42c5407630b26c52ca4512c9c855faf8b/release_notes/0.5.0.md#new-features)
 - I didn't seem able to use webpack as a preprocessor like we do currently in Karma. If you aren't using ES Modules (which allows import statements) - libs that we usually retrieve via `require` statements would need to be accessed globally (which would take some editing of our current test files
 - Due to MIME type, I'm currently not able to load any images with `jasmine-browser-runner` - which is something we can do in Karma

I think once a few of these pieces get fixed I'd be happy for us to take a second look, but I don't think it would work for bedrock at the moment.

**Comment by alexgibson** [comment]
Thanks for taking a look at this one @nathan-barrett! I agree it sounds like it's missing some features we currently rely on. Closing this and we can revisit perhaps some time in the future.
