### ISSUE TITLE
New Sentry instance is not recording user counts

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11484]
Our new Sentry instance is not recording the number of users for new issues created. This applies to all our Sentry projects for bedrock (both backend and front-end).

![image](https://user-images.githubusercontent.com/400117/163003720-bfb15404-29ef-4862-b6b2-f848cfa3ba50.png)

**Comment by alexgibson** [comment]
This might be because we're filtering out IP addresses, which is maybe a reason why this could be fine as a wontfix.

**Comment by stevejalim** [comment]
Explored and discussed this a little just now and I agree - we have `Prevent Storing of IP Addresses` enabled (and I can't disable it with an Admin hat, even if we wanted to) so I think we lack [any factors that Sentry uses to identify a distinct user](https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/), partic because all our users are unauthenticated.

As such, closing as wontfix, with @alexgibson's blessing
