### ISSUE TITLE
Feedback for /about/webvision

### ISSUE THREAD

**Issue by k88hudson** [mozilla/bedrock#11501]
Hey! I took a look at https://www.mozilla.org/en-US/about/webvision/full/ and have some design feedback. In general, I think it would be great it if were more in line with the [manifesto](https://www.mozilla.org/en-US/about/manifesto/details/) page, for example:
* Can we align the top of the first item in the sidebar with the top of the article, more like manifesto or [in this demo](https://protocol.mozilla.org/demos/article.html)?
* Can we use heading styles for the top-level headings (Our Values, etc.)?
* I think it would look better with less space between the sidebar and the article (again, more like the manifesto or article demo linked above)

Another issue I'm seeing is that because the sidebar is so long, we're getting a scrollbar on most screen sizes, which isn't really ideal. Could we consider an option with less inter-item spacing (if there is such an option) or having it not be sticky?

Thanks!

**Comment by pmac** [comment]
Thanks Kate! We'll take a look and get back to you shortly.

**Comment by reemhamz** [comment]
Thanks for  the feedback @k88hudson, I'll get on it and show you what I come up with.
We also had some [feedback from Peiying](https://github.com/mozilla-l10n/www-l10n/pull/281) regarding usage of the word `Web` in regards to the Web Vision content. We chose to link the Web Vision to other pages here and capitalize the word `Web` instead of keeping it as `web`: 
- https://www.mozilla.org/en-US/about/
- https://www.mozilla.org/en-US/about/manifesto/details/

Do you prefer we keep it consistent with the title that uses the capitalized word (`Mozilla’s vision for the evolution of the Web`), or keep it strictly lowercase where we were referring to the Web Vision page?

**Comment by reemhamz** [comment]
A few updates regarding changes:

I managed to do the following pretty well:
- aligned the top of the sidemenu with the article
- fixed spacing between sidemenu and article

I really don't think it's a good design move to have heading-level styles on the top headings for the sidemenu, so I opted to just making them bolded, which aligns better with the rest of the sidemenus we have throughout Bedrock. 

I also won't be able to minimize the spacing of the list items without making them look too janky. Truth is, for it to be consistent with our Protocol designs, it won't make much sense to squish the items together to get rid of scrolling. 

You can take a look at the PR here for now until its merged: https://github.com/mozilla/bedrock/pull/11505

**Comment by reemhamz** [comment]
Also, here is the demo for the changes: https://www-demo3.allizom.org/en-US/about/webvision/full/

**Comment by k88hudson** [comment]
Awesome, this looks great! On the capitalization of `Web`, yes, please keep it capitalized. 

Thank you!
