### ISSUE TITLE
FF100 landing page Google Play Store link sends to Apple App Store

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11691]
## Description

On https://www.mozilla.org/en-US/landing/firefox/fx100 there are buttons to the Play Store and the App Store but both of them go to the App Store.

The links are different in terms of adgroup, but have the same IDs:

* Play Store: https://app.adjust.com/jcn6eyw?campaign=firefox100&adgroup=android-store
* App Store: https://app.adjust.com/jcn6eyw?campaign=firefox100&adgroup=ios-store

**Comment by stevejalim** [comment]
@slightlyoffbeat Is this sometihng that's tweakable in Adjust, or has the wrong link been used for the Play Store, please?

**Comment by slightlyoffbeat** [comment]
@stevejalim this is as designed. This landing page will be shown to mobile users only. On mobile, it should detect platform and redirect to apple or play store accordingly.

If we use adjust links that could also be viewed on desktop, then we will often force the adjust link to always show one or the other. Since this is mobile-only, we just let adjust do detection and direct accordingly. We could even use the same link for both, but have some slightly different URL parameters for extra click data.

**Comment by stevejalim** [comment]
Thanks @slightlyoffbeat - tried it from my Android phone and the page only showed the Play Store link, which then went to the correct destination of the Play Store. Thanks for the explanation!

Closing!

cc @alexgibson

**Comment by alexgibson** [comment]
I guess I'm still a little confused by this. I get that technically no one on a desktop browser should see this, which might mask the behaviour that Steve noticed. However I also suspect that it's likely this assumption won't remain true in every scenario (UA detection is known to be problematic, especially in the way Adjust seems to handle it).

We have two separate buttons on the page, so is there a technical reason why we can't have two separate links, that always take you to the place we'd expect?

**Comment by slightlyoffbeat** [comment]
There is not a technical reason we can't do this. But if UA ever doesn't work for someone on a mobile device, this should help increase the chances that they will always be shown the correct app store/play store after clicking a link.

The risk is if a desktop user ever finds this page, which shouldn't happen.
