### ISSUE TITLE
Broken link on rest-of-world home page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#11703]
## Description

https://learning.mozilla.org/ seems to no longer exist

### Steps to reproduce

1. Open https://www.mozilla.org/es-ES/
2. Click the link [Empoderando a las mujeres en línea](https://learning.mozilla.org/blog/new-partnership-with-un-women-to-teach-key-digital-skills-to-women/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=homepage)

### Expected result

The link should work.

### Actual result

The link does not work.

### Environment

N/A

**Comment by Ayushsunny** [comment]
Hello @alexgibson,
will it work if we'll replace that link with [this link](https://blog.mozilla.org/foundation-archive/mozilla-learning/new-partnership-with-un-women-to-teach-key-digital-skills-to-women/)?

**Comment by Ayushsunny** [comment]
@itachi9604 is this some kind of loot or what Mr. Pranay? I already left my last issue for you because you were a beginner but you came here and made a PR without even asking me and you knew that I was gonna make PR for this issue? Do you really want to learn something from here or just want to show green dots on your profile? this kind of childish behavior won't be acceptable from next time.

**Comment by alexgibson** [comment]
@Ayushsunny please try to be respectful and assume that everyone here has the best of intents, as per our [code of conduct](https://www.mozilla.org/en-US/about/governance/policies/participation/). Whilst certainly it's true that you asked a question on this issue first, that doesn't necessarily makes it clear to everyone that you are actively working on the issue. We get quite a lot of people asking questions, which is actively encouraged. But there hasn't been any activity on this issue in the past 10 days since @itachi9604 issued a PR.

From our [contributing guidelines](https://github.com/mozilla/bedrock/blob/main/.github/CONTRIBUTING.md):

> Once you have found an issue that interests you, it's worth reading through carefully to make sure that you understand what needs doing, and also to check that someone else isn't already working on it. If you're unsure about anything, then questions are always welcome. Mozilla employees are happy to try and help, but please note they may not always have the capacity to help mentor on more complicated issues. So please only take on issues where you feel you have an understanding for what needs doing. Pull requests will be reviewed on a first come, first served basis.

**Comment by Ayushsunny** [comment]
> @Ayushsunny please try to be respectful and assume that everyone here has the best of intents, as per our [code of conduct](https://www.mozilla.org/en-US/about/governance/policies/participation/). Whilst certainly it's true that you asked a question on this issue first, that doesn't necessarily makes it clear to everyone that you are actively working on the issue. We get quite a lot of people asking questions, which is actively encouraged. But there hasn't been any activity on this issue in the past 10 days before @itachi9604 issued a PR.
> 
> From our [contributing guidelines](https://github.com/mozilla/bedrock/blob/main/.github/CONTRIBUTING.md):
> 
> > Once you have found an issue that interests you, it's worth reading through carefully to make sure that you understand what needs doing, and also to check that someone else isn't already working on it. If you're unsure about anything, then questions are always welcome. Mozilla employees are happy to try and help, but please note they may not always have the capacity to help mentor on more complicated issues. So please only take on issues where you feel you have an understanding for what needs doing. Pull requests will be reviewed on a first come, first served basis.

There's hasn't been any activity because I was busy with my uni's assignments but that doesn't mean anyone will come and make PR on that issue.
As you have seen in the last issue in which he asked i politely left my issue to him but what he has done here? 
And i also think that I'm working on this repo from long time but you want your issue to be just fixed by any random person who will make single PR and leave well if you don't want them to stay and be part of your org, It's okay.

And I'm not being disrespectful to anyone in here it's that I really felt bad.

**Comment by itachi9604** [comment]
@Ayushsunny This is not a loot, and sorry that the PR intersected with yours. But it was inactive for ~10 days. And I have found so many of comments you have done at various issues. I went through issues and solved the one I could.
