### ISSUE TITLE
Language selection is not persistent throughout the pages

### ISSUE THREAD

**Issue by sharrythakur** [mozilla/bedrock#11942]
## Description

When user select a language from drop down and clicks on any other link on the page the default selected language gets changed on next page. USer has to select language on every page manually.

### Steps to reproduce

1. Go to https://www.mozilla.org/en-US/firefox/
2. Select language option from drop down below the page
3. Language changed on the page
4. click on download firefox button
5. next page shows new language as english instead of user selected language

### Expected result

Language selection should be continuous throughout the pages

### Actual result

Language has to be selected on every page user lands on

### Environment

Mozilla firefox

**Comment by alexgibson** [comment]
Thanks for filing this bug @sharrythakur!

In testing your STR above, I see that this only happens on the FIrefox download button. On regular links, we persist language like you expect.

The reason why we don't do this for most Firefox download buttons, is because many pages on the site are not as widely translated as the number of languages that we support in FIrefox. If we persisted the locale for the download button links, it would not be possible to download Firefox in someone's preferred language from many pages of the site.

Example:

- I'm on an en-US only page, but by preferred language in German. Clicking "Download Firefox" should still give me the German version of Firefox.
- I'm on a page that's translated in 20 languges, but not es-ES which is my preferred language. Clicking download should still give me the Spanish build of Firefox.

It's not an ideal situation I agree. However achieving translation parity for all pages on the site is not very likely. Perhaps in the future when we have multi-language Firefox installers more readily available we can change this.
