### ISSUE TITLE
Minorly broken HTML on MoCo diversity data page

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#13188]
## Description

On https://www.mozilla.org/en-US/diversity/2021/mozilla-corporation-data/ if you scroll to the Gender section, you'll notice a stray `>` below one of the graphs which needs fixing appropriately. 

<img width="741" alt="Screenshot 2023-05-25 at 09 28 56" src="https://github.com/mozilla/bedrock/assets/101457/04a23b90-3153-45ec-abb8-5f1460e4fbbb">

## Success criteria
- [ ] The page no longer has the stray character
- [ ] The page passes HTML validation

**Comment by yashkhandelwal123** [comment]
hi, can I work on this?

**Comment by UnejucatedGuy** [comment]
If this issue is still relevant, could you provide some guidance on how I can get started? Alternatively, if this issue has been resolved or is no longer being pursued, could you suggest another beginner-friendly issue that I could tackle? I'm eager to learn and contribute to the project. Any suggestions or guidance would be greatly appreciated.

**Comment by alexgibson** [comment]
Looks like this was fixed in https://github.com/mozilla/bedrock/pull/13191
