### ISSUE TITLE
Add / Edit email preference center strings to bedrock

### ISSUE THREAD

**Issue by krattliff11** [mozilla/bedrock#13250]
Lifecycle marketing (Tina) and Firefox accounts (Jess) will need support for revising newsletter sign-up entry points and that means we need to edit the language in the email preference center.  

Please make these changes on July 5, 2023:

(Part I) add a newsletter

Firefox accounts

Get tips from Mozilla on how to get the most out of your account. 

(Part II) edit the existing newsletter title and description formerly known as Firefox Account Tips

Welcome emails

Welcome emails that get you started using our products & services.

---

**Success Criteria**
- newsletter subscription will be visible in the email preference center - Welcome series will be visible for all who sign up for a Firefox Account after June 21st
- translation strings landed

**Comment by pmac** [comment]
Here are the slugs:

- `mozilla-accounts` == "Firefox accounts"
- `firefox-accounts-journey` == "Welcome emails"

**Comment by pmac** [comment]
Due to this needing to go live on a specific date (July 5th) but also needing to be translated, we should land the strings at least asap so that the translation process can get started. We could put these new strings behind a switch, or just not make the code changes (only the ftl file ones) until later. Ping me with questions.

**Comment by alexgibson** [comment]
@pmac @krattliff11 happy to help pick this up. I think just exposing the strings for translation ahead of time would be best here. Then I can followup with a code change on July 5th to add/swap the strings for each slug.

I'm going to assume `Firefox accounts` should be title case (`Firefox Accounts`) since it's a brand name?

**Comment by pmac** [comment]
That was my thinking as well. Get the strings landed now, then we can swap them in at the right time. We could potentially use a switch for the one replacing a current string. The other one (`mozilla-accounts`) is new so no need to wait on that one, it can go out now since no one will be subscribed to it.

**Comment by krattliff11** [comment]
As per Mary's review. 'Firefox accounts' is the case to use.

**Comment by alexgibson** [comment]
> As per Mary's review. 'Firefox accounts' is the case to use.

I believe our L10n team encourage us to use title case for Firefox Accounts for consistency throughout the website (it often seems to get picked out in PR reviews before they expose the strings for translators). I'd be happy to change that at some point if it makes sense, but it probably needs to be a conversation as to when that happens.

**Comment by alexgibson** [comment]
This has merged and we'll get it deployed today
