### ISSUE TITLE
Site switches from german to english 

### ISSUE THREAD

**Issue by topotropic** [mozilla/bedrock#13355]
## Description

I'm on https://www.mozilla.org/de/firefox/ and click on "Jetzt Firefox wählen", the site switches to the enlish/US version and the download landing page is in english https://www.mozilla.org/en-US/firefox/download/thanks/

### Steps to reproduce

See above, try it in Chrome or Safari

### Expected result

I get the german download page

### Actual result

I see the english page despite being on the german site

### Environment

Might be because my system language is english 🤷 but if I deliberately select german as site language it would be great if the site would keep that

**Comment by alexgibson** [comment]
Hi!

Thanks for filing this - yes you're right, the download switches to English because that's what you have set as your preferred language in your browser settings. Typically we do this on most pages, because having every page translated into every possible language is not a realistic target we can meet. Say if we had a page only translated in 10 languages, then you would only be able to download Firefox from that page in 10 languages (as opposed to 100+). Does that make sense? This is why we let the browser figure the most appropriate language.

That said, the campaign page we have at https://www.mozilla.org/de/firefox/ is a special case. We know that both pages are translated in German. So i think your suggestion makes sense here and we can accommodate :)
