### ISSUE TITLE
VPN RC Redirect changes

### ISSUE THREAD

**Issue by nathan-barrett** [mozilla/bedrock#13460]
Certain pages don't maintain the correct locale from the old `products/vpn/more/*` to the vpn resource center. I am assuming this is happening because certain locales haven't been fully translated for the resource center.

Adria created this [spreadsheet](https://docs.google.com/spreadsheets/d/1Ud40NM11LkxEs2dm0RAMqiRQguLLPc7n-IBtzqmOb-A/edit?usp=sharing) lists out which pages don't have equivalent translated pages.

Examples:
`https://www.mozilla.org/ar/products/vpn/more/vpn-or-proxy/` redirects to `https://www.mozilla.org/en-US/products/vpn/resource-center/the-difference-between-a-vpn-and-a-web-proxy/`

**Comment by pmac** [comment]
Let's discuss the way forward for this one a bit more. I'm told we want to bring back the old pages but only for some locales? Is that right? Has @slightlyoffbeat weighed in on this? 

My feeling is that I'd like to try to avoid a scenario where we have to maintain both the old pages and the new Contentful-based ones. If Contentful isn't working out for us here, and no one updates these pages very often, we could convert them back to static and manage them the way we do most pages.

**Comment by pmac** [comment]
I'm not clear on why the example redirect is a problem. We always redirect from a locale we don't have to the best match one that we do.

**Comment by a-kyne** [comment]
> I'm not clear on why the example redirect is a problem. We always redirect from a locale we don't have to the best match one that we do.

We had a good article in Arabic and replaced it with an article that was in English and for the US. Even beyond the usability issue, we lost all of the organic traffic that the Arabic article was attracting. I have asked Nathan to only redirect the old URLs when there is a translated document available to replace the old document, so that we are not taking perfectly good localized content and replacing it with en-US.

**Comment by pmac** [comment]
Are these english pages added or changed enough that it's worth having them in contentful? It'd be easier to maintain in these scenarios if they weren't. And we also don't get languages like Arabic via Smartling so they won't happen for new pages in contentful. It seems like we need to choose between the contentful admin and widely translated.

**Comment by a-kyne** [comment]
Hmm. What would be "enough"? I don't think I have a good sense of what that should be.

**Comment by pmac** [comment]
More than once a month maybe? I'm mostly saying we have to choose between being able to very quickly add or edit these pages without involving a developer, or solid long-term content that we can send to the larger translation community, but which would require a developer to add or update.

**Comment by a-kyne** [comment]
I don't think we're likely to add new content more than once a month; the turnaround time on all the approvals is just too slow.

**Comment by alexgibson** [comment]
From a maintenance perspective, I’m not sure it makes sense to keep older or outdated versions of pages around indefinitely. At least in the long term.

If we need these pages to have a broad range of locale support for SEO, then perhaps we should consider widening the number of locales we support through Contentful? Or failing that, we could move these pages out of a CMS and make them static where they have an option for wider l10n.

**Comment by a-kyne** [comment]
I think the larger issue is that our localization strategy is pretty haphazard. We **can** post content in other languages so we **do**, but there is no commitment to creating a good experience for users in other languages. So we get patchy support even in bigger languages like French, which can be rather disconcerting for users.

Our traditional audience, tech people who feel positively about community-supported websites, are prepared to face gaps caused by inconsistent volunteer support. As soon as we start trying to reach more broadly to normal people who are not particularly tech-focused and are used to different standards of customer service (as it were), we may need to recognize that our past practices don't scale well.

I thought we were just going to rename some files, but if we're looking at the bigger picture and trying to gauge long-term investment value, then perhaps what we need to do is to go back to the VPN PMM and ask them about how much they want to invest in these other locales. I'll just go check, shall I?

**Comment by alexgibson** [comment]
Mozilla has traditionally looked to support from volunteers for localisation efforts, rather than using an agency to pay for translations. In an ideal world we would have every page translated in every possible language all the time, but we just haven’t had those budgets that other companies can afford. We instead have to focus our content on a tiered set of locales, and anything we get above that is considered a very welcome bonus.

I’m not sure if haphazard is really the right word to use to describe that approach. It’s certainly not a commitment to 100% coverage like people want in an ideal world, but it is at least a considered approach, given the reality of our constraints.

**Comment by a-kyne** [comment]
I hope I didn't give the impression that I didn't think it's a considered approach! Just that the outcomes are not consistent, and that as we expand our audience from allies and fans to people who are meeting us for the first time, that the use of volunteers may not meet the expectations of those new people.

(BTW the specific thing that I'm thinking of is that there are links on the FR Firefox product page to SuMo, where the SuMo pages we link to are not translated into French)

**Comment by a-kyne** [comment]
@nathan-barrett PMM checked back in and said he wants to hold onto the older content as long as possible. The end result that I need is that the content is available again. Since the old URLs have been redirected, I had supposed that the easiest solution would be to republish it using Contentful, but it doesn't matter to SEO how it gets republished, just that it is. @pmac I have no opinions about the best way to manage the content (i.e. Contentful or not) and defer to your judgement.

**Comment by slightlyoffbeat** [comment]
After revisiting this, I believe we need:

1. A short/fast solution to mitigate the SEO damage that has happened from removing articles in certain locales and redirecting to English

2. A long (near?) term solution that is maintainable and scalable (and doesn't have us maintaining 2 systems/layouts).

The long term solution is that we need to get these articles translated and into contentful. We already have a system for translating, but there is an issue that some of the languages aren't in our list of supported languages currently. @stevejalim  do you know what it would take to do page translations for languages that are not in our list of languages we support in smartling? Perhaps we could translate them and add them manually? 

I imagine the case of having to have contentful content outside of our supported languages is limited to cases like this where we are replacing pages with contentful pages that have wider translations (which would not happen very often).

@alexgibson @pmac @nathan-barrett What is the scope of work to bring back the deleted pages and fix the redirects while we solve for the long term (which we will absolutely solve for). The goal being to mitigate SEO damage.

**Comment by nathan-barrett** [comment]
Wanted to check where we were with this, and what I can do to help close the issue out. The redirects were added in [this PR](https://github.com/mozilla/bedrock/pull/12938) which redirected the pages at `products/vpn/more/*` to corresponding articles in the resource center. 
Asking questions just to clarify:

@a-kyne Are we wanting to bring back the pages that we removed under `vpn/more/*` and remove the redirects entirely? 

As far as I know, since localization is done differently in contentful vs in bedrock - added those old pages to contentful wouldnt give us access to the translations for the locales we're missing currently. 

cc @pmac @alexgibson @slightlyoffbeat

**Comment by a-kyne** [comment]
@nathan-barrett The original intention was to redirect the URLs of pages in /more/ that were duplicated by pages /resource-center/. The URLs in non-/en-US/ locales that were not duplicated, and are now being redirected to /en-US/ from other locales, did not actually need to be redirected. Unfortunately some of these pages are in languages that are not even supported by translation resources in Contentful.

What I would like to do is have only the pages that were duplicated in Contentful by redirected, and the sub-nav in locations that do not have a Resource Center return to their previous structure.

**Comment by nathan-barrett** [comment]
Can and will do, thanks for clarifying @a-kyne

**Comment by a-kyne** [comment]
@nathan-barrett  Thank you so much for your flexibility!
