### ISSUE TITLE
Copy issue on ESR page

### ISSUE THREAD

**Issue by jonathan-codebase** [mozilla/bedrock#13487]
## Description

The ["Get Firefox for your enterprise" page](https://www.mozilla.org/en-US/firefox/enterprise/) has a copy issue: it says "Your data stays your business" which seems like a mistake

### Steps to reproduce

Visit https://www.mozilla.org/en-US/firefox/enterprise/

### Expected result

It should probably say something like "Your data stays private to your business"

### Actual result

It says "Your data stays your business"

### Environment

Firefox 117 on MacOS

**Comment by craigcook** [comment]
Thanks for reporting, and I can see how this could be confusing in the context of an enterprise product. But this language is intentional. It's casual US English where "business" means something with which a person is rightfully concerned, as in the phrases "mind your own business" or "what you do in your own home is none of my business." Here we're playfully saying your data isn't something anyone else should see, it belongs to you and no-one else. It's your business.
