### ISSUE TITLE
Bing includes confusing metadata when searching for Firefox using Edge

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13618]
## Description

See https://bugzilla.mozilla.org/show_bug.cgi?id=1850052 for details

We should review the embedded metadata that was added some years ago (as an SEO project), and either remove or update it where no longer relevant / needed.

The current JSON can be found here, which is embedded throughout several landing pages.

https://github.com/mozilla/bedrock/tree/main/bedrock/base/templates/includes/structured-data

**Comment by alexgibson** [comment]
@a-kyne - can you please take a look here and confirm if we are OK to remove this metadata? Thanks

**Comment by a-kyne** [comment]
Hi @alexgibson, thanks for pinging me.

This structured data is invalid for SEO purposes, as it lacks one of Google's [Required properties](https://developers.google.com/search/docs/appearance/structured-data/software-app#structured-data-type-definitions), either Review or aggregateRating. Bing [does not support](https://www.bing.com/webmasters/help/marking-up-your-site-with-structured-data-3a93e731) the SoftwareApplication feature. 

I'm not sure why this data includes the _sameAs_ (which is neither a Required nor a Recommended property).

It is not an SEO priority to pursue a Rich Results listing for our mobile product pages because I do not believe that diverting users from the search result listings for either of the places where users can download the app (i.e. Play and App Store pages) will increase our downloads or app usage. I do not think it is a good idea to include it on our Desktop download page because many users expect Rich Results application listings to be for mobile apps and it may cause confusion.

I recommend removing SoftwareApplication structured data from all pages (that is, also from the mobile app pages).

**Comment by alexgibson** [comment]
Great thanks, we'll delete all instances where it is present.
