### ISSUE TITLE
Video-embedding iframes have non-validating markup

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14042]
## Description

While adding cookieless youtube embeds to Birdbox, I was using https://www.mozilla.org/en-US/firefox/features/tips/ (and specifically [this template](https://github.com/mozilla/bedrock/blob/main/bedrock/firefox/templates/firefox/features/tips/includes/password-nneka.html)) as a reference for how we do it.

While validating the Birdbox embed, though, the W3C validator complained about there being content inside the iframe, which is also causing the Firefox Tips page to fail validation ([Report](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Ffeatures%2Ftips%2F))

I don't know if having the link to the original video in the iframe is a mitigation for older browsers or to help with a11y ([MDN suggests](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#accessibility_concerns) we just need a `title` for a11y on an iframe).  If it's neither, we should fix that page and anywhere else we use that general iframe/embed pattern (such as the careers landing page)

---

#### Success Criteria
- [ ] Pages featurng video embeds pass HTML validation (or we know a good reason why they don't)

**Comment by reemhamz** [comment]
Thanks for creating this issue!

```<a href="https://www.youtube.com/watch?v=CqGZtCZVDZ0">{{ ftl('ui-watch-the-video') }}</a>```

I took a deeper look into it, and I suppose the reason we had the above line in the first place was because YouTube didn't always have an accessible Play button that screen reader users would know to click on.
See this blog post for a relevant explanation: https://adrianroselli.com/2017/08/inaccessible-youtube-embeds.html

However, judging by the W3C validator error you got, it seems that the text we placed within the `p` tag doesn't seem to be the right thing to do anyway. I also opened up the dev tools and searched for that specific `p` tag/the text it contains, and though dev tools show that the text may exist, it's not showing me where it's found + I couldn't find it when doing my own manual digging -- keen to see if you've hit that wall as well.

That blog post was years ago now, and things have been fixed (as also mentioned in the blog post). If you use a screen reader now to go over the video, the Play button is read aloud:


<kbd>![Screenshot 2024-01-04 at 7 44 17 PM](https://github.com/mozilla/bedrock/assets/42309026/b7359332-71a9-4c37-9fb9-c620be402600)</kbd>

With that update, and assuming the reasoning behind the text we placed inside the `iframe` frame was right, I would conclude that there's probably no need for that `p` tag anymore (also because it doesn't seem to work).

Regarding the `title` attribute, it's standard practice that `iframe` elements should have the `title` attribute in the first place, as it's an accessible description for the `iframe`, since folks using screen readers may not know what is really contained inside the  `iframe`. Here's a good explanation on that, too: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#accessibility_concerns

One thing I did notice when I placed a `title` attribute in the `iframe` element in the file you mentioned is that it would only be highlighted by the screen reader 1 out of 20 times for me, but I think that's an issue with the screen reader trying to highlight the `iframe` element but it was highlighting whatever is inside it instead. Although, when it did highlight it correctly, it did read aloud the `title` attribute as expected. I'm curious if you've happened to also stumble upon that issue, too?

**Comment by stevejalim** [comment]
Heya @reemhamz - thanks for digging into this! It sounds like we can drop the `<p>` in the `iframe`, and it makes sense that we had to do it for a11y in the past. Puzzle solved! ✅ 

--- 

> I also opened up the dev tools and searched for that specific p tag/the text it contains, and though dev tools show that the text may exist, it's not showing me where it's found + I couldn't find it when doing my own manual digging -- keen to see if you've hit that wall as well.

Yeah i can confirm that behaviour. If I view source on the careers page I can find:

```
<div class="mzp-c-video">
    <iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/_EeFDE5WW0I" title="Mozillians, kids, and pets on Zoom" frameborder="0" allowfullscreen>
        <p><a href="https://www.youtube.com/watch?v=_EeFDE5WW0I&t">Watch the video</a></p>    
    </iframe>
</div>
```

But if I explore the rendered DOM with devtools then the iframe's content has been replaced by content from YouTube:

<img width="558" alt="Screenshot 2024-01-04 at 11 04 13" src="https://github.com/mozilla/bedrock/assets/101457/91f9afce-8e46-4731-bab0-6e456fc627b9">

**Comment by reemhamz** [comment]
Definitely a weird one isn't it?
I'm going to pick up this ticket and update any of our `iframe` tags who have text within them and I'll add `title` attributes to them 👍🏼 

Thanks again for filing this issue :D luckily since YouTube fixed a lot of their embedded a11y issues, this isn't a severe one, but still one to fix up ASAP

**Comment by zcorpan** [comment]
Devtools is technically incorrect (but is useful). The iframe's nested document is not a child of the `iframe` element in the DOM.

Use http://software.hixie.ch/utilities/js/live-dom-viewer/saved/12259 to see what the DOM actually looks like. The markup in `iframe` becomes a single text node, even if it looks like tags in the source code. (Similar to e.g. tags in `<style>`.)

The contents of `iframe` were useful in the past as fallback content for very old browsers that didn't support the `iframe` element (e.g. Internet Explorer 2). AFAIK, it has never been exposed in any way to assistive technology.

The HTML standard requires `iframe` elements to be empty: https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element

> [Content model](https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model):
    [Nothing](https://html.spec.whatwg.org/multipage/dom.html#concept-content-nothing).

See https://github.com/whatwg/html/pull/2049 for rationale.

**Comment by reemhamz** [comment]
Done and dusted 🧹 https://github.com/mozilla/bedrock/pull/14065
