### ISSUE TITLE
add UTM codes for links to monitor.mozilla.org

### ISSUE THREAD

**Issue by rhelmer** [mozilla/bedrock#14432]
## Description

We (the Mozilla Monitor team) noticed that we're receiving quite a bit of traffic from `mozilla.org` to `monitor.mozilla.org` without UTM parameters. We also don't receive referrers, so this makes it difficult to tell which pages and links are actually sending the most traffic.

Here is an example of a link that has the kind of info we'd hope to see:
`https://monitor.mozilla.org/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=nav&utm_content=products`

`source` and `medium` we could infer but I think it'd be best to be consistent and send them. The `campaign` and `content` are probably the most important.

---

#### Success Criteria
- [x] UTM source, medium, campaign and content parameters for links to monitor.mozilla.org

**Comment by janbrasna** [comment]
There's some links w/o utm params:
1. https://www.mozilla.org/antiharassment-tool/ under "More Mozilla products" above footer.
2. https://www.mozilla.org/products/vpn/download/mac/thanks/ in "How do I know the VPN is working?" section.
4. https://www.mozilla.org/firefox/browsers/best-browser/ mid-page above the quote.
5. https://www.mozilla.org/newsletter/updated/ in newsletter preferences confirmation.
6. https://www.mozilla.org/firefox/privacy/safe-passwords/ right above "Security Questions" — even though the comments claim the tags will be included they are not. This page is nonetheless going away in #14248
7. look for it in https://www.mozilla.org/en-US/foundation/annualreport/2018/ and https://www.mozilla.org/en-US/foundation/annualreport/2017/
8. the most prominent is probably https://www.mozilla.org/account/ …
9. … and the "Get Monitor" button on https://www.mozilla.org/ homepage 😇 

There are some links to API, oauth, and some through FxA login to dashboard that probably don't/won't have tags etc., some "clicks" are also run in tests so that could also add up.

**Comment by stevejalim** [comment]
@alexgibson Can we arbitrarily choose `campaign` and `content` values for the missing UTMs here, or should we consult with Adria or PMMs? If we can pick our own ones, I can generate a list and maybe @janbrasna could pick up that, as he's already engaged with the ticket

**Comment by alexgibson** [comment]
I think it would be fine if we pick some sensible campaign / content params here

**Comment by janbrasna** [comment]
I'm gonna fix those where the `utm_params` are already set somehow somewhere, but just not added, not having to invent any new tags, and also resurrecting those that once were there but got removed at some point. That would fix 8. & 7. (the most important).

I'm not sure about changing the old annual reports (newer have the tags, not sure how I feel about retrofitting this for 2017–2018 MoFo content), and for the couple of remaining pages I'll see if I can come up with reasonable campaign content values.

I originally didn't want to mess with this and leave it to someone with more systematic approach like a helper function to build the URLs, but seeing the `utm_params` being already constructed in several different ways among the templates and views, I think this could just continue the same way…

**Comment by janbrasna** [comment]
@rhelmer The most prominent product links have the attribution added for about a month now. Do you see any improvement on your side? Feel free to close if that looks sufficient for now — or if there's still a bunch of unidentified traffic I could try adding the tags to even the less prominent locations if that helps.

However I'd personally try not to retrofit the tracking to content that captures some historic state in time, like the annual reports, though.

**Comment by stephaniehobson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/14478
