### ISSUE TITLE
Even out navigation drop down menus

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14458]
## Description

Even out navigation drop down menus which have had items removed.

- [ ] Change the "who we are" menu to 3 rows
- [ ] Swap the positions of the "leadership" and "get involved" links under "who we are"
- [ ] Change the "Innovation" menu to 2 rows

**Comment by stephaniehobson** [comment]
FYI the code already has support for `mzp-l-rows-three` and `mzp-l-rows-two` so it should be an easy class change 🤞

**Comment by janbrasna** [comment]
There will be two prominent menu items removed in #14248, making the grid rather empty in a few spots:

![main](https://github.com/mozilla/bedrock/assets/1784648/0578af3a-7d23-466b-a949-2be0299ad520)

After the privacy pages get reduced, this would enable to align all the dropdowns consistently to 3-row e.g.:

![tbd](https://github.com/mozilla/bedrock/assets/1784648/92ead8b9-90dd-4ed7-b71b-5239469f4742)

Would it be OK to move around some products, like the Focus/Klar and VPN to row:1 col:2 to make better use of the space?

**Comment by stephaniehobson** [comment]
Yes, those are good moves for Focus & VPN. Don't wait for #14248, you can remove those items as part of this PR. 🎉 

I think I'd still prefer the Innovation menu to be 2 rows so there's no "hole" and I like having Dev Edition and MDN alone in a column together. If we had a landing page for the innovation links at the bottom of the menu I'd feel differently but right  now, we don't. Major work on the nav menus is coming in June anyway 🤞

**Comment by janbrasna** [comment]
RIght, there's no landing page for _Innovation_ so the menu would be different size anyway. 👍 Will do. With two rows in Innovation I'm also switching positions of future.m.o & commonvoice.m.o so that with two lines "Mozilla Innovation Projects" is still right top, and "Common Voice" now moves right bottom.

I have some menu updates in other PRs already, but will chop them out and make all the dropdown changes in here to push them in one go. 🚀

**Comment by stephaniehobson** [comment]
@janbrasna Thank you :)
