### ISSUE TITLE
Docs no longer auto building on commits to main branch

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14464]
## Description

The last few times I've updated the bedrock docs, the changes are not reflected in https://bedrock.readthedocs.io/en/latest/index.html.

For example, the changes in https://github.com/mozilla/bedrock/pull/14452 are not present in https://bedrock.readthedocs.io/en/latest/attribution/0003-firefox-mobile.html

**Comment by janbrasna** [comment]
https://readthedocs.org/projects/bedrock/builds/

> Recent Builds:
> Passed version latest (html) 2 weeks, 6 days ago

This was the last commit https://github.com/mozilla/bedrock/commit/fb3a54e2ea5491e6fcd7f2cae82444ac25a981b7 to be picked up by rtfd…

**Comment by stevejalim** [comment]
Yeah, I think that was a manually triggered build, by @robhudson

I'll check the webhook and see if it's obvious what's wrong.

**Comment by stevejalim** [comment]
This one's a bit of a fiddly one.

We can see that it's failing in GH (https://github.com/mozilla/bedrock/settings/hooks/76849843?tab=deliveries) and the response tells us what to do, namely read https://blog.readthedocs.com/security-update-on-incoming-webhooks/

That page tells us to go to the webhook in our RTD account and hit the Resync webhook button. 

However, that fails with "Webhook activation failed. Make sure you have permissions to set it." and comments on this issue (https://github.com/readthedocs/readthedocs.org/issues/4065) suggest that it's because one needs to be the admin of the GH repo (and presumably authed for Github) in order to use that Resync button.

I am an Admin on mozilla/bedrock, but seem to not have the right permissons and wonder if there's a way to see why the request is being denied. I've asked our GH Enterprise admin if there's anything they can see on their side that might be stopping the resync

**Comment by janbrasna** [comment]
Anyways that's a sign it's probably about time to start building the mkdocs #13288 here to gh-pages with actions instead of relying on webhooks (that are unscriptable opaque clickops) — `kitsune` just recently moved from RTD to GHA (incl. publishing a stub to rtfd about new loc and setting up redirects away for posterity) and the workflow is pretty simple, I've actually drafted a mkdocs build straight to deployment env https://github.com/mozilla/kitsune/commit/d6570a340063fbaee41efeb015adf0861e6932b9 so there's no need to keep the pages' content in branches anymore and it only triggers on docs changes etc. I'll try to check how much updating the WIP PR here needs, there has been some .rst content changes since… but the work already done on the mkdocs migration is great and it'd be a shame to let it get too out-of-sync.
