### ISSUE TITLE
MoFo Donate Banners 

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14747]
Hello. Similar to the MoFo banners we made in Dec 2023 (see [this](https://github.com/mozilla/bedrock/issues/13880) issue for reference), there is a request to do something similar again this summer.

**_PART 1 = NA U.S. EXPERIMENT_** 

The experiment will only test 2 variations and will only take place in EN and the U.S. on the mozilla.org homepage.

The design is going to remain the same as last time, the one with the heart in the hand ([figma](https://www.figma.com/design/2TK8tXeDIiLC67TMdbMIcO/Fundraising?node-id=1652-358&t=Y2a7DtC3Qx4HrNlU-0)).

![image](https://github.com/mozilla/bedrock/assets/134577516/14ef9dd6-c8a8-4101-a7d3-9836c8a80332)

The copy for the two versions will be:

1. Version A (same as one we did last time)= 
Title = `Donate to Mozilla. Reclaim the internet.`
Tagline =` It’s time to take the internet back from big tech. Can you donate to Mozilla?`
Link to = https://foundation.mozilla.org/?form=july-banner-a

3. Version B (this one has a new tagline, which is what they are testing) = 
Title = `Mozilla puts people over profits. Will you donate?`
Tagline = `It’s time to reclaim the internet from big tech. Can you donate to Mozilla?'
Link to = https://foundation.mozilla.org/?form=july-banner-b

They would like to split traffic on the site 50/50. 

**_PART 2 = OUTSIDE OF THE U.S._** 

For the rest of the world outside the U.S., they are requesting us to use the same design + copy as one of the banners we did last year in UK, DE, FR. There will be no experiment. 

The banner design + copy they would like to use for this is the same as Version A above:
Title = `Donate to Mozilla. Reclaim the internet.`
Tagline =` It’s time to take the internet back from big tech. Can you donate to Mozilla?`

They would like 100% of global traffic to see the banner. The CTA should link to: https://foundation.mozilla.org/?form=july-banner-om

*TIMELINE*

The test should go live on **July 8th, 2024** and end on **July 15th, 2024.**

**Comment by slightlyoffbeat** [comment]
Should donate links be unique to be able to properly attribute?

**Comment by robingrace5** [comment]
**Yes, we need unique donate links for each variation and for ROW.**

U.S. version A: https://foundation.mozilla.org/?form=july-banner-a
U.S. version B: https://foundation.mozilla.org/?form=july-banner-b
ROW: https://foundation.mozilla.org/?form=july-banner-om

**For version B, we would like to test the title rather than the tagline.** 

Title = Mozilla puts people over profits. Will you donate?
Tagline = It’s time to reclaim the internet from big tech. Can you donate to Mozilla?

**Lastly, the design we'd like to use is the hand with the heart in it, not the hourglasses.** Here it is for reference: 

<img width="610" alt="Screenshot 2024-06-28 at 11 42 50" src="https://github.com/mozilla/bedrock/assets/174104373/8f5eb6e7-1ffa-47c5-b9ba-a6c81c42e258">
