### ISSUE TITLE
MoFo Donate Nav Experiment - July 2024

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14748]
Hello. We will be conducting an experiment on the mozilla.org homepage navigation by adding a `donate` button to it.

Requirements: 
- It will be in EN only.
- The donate button should replace the existing VPN button in the top right corner. 
- The button should be the same as the donate button in the footer, but with a white background, black border, and becomes shaded upon hover.
- The button should link to https://foundation.mozilla.org/en/?form=donate
- The traffic split should be 50% of the entire audience sees the donate button. Then, for the remaining 50% of the audience, it behaves as normal, meaning FX audience sees donate button, Non FX audience sees download Firefox.

This experiment needs to begin once the banner experiment ends ([ref issue](https://github.com/mozilla/bedrock/issues/14747)). Final dates TBD, but need to aim for before code freeze starts on July 26th. I will update this as soon as I know.

**Comment by slightlyoffbeat** [comment]
Some additional context:
- En only, and we can limit to homepage. 
- For the remaining 50% referenced in the final bullet point above, we'd essentially be swapping the VPN CTA that fx users see for a donate CTA.

We should differentiate the link for the two tests so that we can monitor donations for each individually.

What we are looking to learn:
1. impact of adding donate link to nav
2. impact of having donate link for all traffic, vs only FX traffic

**Comment by robingrace5** [comment]
Hi Dan and Emma, 

This all sounds great. Thank you for planning this test for July before the code freeze. 

I'm sharing both links below for the experiment plan outlined above. 

**Entire audience:** 
https://foundation.mozilla.org/?form=cta-donate-nav

**Firefox audience:** 
https://foundation.mozilla.org/?form=cta-donate-nav-fx

Feel free to let me know if there's anything else you need from our end.
