### ISSUE TITLE
Remove experiment from Welcome 15

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14951]
## Description

In #https://github.com/mozilla/bedrock/issues/13303 an experiment was added to Welcome 15. It collected data in UA/GA3 for nearly a year before Google turned UA off.

This experiment is no longer collecting data and should be removed from the site.

**Comment by janbrasna** [comment]
Since it's 50:50 split it's not implied which version would be the default =to stay, but it's [v1](https://www-dev.allizom.org/en-US/firefox/welcome/15/?v=1) that seems to have less special arrangements going on, so that'd be the default to keep I assume.

([v2](https://www-dev.allizom.org/en-US/firefox/welcome/15/?v=2) has a broken image that got moved in the past, so that'd need fixing if it were to stay…)

**Comment by stephaniehobson** [comment]
+1 to keeping the one that isn't broken 😬
