### ISSUE TITLE
WNP 132

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#15295]
Hello. Please refer to [this brief document ](https://docs.google.com/document/d/1pDlsb8uuj4yPXQwSf1kb0a3vpx7sGjg0QX6-iqBZWgg/edit)for additional details. Thank you.

**Comment by slightlyoffbeat** [comment]
[Copy Document (En-US, en-UK, DE, FR](https://docs.google.com/document/d/13zYbS9rDeW3PAwNVAZAV9fYnd4mpelBxAzxH-TX6Z98/edit?usp=sharing)

[Figma Design - en-US](https://docs.google.com/presentation/d/1RNFkTVCzN9dO4QFFedOnRhbhJjGLGbT2KvhOml0-FMM/edit#slide=id.g30da67f0dee_1_0)

Figma Design - UK, DE, FR - coming soon. They will be same design, but without the subheads, and just a single CTA.

Criteria:

- [ ] North America (English) will have headline, video, body, and subheads
- [ ] UK (English), DE and FR will have just headline, video, body, and single CTA instead of subeads

**Comment by slightlyoffbeat** [comment]
Youtube links for German and English. French coming.

EN: https://youtu.be/-Mz8xJW4CNE
DE: https://youtu.be/Fc0fPt_8tLY
