### ISSUE TITLE
Refresh: Update social share og image

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15595]
Image can be exported from [Figma](https://www.figma.com/slides/r0pOJ76CKntt6aRRjRZlEc/Mozilla-Brand-Asset-Rollout?node-id=2-65&t=4wva1mnhilYRevry-1).

**Comment by janbrasna** [comment]
If I could bother @ehot or someone to export the latest version of the social poster og image from the Figma above, I'd update that one as well. (Should be 1200×630px) ~Thanks.

**Comment by stephaniehobson** [comment]
This is what's in the Figma: <img width="591" alt="image 2" src="https://github.com/user-attachments/assets/b929fabc-2cdc-4eb3-a668-642fc15b1097">

Slightly smaller than the recommended size. I don't know why. It'd be easy enough to add black or off black to make up the difference.

**Comment by janbrasna** [comment]
Neither was the last one the right resolution/ratio, it also needed some alignment.

I tried to find the right spacing according to brand guidelines (that is usually something like half the M size, or half the flag dimensions etc.; neither was the case here) but the grid seems to be sized around the flag sometimes, sometimes not:

![mzla-grid](https://github.com/user-attachments/assets/6565d5df-9cf7-4075-8dcf-db9c642680e6)

so I just sorted out the poster size and left it as-is otherwise.

NB: It's flat black, so I kept it that way.
_(If there's ever any further iteration of perhaps off-black with green type or anchored positioning for more fun lockup I'm happy to update it again. I didn't feel like inventing something that might need to gather feedback et al. first when this is already approved.)_
