### ISSUE TITLE
Firefox Relay Logo / Icon is incorrect

### ISSUE THREAD

**Issue by tesseheinricks** [mozilla/bedrock#15632]
## Description

The Firefox Relay Logo is currently black instead of purple

### Steps to reproduce

<img width="1461" alt="Screenshot 2024-12-03 at 11 54 19 AM" src="https://github.com/user-attachments/assets/759137c4-d813-4bad-a438-ed586497456b">

### Expected result

The logo should look like the primary purple logo

### Actual result

The logo uses a black background instead of the purple gradient 

### Environment

Firefox desktop, Macbook Pro, MacOS Sanoma 14.6.1

**Comment by janbrasna** [comment]
This is actually being tracked upstream in https://github.com/mozilla/protocol-assets/issues/87

A quick workaround might be using [`logo-white.svg`](https://github.com/mozilla/protocol-assets/blob/a99bd40321cde692479d03dcc619a215ef3890a0/logos/firefox/relay/logo-white.svg) instead of [`logo.svg`](https://github.com/mozilla/protocol-assets/blob/a99bd40321cde692479d03dcc619a215ef3890a0/logos/firefox/relay/logo.svg) that has been done here before, until the protocol-assets versions are tackled? (I know it's _de iure_ designed to be used on dark backgrounds, but it gets the job done for now…)

**Comment by janbrasna** [comment]
FYI it's both in the _launchpad_ and the _products_ submenu.
