### ISSUE TITLE
Refresh: update localized font stacks

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#15687]
## Description

The new brand fonts don't currently include a number of Latin Extended characters. Some languages that rely on the extended alphabet such as Turkish, Czech, and Vietnamese (among others) will show most characters in the brand font, but unsupported characters will render in the next available fallback font. It's readable, but unattractive and annoying to see one letter in the middle of a word rendered in a very different font.

We should use our l10n CSS capabilities to deliver the brand fonts only to those languages we know it supports, and other languages can use a default font stack. We can use Inter as the primary webfont for those.

**Comment by janbrasna** [comment]
It's unfortunate that for most of languages it's just one or two glyphs missing, that make the new font output look subpar:/

(There are probably more languages affected that are currently below the prod threshold for %% translations activation, but I'll start with current prod languages first, and may come back to adding some of the affected non-prod locales too, to have a full list what to check for if the font gets any l18n updates in th future.)

Non-Latin alphabets are not excluded explicitly, as they fall through the glyph support to pick up what works for them in the font stack — meaning whenever e.g. a brand term in Latin appears, it's rendered in Mozilla font side by side with another e.g. system sans for the rest of the language (Greek, Cyrillic, Middle Eastern and Asian locales), but that's mostly constrained to individual words and doesn't look too disruptive.

Vietnamese is already manually excluded due to the amount of accents used, as usually only a few very broad font families include all of them.

🚧 TKTK: I'm not too familiar with regional western languages as occitán, lengadocian, aragonés, asturian, ligure etc. … but will check some of the Latin2 languages for obvious missing chars. (Polish is fine, Albanian is also covered, but more Slavic as _bs, hsb_ or _dsb_ miss some.) +There's also a Berber locale (_kab_) missing their more complex glyphs.

**Comment by selimsum** [comment]
Looks like we have proper Turkish support now. Is it time to revert these changes?

**Comment by janbrasna** [comment]
I'm tracking that in https://github.com/mozilla/bedrock/issues/16145#issuecomment-3112087988

This is where we're at atm: https://github.com/mozilla/protocol/issues/1086#issuecomment-3183746627
