### ISSUE TITLE
Release notes item order is randomly reshuffled 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/bedrock#5193]
Ref: https://www.mozilla.org/en-US/firefox/56.0/releasenotes/

Reported by the owner of Android Police. They post articles of every release of Firefox for Android. See last 2 messages of this thread: https://twitter.com/ArtemR/status/917491762385494016

What could this be? Is it just us updating the release notes and changing the data on deploy or could this be some tech issue?

**Comment by pmac** [comment]
I'll look into this. Apologies for the delay. Do you know if this started happening recently or is a long-standing thing? Also, perhaps they'd prefer a notes feed? We have one for Nightly, but not for other channels.

**Comment by pmac** [comment]
Looking into it I do see that the default ordering for notes is by modification date. So it would reorder the notes per section by whichever is most recently modified. I can change this to be more consistent, but we'll have to discuss with relman on what is most approrpiate. Perhaps @sylvestre has ideas?

**Comment by pmac** [comment]
Actually it looks like they're [ordered by a "sort_num" value](https://github.com/mozilla/rna/blob/master/rna/models.py#L130), but that value is rarely used, so I think this may result in random ordering. They should only reorder when a release is updated, but they would potentially reorder at that point. I can add a secondary ordering by creation date or the ID (autoincrementing) which would give some order if no manual "sort_num" were entered. Does that sound reasonable?

**Comment by vladikoff** [comment]
Hey @pmac, 

> I can add a secondary ordering by creation date or the ID (autoincrementing) which would give some order if no manual "sort_num" were entered. 

This sounds great!

**Comment by pmac** [comment]
Okay. Just deployed a fix for this to Nucleus. Should propagate in some release reordering soon, and then we'll just see. Closing this for now.

**Comment by archon810** [comment]
Thank you for fixing this. I'll report back if they keep shuffling.

I'd like to see what the feed idea would look like too, for stable and beta. Specifically, how it would update with new items when the notes change.

**Comment by pmac** [comment]
I'm not sure yet. We could discuss it. The [feed for Nightly](https://www.mozilla.org/en-US/firefox/nightly/notes/feed/) is just the notes and is not release based since there isn't really such a thing as a "release" of Nightly. It would probably need to be different for the releases.

There is already kindof a feed for these data since the site pulls in the data using [JSON from nucleus.mozilla.org](https://nucleus.mozilla.org/rna/all-releases.json). That's a giant JSON blob of all release notes from all of the releases in that system. We parse it and update [another git repo with releases](https://github.com/mozilla/release-notes/). So monitoring that repo and pulling in those JSON files is probably the best feed there is likely to be.

I could see perhaps simply offering a JSON view of every release notes page e.g. https://www.mozilla.org/en-US/firefox/56.0.2/releasenotes/ and https://www.mozilla.org/en-US/firefox/56.0.2/releasenotes.json. Would that be helpful?

**Comment by archon810** [comment]
Honestly, I think continuing to monitor the 2 listed pages for changes will work best for us. Otherwise, I'd probably prefer RSS, and we'd monitor each entry for updates. JSON doesn't play nice with our monitor.

**Comment by archon810** [comment]
Hmm, I just got another reshuffle for the beta page https://www.mozilla.org/firefox/android/beta/notes.

The one from Oct 31 was: 
![image](https://user-images.githubusercontent.com/469543/32628544-183abe90-c54b-11e7-8f97-4c350a3c9b12.png)

The one from 4 hours ago:
![image](https://user-images.githubusercontent.com/469543/32628553-2032d29a-c54b-11e7-8ecd-20d31b2b2cca.png)

Is this something we expected?

**Comment by pmac** [comment]
That one looks like an intentional edit from the release management team. I think we're still okay as long as you're not seeing pure reordering changes.
