### ISSUE TITLE
Make it run error

### ISSUE THREAD

**Issue by sweatC** [mozilla/bedrock#5277]
Hi!
I am trying to run bedrock app. And I follow this [instruction](http://bedrock.readthedocs.io/en/latest/install.html). 
So I get this error:
![image](https://user-images.githubusercontent.com/15202961/32745935-e0fab9f6-c8bc-11e7-8e65-ba8c3d0d2fc5.png)

**Comment by georgegillams** [comment]
That'll be because you aren't running within the virtual environment. You need to run `source venv/bin/activate` first to activate the virtual environment. if you are on Linux there are some things you need to install first. if you are on Windows the command is slightly different. 

Long setup instructions like these can be confusing at first, but try to work through them methodically from the beginning each time you get stuck. Everything you need is there!

Good luck 👍 😎

**Comment by flodolo** [comment]
The screenshot shows an active (venv). Did you install the requirements?

**Comment by sweatC** [comment]
@flodolo yes, I have installed all the requirements. 

![image](https://user-images.githubusercontent.com/15202961/32852342-471840f8-ca40-11e7-9b60-e45e80b58df5.png)

**Comment by NdagiStanley** [comment]
@sweatC From your screenshot above, I can tell that the requirements were not fully installed. Issues #5346 and #5325 have kind of a similar issue. I had a pip install error when running pip install -r requirements/base.txt but running `pip install -r requirements/test.txt` works on my Mac.

The docs [here](http://bedrock.readthedocs.io/en/latest/install.html#installation) insist on running `pip install -r requirements/test.txt` which by extension installs the packages in requirements/base.txt. There might be an error on first run of this but a rerun does the trick.

Again ensure the python version in 2.7 and that you are in a virtual environment

**Comment by NdagiStanley** [comment]
@sweatC if this is no longer an issue feel free to close this issue.
