### ISSUE TITLE
Mozilla.org gets a C for it's TLS connection from ssllabs. This is really low.

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/bedrock#5405]
https://www.ssllabs.com/ssltest/analyze.html?d=mozilla.org

![screen shot 2018-01-20 at 02 02 28](https://user-images.githubusercontent.com/922368/35177150-0fca07f2-fd86-11e7-9aa0-244d500086ae.png)

**Comment by pmac** [comment]
We use certificate switching on-demand so that we can continue to support old browsers (IE, Chrome, etc. on Win XP) that do not support SHA2 certs so that they can download Firefox. Modern browsers will use the newer and more secure cert. We'll disable the less secure option when we can, but for now we need to keep supporting these users so that they can get a secure browser if they want to even if they can't use a secure OS for some reason.

Thanks for filing.
