### ISSUE TITLE
Web Bug Bounty FAQ are missing instructions on submitting reports

### ISSUE THREAD

**Issue by palant** [mozilla/bedrock#5502]
I was looking at https://www.mozilla.org/en-US/security/bug-bounty/faq-webapp/, trying to find a way to submit a report. "Once I have found a vulnerability, what next?" links nowhere, this section was removed in the https://github.com/mozilla/bedrock/commit/e4dd27a661a8d8e551074b9e18476bd138184d23 commit by @april. The necessary information exists under https://www.mozilla.org/en-US/security/web-bug-bounty/#how-to-submit-bugs but there is currently no link there. One *could* get there by clicking "What are the bounty payouts?" or "What types of issues will be considered as part of the bounty program?" but quite frankly - that is far from obvious.

**Comment by april** [comment]
Please be nice.  :)

It's in the top level page for the web bug bounty program, the most referenced page in the program. It includes payouts, exclusions, and how to submit.

I've not had anybody say they've had issues with finding this information before, and the vast majority of our bugs come in through the proper web bug bounty form. That said, since you find it confusing, I will try to add some more links in the FAQ so as to improve clarity. I agree that it also makes sense to add to the FAQ.

Thanks!

**Comment by palant** [comment]
Well, at the very least you could remove the dead "Once I have found a vulnerability, what next?" link - with that link there I expected this information to be present on the page and didn't realize that I was on the wrong page.

**Comment by april** [comment]
Yeah, that was a mistake missed by about four editors when we relaunched the bug bounty program a year and a half ago.  :)
