### ISSUE TITLE
Enable data collection in account benefits pages (a & b), resume test

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5782]
Requirement is to put data collection in place (GTM) in both of the account benefits pages to enable reporting.

https://www.mozilla.org/en-US/firefox/accounts/features/?v=a
https://www.mozilla.org/en-US/firefox/accounts/features/?v=b

Original implementation was done in https://bugzilla.mozilla.org/show_bug.cgi?id=1444561

**Comment by peterGerman** [comment]
Please add the following data attributes
data-button-name='create an account'

Please update the utm params in the link to accounts to be :
utm_source=account-features
utm_campaign=may2018
utm_content=v-a | v-b
(I'm not totally sure how these are set, and it might be good to check in with the fxa team before pushing)

**Comment by stephaniehobson** [comment]
@peterGerman 

The specs we got from the FxA team are [in Bug 1457004#c15](https://bugzilla.mozilla.org/show_bug.cgi?id=1457004#c15). You're not asking to change the things they asked us for so I assume it's okay.

The proposed `utm_content` is different from the other formats we've been using is it okay to use this instead:
/firefox/accounts/features/v-a | /firefox/accounts/features/v-b

How many days does this test need to run? (We have another change coming to this button and I am trying to figure out if I should push that change through or leave it until after the test finishes).

**Comment by stephaniehobson** [comment]
I submitted https://github.com/mozilla/bedrock/pull/5790.

The buttons are labeled without the article:
data-button-name='create account'

One small change to utm params but I can change it if it's a problem:
utm_source=account-features
utm_campaign=may2018
utm_content= /firefox/accounts/features/v-a | /firefox/accounts/features/v-b

This is consistent with what is in https://github.com/mozilla/bedrock/pull/5749 so the analytics reporting should stay the same.

However, after #5749 is merged non Firefox users will be prompted to download instead.

It's possible to hold off on merging #5749 until after the A/B test is one but we'd really rather not. If it's possible we'll merge it tomorrow morning so the new analtyics parameters go live with it instead of #5749.

**Comment by stephaniehobson** [comment]
The experiment is still running in production so there's no need to switch it back on.

**Comment by stephaniehobson** [comment]
Closed by #5749. Should push tomorrow.

**Comment by peterGerman** [comment]
Thanks stephanie, the above LGTM. Please ping when it is live.

**Comment by stephaniehobson** [comment]
@peterGerman Did I remember to ping you when this went live?
