### ISSUE TITLE
URLs available to resolve with and without and trailing slash

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5783]
https://www.mozilla.org/en-US/firefox/accounts/features 
and 
https://www.mozilla.org/en-US/firefox/accounts/features/

https://www.mozilla.org/en-US/firefox/ios/testflight
and
you get it . . .

**Comment by ejregithub** [comment]
@rraue - please take a look and provide any required actions.

**Comment by kyoshino** [comment]
This is because some `url()` routes don't have a trailing slash.

* [`^firefox/accounts/features`](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/urls.py#L33) has to be `^firefox/accounts/features/$`
* [`^firefox/ios/testflight`](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/urls.py#L67) has to be `^firefox/ios/testflight/$`

I just tested them locally. There might be more.

**Comment by rraue** [comment]
We should fix this, as it seems these setting is the same for the canonical as well and we are producing dublicate content here. If this will affect a lot or important pages, we might get in trouble. 

All urls should end with a trailing slash, and the parameter pages point with the canonical to the version without parameter. The pages without trailing slash redirect 301 to the one with trailing slash. Thats our normal setup.

We should as well add this to our automated testing.

**Comment by kyoshino** [comment]
My quick search finds 6 `url`s missing a trailing slash and/or `$`:
https://github.com/kyoshino/bedrock/compare/5783-urls-trailing-slash

**Comment by rraue** [comment]
My crawl didnt show any otehr url then the ones @kyoshino already mentioned. I am just not sure about the last one in your list, but I am no dev thought.

We should fix this @ejregithub and think about how to prevent this in the future by testing on this.

**Comment by kyoshino** [comment]
This 😅  https://www.mozilla.org/en-US/security/advisories/cve-feed.jsonorsomethingelse
