### ISSUE TITLE
Changes to static-bundles.json not recognized when running locally via Docker

### ISSUE THREAD

**Issue by jpetto** [mozilla/bedrock#5840]
The new CSS/JS bundles created for `/whatsnew/` for Fx61 are 404'ing when running locally via Docker, but work fine when running via `npm start`.

STR: Running locally via Docker, create a new JS bundle (containing any `.js` file) and include it on any page. You'll see a 404 in the terminal window when loading that page. Running the site via `npm start` loads the new bundle correctly.

After a quick look, my guess is that this is due to `static-bundles.json` being a [part of the Docker image itself](https://github.com/mozilla/bedrock/blob/master/Dockerfile#L17-L18), and not being watched for changes. Having to re-build the Docker image each time a bundle is added is (IMO) too clunky.

**Comment by pmac** [comment]
Agreed. I believe I simply overlooked that this file is in the root of the project, and to save on some performance and because I don't want to include `node_modules` in the volume I don't include the whole project directory as a volume in the running local container. You can see the defined volumes in the docker-compose.yml file:

https://github.com/mozilla/bedrock/blob/d3cff63cf9082778646ad5716d9402e6601e651e/docker-compose.yml#L16-L18

So I believe we'd just need to move that file to a subfolder and include said folder in that configuration, or include it in the `bedrock` folder. It could go in `bedrock/settings` where the last definition was, but that doesn't make that much sense considering what is using it. Something to think about since the only real user of that file is gulpfile.js.

**Comment by pmac** [comment]
Maybe just putting it in `./media/` makes the most sense?

**Comment by jpetto** [comment]
👍 on putting it in `./media/`.
