### ISSUE TITLE
Create URLs for Legal

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5915]
Set up the following URLs 

https://www.mozilla.org/privacy/firefox-reality

https://www.mozilla.org/about/legal/terms/firefox-reality/

**Comment by stephaniehobson** [comment]
We need content to set up URLs. Do we have content? Are they going to add something to the legal repo? I couldn't find anything there about Firefox Reality.

**Comment by stephaniehobson** [comment]
Sounds like the plan is to have something in the legal repo in the near future. I'll talk to @pmac about the feasibility of doing any preparatory work on our side.

**Comment by stephaniehobson** [comment]
Okay, I talked to @pmac about this and I understand the system better now.

We need to have a folder in the legal-docs repo before we can create the URL. 

Adding the URL is a one line file edit and can be done very quickly. Since the new docs require us to do a sub-module update there isn't any time savings to be had by trying to do any work before hand.

The best thing to do is to add the URL when the content exists and is pulled into bedrock the first time.

**Comment by alexgibson** [comment]
Both of these pages exist, closing.
