### ISSUE TITLE
/download/thanks page mail CTA content - a/b test 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5943]
## Important Links

[Manapage with Test Write Up](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=81691444)

[Deck with User Flow](https://docs.google.com/presentation/d/1Sq9DCPt5-clMx2rCQ079cM5D7ybkgNLXqMpF_Bb8N5g/edit?usp=sharing)

[Content and Copy](https://docs.google.com/document/d/1ijjDcATdeBGWrBdyTWmJ-4la4RIb4Tyepn3VHv7Dy1s/edit#)

[Sketch File](https://share.goabstract.com/efef0859-ed93-41ef-bbad-dfc90a4ce3ae)

### Prototypes
[Post-Download](https://invis.io/Q8NACUBYM9U)

## Success Criteria

- [ ] 'Expedite' delivery (this is from the Tiger Team)
- [ ] Implemented to 100% of en-US (across all content variations being tested)
- [ ] a/b test in place allocating 50/50 split (of the entire audience) to test content (headlines) in the email CTA

**Comment by thejeffreytaylor** [comment]
ETA for copy treatments Thursday SF lunchtime.

**Comment by dzingeek** [comment]
Working on the flow now. Just posted it to the team for feedback before next steps.

**Comment by dzingeek** [comment]
**Link to deck w/user flow and rough wireframes.** 
https://docs.google.com/presentation/d/1Sq9DCPt5-clMx2rCQ079cM5D7ybkgNLXqMpF_Bb8N5g/edit?usp=sharing

**Comment by thejeffreytaylor** [comment]
Copy here: https://docs.google.com/document/d/1ijjDcATdeBGWrBdyTWmJ-4la4RIb4Tyepn3VHv7Dy1s/edit#

**Comment by michaelmccombie** [comment]
Here is a link to the InVision prototype for the pre-download workflow test:
https://invis.io/SDNAAE3ZCK4

**Comment by craigcook** [comment]
@ejregithub  The title on this issue says it's an a/b test but the success criteria say it's 100% of en-US... we can run it as a test (meaning I'll put it behind a switch so we can turn it off) but if it's a/b are we testing it 50/50 against the regular thanks page? That may not be a meaningful test because the page with the form will obviously get more signups than the page without the form (which is zero).

Success criteria also says "across all content variations being tested"... can you clarify what that means? Right now we have a slew of download page variants; Portland, Berlin, Reggie Watts, Waitface, Better Browser... are we adding the form to ALL of those variant thank you pages? Because we've only discussed and designed one (the default).

**Comment by craigcook** [comment]
Alright, I got the clarity I needed. Recording for posterity...

100% of English visitors will see an email subscribe prompt on the thanks page. 

Of that English audience, we're doing an a/b test of two different headlines with a 50/50 split:

A: "Learn how to make Firefox even smarter, faster and more secure."
B: "Learn how to make the most of the browser made for people, not profit."

**Comment by ejregithub** [comment]
@craigcook - please ping @alexgibson in the PR requesting review when ready

**Comment by craigcook** [comment]
This is live in production: https://www.mozilla.org/en-US/firefox/download/thanks/
