### ISSUE TITLE
(Due 8/28) WNP 62 - Sept 5th

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5946]
[Master project doc](https://docs.google.com/document/d/1wEpa-pEyQOIKwXSRligj6cUPbXQ-qN8wmP4LIe9q7ks/edit#heading=h.44tk8jl1sj1b)

Success Criteria

- [x] EN (all en locales) to be shown content for Pocket
- [x] Page is live on production August 29th to accommodate external QA

**Comment by thejeffreytaylor** [comment]
Copy deck here: https://docs.google.com/document/d/1uf8y5PqUHWghuI_wUmdmQVNEU28XvO9uOhuQmvPtqc0/edit?usp=sharing

**Comment by michaelmccombie** [comment]
Here is a link to the design files
https://share.goabstract.com/48f0d841-d03a-4546-a164-e90c1ea58e5d

**Comment by dzingeek** [comment]
I will package up the assets up today.

**Comment by thejeffreytaylor** [comment]
Copy decks for both versions will be up to spec by EOD today.

**Comment by mrkwvr** [comment]
Design file and assets available here https://mozilla.box.com/s/0v0sgnllpiq9662kgtyf1mudm8g0vjgz

**Comment by dzingeek** [comment]
Designs have been updated. We are going out with version A and if there is time we will test Version B.
https://share.goabstract.com/aef26895-1f7b-485f-a6db-f18efb2c6a44

**Comment by dzingeek** [comment]
**Note:** The design and copy was approved by Janis & Devyani in the slack channel 08.21.18 around  10:35am

**Comment by thejeffreytaylor** [comment]
Copy Decks: 

[Version A (to be deployed) ](https://docs.google.com/document/d/1y8mjxwaZ5tCuwoBP3KKpODCsEKOg0DAg1UsWzZFu3dY/edit)

[Version B](https://docs.google.com/document/d/1uf8y5PqUHWghuI_wUmdmQVNEU28XvO9uOhuQmvPtqc0/edit?usp=sharing) (for testing, if bandwidth allows)

**Comment by dzingeek** [comment]
**One small tweak to the design:**
Adding Fx logo in header area since the copy no longer references Fx. Sketch file is up to date. 

See png for reference. 
![screen shot 2018-08-23 at 9 40 22 am](https://user-images.githubusercontent.com/3740746/44539518-3699a680-a6b9-11e8-941e-e5cc6af1d736.png)

**Comment by dzingeek** [comment]
**Note:** The design is still in flux, there has been some back and forth in the slack channel. I think we can still move forward with dev but keep in mind there might be some updated images and small copy tweaks.

**Comment by dzingeek** [comment]
New url for Get Pocket CTA buttons: https://getpocket.com/firefox_whatsnew  

_Will updated copy doc with all link urls_

**Comment by thejeffreytaylor** [comment]
@dzingeek Is this done? Should I QA the copy again?

**Comment by dzingeek** [comment]
@thejeffreytaylor I don't think you need to do anything but if you want to double check the copy docs feel free.

**Comment by craigcook** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/62.0/whatsnew/

And screenshots of the different states, since they're pretty hard to get to...

If user is not signed in and is reading English, show Pocket
![01-pocket](https://user-images.githubusercontent.com/205591/44810361-60a20b80-ab86-11e8-922a-5f19778d5ee7.png)

If user is not signed in and is reading not-English, show Firefox Account signup
![02-fxaccount-es](https://user-images.githubusercontent.com/205591/44810379-6a2b7380-ab86-11e8-9d07-f33795843a1a.png)

If user is signed in but has no mobile devices synced, show Firefox mobile

If sendto widget is supported, show the sendto widget
![03-fxmobile-widget](https://user-images.githubusercontent.com/205591/44810419-83342480-ab86-11e8-8a3f-bb694ff430e7.png)

Else show QR code
![04-fxmobile-qr-fi](https://user-images.githubusercontent.com/205591/44810453-9515c780-ab86-11e8-9711-8fc5a5e0444f.png)

 If user is signed in and has a mobile device synced, show Firefox Focus
 If sendto widget is supported, show the sendto widget
![05-fxfocus-widget](https://user-images.githubusercontent.com/205591/44810476-a232b680-ab86-11e8-82d3-05b059780332.png)

Else show QR code
![06-fxfocus-qr](https://user-images.githubusercontent.com/205591/44810489-af4fa580-ab86-11e8-9ff5-bb7454231323.png)

If user is signed in and has a mobile device synced and is in Germany, Austria, or Switzerland, show Firefox Klar
If sendto widget is supported, show the sendto widget
![07-fxklar-widget](https://user-images.githubusercontent.com/205591/44810505-bd052b00-ab86-11e8-94b7-1cd9ea8a1492.png)

Else show QR code... which is especially tricky to achieve since you'd need to be signed in, with a synced device, in one of the Klar countries *and* reading a non-widget language. I'd be interested in seeing how many people even get this view...
![08-fxklar-qr](https://user-images.githubusercontent.com/205591/44810773-a6130880-ab87-11e8-92f5-4eea5321bf9c.png)

**Comment by stephaniehobson** [comment]
I don't think I'm saying anything our team doesn't already know... "Launch Now" and "If You’re Using Firefox, You Already Have Pocket." are deceiving and confusing. I think they will hurt the effectiveness of this page.

**Comment by dzingeek** [comment]
Yes, @stephaniehobson. These things have been raised to the other team w/suggestion for alternate CTAs...they wanted to keep the "Launch Now" and "If You're Using..." text.
