### ISSUE TITLE
301 redirect needs to be removed for /firefox/pocket/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5970]
we have a 301 redirect in place pointing visitors hitting www.mozilla.org/firefox/pocket to getpocket.com.  In a PR merged earlier today we attempted to remove that, but it has not been successful - https://github.com/mozilla/bedrock/pull/5962/files

**Comment by jgmize** [comment]
I believe the PR did what it was supposed to do, but the 301 redirects are cached at the CDN. If you visit one of the CDN origins such as https://bedrock-prod.gcp.moz.works/firefox/pocket/ or https://bedrock-prod.oregon-b.moz.works/firefox/pocket/ you get the page instead of the redirect. Simply waiting for the cache to expire should be sufficient.

**Comment by jgmize** [comment]
```
$ curl -Is https://www.mozilla.org/en-US/firefox/pocket/ | grep cache-control
cache-control: max-age=43200
```

The CDN will cache it for up to 12 hours; if needed I can log into the CDN admin and flush it sooner.

**Comment by alexgibson** [comment]
I believe this is all resolved, closing thanks @jgmize
