### ISSUE TITLE
Pocket feed homepage errors

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6036]
At around 8.50am GMT this morning we got alerts for the www.mozilla.org homepage being unavailable, which we could also verify manually (seeing a `400 Bad Request` message).

Around that same time, we also got alerts in both Sentry and New Relic that pointed toward a possible issue with the Pocket feed:

- https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/4564525/
- https://rpm.newrelic.com/accounts/1299394/applications/27945751/filterable_errors#/show/b8ea2c76-a1f0-11e8-ad2c-0242ac110009_0_3942/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart

Since this is the only dynamic part of the homepage, we [disabled the swtich](https://github.com/mozmeao/www-config/pull/129) and the home page returned to normality.

We then tried to figure out exactly what went wrong. So far, this our initial guess:

1. For some reason the api request for a Pocket article [failed to return an image](https://github.com/mozilla/bedrock/blob/5f6b4499fe2b90ef89ee8545a265361da48a9e76/bedrock/pocketfeed/api.py#L49-L55).
2. Even though the pocket item didn't have an image, the reference to it was passed into the [card macro](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/home/home-en.html#L228) on the home page.
3. This was then passed to the [lazy_img helper](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/home/home-en.html#L56).
4. The `lazy_img` helper tried to check to see if it was an [external image](https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templatetags/misc.py#L235) (looking for `https://`), but failed, so it tried to load it as though it we're a file resulting in an error.

Assuming the above is correct (I'm not too familiar with the pocket code), we could try some things to make this more fault tolerant.

1. If the pocket api request fails to return an image, assign a stock fallback image to be shown instead.
2. Make the `lazy_img` helper more fault tolerant. We only match on `https://` for external images, so if the feed ever contained a reference that didn't start with `https://`  then that macro would try to access it as though it were a file, resulting in an error.

**Comment by jgmize** [comment]
We could also add error handling to https://github.com/mozilla/bedrock/blob/master/bedrock/base/templatetags/helpers.py#L117 which is what the lazy_img helper was calling when the external_img was false due to the regex not matching.

**Comment by pmac** [comment]
Here's what I think happened, and what I was able to reproduce locally:

1. An error fetching an article URL from the CDN caused a pocket article to get a `null` for `image_src`.
2. When the template called `article.image` it called `article.fallback_image()` which returned the result of `staticfiles_storage.url('img/pocket/pocket-feed-default.png')`. Due to settings in prod this URL was something like `/media/img/pocket/pocket-feed-default.agagagagag.png`.
3. When the above URL was passed into the `lazy_img` helper it saw that it was not an external image, and instead assumed it was a local image path, which for that function would need to be `pocket/pocket-feed-default.png` since the `img/` bit is assumed. 
4. Since the URL started with `/media` the second call to `staticfiles_storage.url()` resulted in a `SuspiciousFileOperation` exception since it appeared to the staticfiles system that this was an attempt to access the root filesystem of the server.

So what needs to change is that we should document that we assume that these images will always use the `lazy_img` helper, and have `fallback_image` return the string `pocket/pocket-feed-default.png`.

**Comment by pmac** [comment]
Working on a PR now.
