### ISSUE TITLE
[9/24] Optimize Sync page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6126]
[manapage for test](https://mana.mozilla.org/wiki/display/FIREFOX/Optimize+Sync+Page)

**Comment by stephaniehobson** [comment]
The accounts product manager says that the animation on the old page boosted conversions significantly: https://web.archive.org/web/20161225055441/https://www.mozilla.org/en-US/firefox/sync/

**Comment by alexgibson** [comment]
Could an additional improvement also be to fix the declining source of traffic to this page, as @hoosteeno pointed out in Slack?

![screen shot 2018-09-05 at 11 19 05 am](https://user-images.githubusercontent.com/400117/45160221-d5a5be80-b1e0-11e8-8bad-0ca95e2deac2.png)

**Comment by hoosteeno** [comment]
This is not as large an opportunity as it once was.

* The sync page has lost 65% of its weekly traffic in 2018. It's gone from 200k/week to 35k/week (as the chart in https://github.com/mozilla/bedrock/issues/6126#issuecomment-419092736 depicts). This means we aren't looking at as big a pool of potential conversions.
* Its present conversion rate is slightly higher than other FxA acquisition channels on www.mozilla.org (e.g. the send-tabs page and the fxa-benefits page, which has been through recent rounds of optimization). This means we are unlikely to achieve a dramatic improvement to conversion rates.

I started [an experiment plan for this ](https://mana.mozilla.org/wiki/display/FIREFOX/Optimize+Sync+Page) but have paused that due to the above. The plan, however, includes links to details about the above.

**Comment by ejregithub** [comment]
@stephaniehobson @hoosteeno 

We tested imagery, results are [here](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=72783034)

**Comment by alexgibson** [comment]
This page no longer exists, closing.
