### ISSUE TITLE
[10/4] FFYR - Update homepage content cards

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6154]
This work supports the Fight for Your Rights campaign
 
Success Criteria:
- [ ] new cards live on 10/4 (content delivered from FMB)

Schedule:
Content from Editorial (MJ) by Sept. 25
Demo on Friday the 28th for stakeholder QA
Code review Mon, Oct. 1
Content live on the Oct. 4th (time TBD)

Tasks:
- [ ] Team QA - Design
- [ ] Stakeholder QA - Design - TBD

**Comment by djst** [comment]
Blocked on input from MJ on specific cards to update.

**Comment by djst** [comment]
@ejregithub is this still blocked?

**Comment by alexgibson** [comment]
Content: https://docs.google.com/spreadsheets/d/1aJO3K_W6FMjup3bucpAQs2xvymvxK-DYK6LLMesLwEQ/edit#gid=0

AirTable link: https://airtable.com/shrVQdWrXYQus2NqT

**Comment by alexgibson** [comment]
@ejregithub can you please make the due date clear on this issue? 9/25 is the date the content was delivered for, but I believe this is due to go live 10/4 (according to Slack?)

**Comment by alexgibson** [comment]
This issue also depends on https://github.com/mozilla/bedrock/issues/6186, since there's a card that link to the election bundle.

**Comment by kellymj** [comment]
Card 1 (Election edition):
- Do you mean to link that to a bedrock demo page?

Card 2 (Misinfonation video):
- The URL was submitted incorrectly with a dash instead of a slash between day and month. The correct URL is: 
http://blog.mozilla.org/internetcitizen/2018/10/04/misinfo-nation-misinformation-democracy-internet

Card 5 (Pocket election section):
- Add a period to the end of the blurb.
- The image is not rendering smooth at the smaller size. Can you adjust or do I need to resubmit a scaled down version?

Card 7 (Nothing is as simple): 
- Missing graphic can be found here[https://dl.airtable.com/2aBk55hlR0y4peu7nmOb_full_Misinfo_header.png](url)
- Please update the URL for card 7 to http://blog.mozilla.org/internetcitizen/2018/10/03/ifcn-article/

Card 8 (Dipayan Ghosh):
-URL contains an extra "h" at the beginning

Card 9 (Genevieve Valentine):
- If the blurb will get truncated, let's shorten to: _We invited science fiction and fantasy author Genevieve Valentine to describe elections in the future._
- The correct URL is: 
http://blog.mozilla.org/internetcitizen/2018/10/04/election-genevieve-valentine/

Card 11 (Firefox Reality):
- Let's try a square graphic here instead for more visual diversity: https://dl.airtable.com/FZGV19ET06hQ06KqOiZO_full_firefox-reality_square.png

Card 12 (Developers guide):
- The correct URL is:
https://blog.mozvr.com/firefox-reality-developers-guide/

Card 14 (Common Voice):
- The image is cropped. Can you allow it to flow down so that the full robot appears?

Given the square graphic moving into Card 11, let's switch the positions of cards 14 and 15 so that they are balanced better across these two rows.

Card 17 (Privacy philosophy):
Blurb was missing a word. Copy should read: At Firefox our privacy philosophy guides how we put people first when we make products, manage data and advocate for policies.

**Comment by kellymj** [comment]
Hmmm, the image for Card 5 won't resize smoothly for me either. Let's leave it. 

The rest looks great.

**Comment by kellymj** [comment]
Late breaking image update for Card 1: https://dl.airtable.com/A6EsDW9wSgGHzQrfSWKE_full_homepage-election-edition.jpg

**Comment by kellymj** [comment]
@alexgibson  

Three edits:
1. Card 1, replace graphic. This version drops the tagline: https://dl.airtable.com/A6EsDW9wSgGHzQrfSWKE_full_homepage-election-edition.jpg

2. Card 1, replace the Title: *Get the Firefox Election Bundle*
"Bundle" is the key word to replace "Edition". Hopefully you know this for the product page as well.

3. Card 4, replace Pocket's election selection image with this one: https://dl.airtable.com/CcE9OokfQoisKRcu0vVz_full_pocket-election-selection-home.png

Thanks

**Comment by alexgibson** [comment]
Updated, thanks

**Comment by kellymj** [comment]
@alexgibson I just noticed the link for card is incorrect. It should be:
http://blog.mozilla.org/internetcitizen/2018/10/04/microtargeting-dipayan-ghosh/
