### ISSUE TITLE
[FFYR #5] Update Firefox Download page

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6199]
FFYR priority #5: https://docs.google.com/presentation/d/1GVQ94lVChlPnbTYgG56wJ-UblkraIfMHJxqYD9KvSOQ/edit#slide=id.g3f2e52f863_0_48

Part of this work is to rewrite page in Protocol, plus introduce FFYR positioning.

**Comment by ejregithub** [comment]
We should also include the addition of a lang selector, as proposed in this bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1440488

**Comment by flodolo** [comment]
Hi, is there any update on the timeline for this? I was wondering if bug 1440488 could be split out, since it looks like a small, self-contained change. See also [this document](https://docs.google.com/document/d/1ljj5_TFWW6M7koQQ_ue3Epuoi_1vZOV607c03aqSkpw/edit#heading=h.3victmqgqfxv) for background.

**Comment by alexgibson** [comment]
This is work for the FFYR campaign that as far as I know, never happened. I'm going to close this issue but feel free to reopen if I'm mistaken.

**Comment by flodolo** [comment]
> I was wondering if bug 1440488 could be split out, since it looks like a small, self-contained change. See also [this document](https://docs.google.com/document/d/1ljj5_TFWW6M7koQQ_ue3Epuoi_1vZOV607c03aqSkpw/edit#heading=h.3victmqgqfxv) for background.

At this point, even more so.

**Comment by alexgibson** [comment]
@flodolo that sounds like https://github.com/mozilla/bedrock/issues/6102
