### ISSUE TITLE
Login Page (accounts.firefox.com) - Account Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6336]
| Estimates |  |
| ------------- | ------------- | 
| TL |1 |
| PM | 0|
| ENG |6 |
| SEO | 1|
| ANA | 1|
| DES | 4|
| COPY | 16|

There are two pages to login to an account: accounts.firefox.com and firefox.com/accounts. 
One is indexed by google, and the other is not.
The question is for RR: is it valuable to have both, or should we kill /accounts.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Ask RR is this valuable (can we just use accounts.firefox.com)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:

Tasks
- [x] Research and provide recommendations - @rraue

**Comment by rraue** [comment]
When I open firefox.com/accounts I get redirected to WMO/new and I can't find the page indexed as well. So no harm if it redirects to accounts.firefox.com.

accounts.firefox.com should be indexed and have a canonical to the accounts page on wmo (defined in this project process) as it has a lot of good internal and external links, they could help the marketing page (sync, accounts or accounts benefits) on wmo ranking better.

Not sure if that's in scope or even possible.

**Comment by ejregithub** [comment]
> accounts.firefox.com should be indexed and have a canonical to the accounts page on wmo (defined in this project process) as it has a lot of good internal and external links, they could help the marketing page (sync, accounts or accounts benefits) on wmo ranking better.
> 
> Not sure if that's in scope or even possible.

@rraue - can you please discuss this proposal with the Fx Accounts folks (probably starting the conversation w. Alex Davis?)

**Comment by alexgibson** [comment]
Just a note that I think firefox.com/accounts may be a typo. I think it should have been https://www.mozilla.org/firefox/accounts/ (unless I'm missing out on some other piece of the puzzle)

**Comment by rraue** [comment]
Who can be sure about this? @dzingeek? That would be a different question. WMO/accounts has quite a bit of traffic and is basically the landing page for all searches around Firefox accounts. We will need at least one landingpage but not 3+1 not indexed.

In general one landing page about firefox accounts must be on www, explaining accounts, but where the magic happens is not important for crawlers, as they do not sign up for anything.

So in order to answer the question, I need to know:

- [ ] What should be the main landing page for accounts from search, nav and referrals (external and internal)?

- [ ] Will we keep /firefox/accounts, /firefox/accounts/features/ and /firefox/features/sync/ or will they be merged into one page?

**Comment by dzingeek** [comment]
@rraue and I chatted about this today and it sounds like the goal is to move /accounts/features/ to /accounts/ (this will become the location of the benefits pg) and route the traffic from /features/sync/ to /accounts/. 

keeping accounts.firefox.com as is but getting it index since we don't own that. 

does that sound right @rraue ?
