### ISSUE TITLE
[Research] Win 10 in S mode - detection on mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6367]
Description: Currently mozilla.org is unable to detect visitors to the site that are using Windows 10 in S mode to do so. This project

Problem statement: Users of Win 10 in S mode are unable to install Firefox, being limited to installs only via the Microsoft app store. This limits a large potential set of Firefox users.

Success Criteria:
- [ ] mozilla.org is able to reliably detect visitors to the site on Win 10 in S mode

**Comment by alexgibson** [comment]
UA string from a Levono laptop I obtained running Windows 10 S

`navigator.userAgent`

```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
```

`navigator.platform`

```
"Win32"
```

**Comment by alexgibson** [comment]
Firefox install flow:

Searched for "Download Firefox"

![firefox search result](https://user-images.githubusercontent.com/400117/50588322-6df33d80-0e79-11e9-9bb8-5f70e08f0760.png)

After ignoring all the Edge messaging in the search results, I clicked the moz.org link and downloaded as normal. Once the download had completed, I double clicked the installer .exe, which was then blocked by this message:

![install blocked](https://user-images.githubusercontent.com/400117/50588398-ba3e7d80-0e79-11e9-9136-b2235e3d4670.png)
 
Because I wanted to install Firefox, I clicked the "See how" link, which then opened this screen:

![click see how link](https://user-images.githubusercontent.com/400117/50588518-62ecdd00-0e7a-11e9-9a85-b1eeab1b4934.png)

This screen told me **absolutely nothing** about what I wanted to know. In frustration, I tried double clicking the Firefox installer again. This time, I got a different message:

![install blocked 2](https://user-images.githubusercontent.com/400117/50588554-90398b00-0e7a-11e9-89c0-f58e9416ee15.png)

This time, clicking the "See how" link took me to somewhere more useful:

![click see how link 2](https://user-images.githubusercontent.com/400117/50588628-df7fbb80-0e7a-11e9-8aca-f287b4ff819a.png)

**Comment by alexgibson** [comment]
Install flow for Chrome:

Searched for "Download Chrome"

![chrome search result](https://user-images.githubusercontent.com/400117/50588689-1ce44900-0e7b-11e9-81c3-8a25345ff6c9.png)

Again, some pretty agressive messaging for Edge. I ignored it, and went to download Chrome:

![download chrome](https://user-images.githubusercontent.com/400117/50588732-47360680-0e7b-11e9-8937-7a8ddcb17391.png)

Google does not detect Windows 10 S in any way, much like mozorg. There is no specific messaging shown to Edge users:

![download chrome 2](https://user-images.githubusercontent.com/400117/50588750-692f8900-0e7b-11e9-8374-59cc01e2bf10.png)

Double clicking the Chrome .exe installer results in the same message shown to Firefox:

![chrome install blocked](https://user-images.githubusercontent.com/400117/50588771-8401fd80-0e7b-11e9-80d3-5d5fba08f1e2.png)

**Comment by alexgibson** [comment]
UA string from Window 10 Pro laptop:

`navigator.userAgent`:

```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240"
```

`navigator.platform`:

```
"Win32"
```

**Comment by alexgibson** [comment]
Comparison between user agent strings:

Window 10 Pro:

```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240"
```

Windows 10 S:

```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
```

Conclusion: there is no identifiable difference, so using UA sniffing to identify Windows 10 in S mode is not going to be possible.

**Comment by alexgibson** [comment]
I've spent some time looking through other properites exposed to JS from `navigator` in Edge, and I don't see anything that identifies S mode.

**Comment by alexgibson** [comment]
@ejregithub initial research is complete, please see above for details.

**Comment by alexgibson** [comment]
The Firefox product team have reached out to Micorosoft directly on this. There is a proprietary API in Edge that may give us the information we need:

https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/mt795399%28v%3dvs.85%29

"I believe you are looking for 178 or 179 in the “unlocked” value."

I'm going to try and test this out on a device and report back. It's currently not clear if this API will still work when Edge moves to Chromium.

**Comment by alexgibson** [comment]
I've tested the above out on a laptop running Windows 10 Pro in S mode, in Edge 17 and I see the following:

```
console.log(window.external.getHostEnvironmentValue('os-mode'));
  {"os-mode":"2"}
```

On a regular Windows 10 VM I see the following:

```
console.log(window.external.getHostEnvironmentValue('os-mode');
  {"os-mode":"0"}
```

The results are definitely different, but they are also not the expected values cited in the email. It's also still unclear if this API will be present when Edge switches to Chromium.

Also worth noting: I had to upgrade my laptop to the latest version of Windows 10 and Edge in order to get this API to work. It wasn't present in the version of Edge that shipped with my laptop.

**Comment by alexgibson** [comment]
Test page: https://www-demo2.allizom.org/en-US/edge-test-page/

**Comment by ericlaw1979** [comment]
The value returned is from https://docs.microsoft.com/en-us/windows/desktop/devnotes/wldp-windows-lockdown-mode

`
typedef enum _WLDP_WINDOWS_LOCKDOWN_MODE { 
  WLDP_WINDOWS_LOCKDOWN_MODE_UNLOCKED  = 0,
  WLDP_WINDOWS_LOCKDOWN_MODE_TRIAL     = 1,
  WLDP_WINDOWS_LOCKDOWN_MODE_LOCKED    = 2,
  WLDP_WINDOWS_LOCKDOWN_MODE_MAX       = 3
} WLDP_WINDOWS_LOCKDOWN_MODE, *PWLDP_WINDOWS_LOCKDOWN_MODE;
`

At present, `getHostEnvironmentValue()` is not in the Chromium-based version of Edge.

**Comment by alexgibson** [comment]
@ejregithub can you please get this in the backlog so we can prioritize this work? Thanks

**Comment by ejregithub** [comment]
Closing this issue. I will create a new one for the work itself (bedrock detecting Win 10 S mode visitors to www.mozilla.org) and reference this issue in that.
