### ISSUE TITLE
LiveNation campaign landing page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6444]
| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: webpage on mozilla.org supporting the LiveNation campaign promoting FxAccounts

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Live on 11/30
- [x] Includes FxA form for users to receive notifications about event *and* access to it.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Content to enable copywriting

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/48519808-25c58080-e823-11e8-82fe-953e312e05ae.png)

**Comment by craigcook** [comment]
Note: I initially kept this open since I was expecting ongoing updates to the page and wanted to keep it all in one place, but as it turned out the page hasn't needed any changes for a while and we're still not sure if/when the next concert will happen. So closing this now is good cleanup and we'll do any further concert updates as new issues. 👍
