### ISSUE TITLE
Issues running smoke tests whilst pushing to run-integration-tests branch

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7028]
## Description

I'm trying to push the latest bedrock `master` branch to `run-integration-tests`.

### Steps to reproduce

```
git push upstream master:run-integration-tests
```

### Expected result

The test run should be green, like the [last commit to master](https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1592/pipeline).

### Actual result

The `smoke` tests for the /firefox/mobile/ page [all fail](https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/289/tests).

Running the tests locally, they all pass. I also deployed to demo and ran the tests locally against that, and they also still pass.

The last person to [push a job to the testing branch ](https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/287/pipeline/)was making changes on the /firefox/mobile/ page. Is there a chance that there's some issue with the workspace, or there's still different code deployed? I'm, at a loss as to what's going on, as the tests passed fine on the last commit to master.

To make sure I'm not going crazy, I tried [rerunning the last master job](https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1594/pipeline/), but now I get a different error:

```
Error response from daemon: Conflict. The container name "/bedrock-code-master-01acfb05c98bfe64fd433b6b743fd5ea97a565ee" is already in use by container "cffc0b09ffcd5e338a5124ac6c9c0a6e33ce9dc15f8d65f0d22e897b042645ab". You have to remove (or rename) that container to be able to reuse that name.
```

And now I'm even more confused :/

**Comment by alexgibson** [comment]
@jgmize any ideas what might be happening here?

**Comment by alexgibson** [comment]
I'd also like to bring this up as an opportunity to discuss how much value these smoke tests are adding. They all get run agains each deployment anyway, and are super difficult to debug because they are inside a remote docker container?

**Comment by alexgibson** [comment]
Ok, the latest commit to master was fine: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/1595/pipeline/39/

I'm going to try pushing this to `run-integration-tests` and see what happens.

**Comment by alexgibson** [comment]
The same commit fails against run-integration-tests: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/292/pipeline/

Something definitely seems wonky. My hunch is that the docker image that runs smoke tests isn't being updated correctly.

**Comment by jgmize** [comment]
Hi @alexgibson, I'm still looking into the earlier errors, but the `Error response from daemon: Conflict. The container name [...] is already in use by container [...]` was the result of the container names being based on the commit hash and not including the branch name, so when you pushed the same commit to the master branch, there was still a container with the same name running from the previous test against run-integration. The reason it went away on its own is because the other job finished and the conflicting container was automatically removed, but I've run into issues before where the container needed to be manually stopped with `docker stop [container id]`.

**Comment by jgmize** [comment]
Correction, the container name was in use from the previous *master* build; the conflict in job #1594 was from the container running from the aborted job #1593.  The reason the next master job succeeded was because it had a different container name based on a different hash.

**Comment by alexgibson** [comment]
@jgmize thanks, and sorry for all the noise in the jobs. This was a somewhat perplexing morning. Thanks for taking a look :)

**Comment by jgmize** [comment]
After discussing with @alexgibson, we've decided to stop running the smoke tests in a local docker container on jenkins in favor of only running them against deployed instances, which will eliminate this type of issue. I've filed #7030 to address this.

**Comment by alexgibson** [comment]
We removed the smoke tests and on deployment the page that relates to the failing test is 500: https://bedrock-integration-tests.oregon-b.moz.works/en-US/firefox/mobile/

There's also an error in Sentry: https://sentry.prod.mozaws.net/operations/bedrock-dev/issues/5490305/

```
ValueError: The file ‘css/BUNDLES/firefox-mobile-protocol.css’ could not be found
```

This bundle does not yet exist in the master branch, so it looks like something is wrong with the deployment?

**Comment by alexgibson** [comment]
The bundle in question is created in this branch https://github.com/stephaniehobson/bedrock/tree/mobile, which has not yet merged to master.

**Comment by jgmize** [comment]
The deployment completed correctly, but there are references to the firefox-mobile-protocol css bundle in the docker image itself:

```
$ docker run -it mozorg/bedrock:run-integration-tests-2e18467e303f2d3170f72b450c3d5556c5caec32 bash
webdev@a6361129db99:/app$ grep -r 'firefox-mobile-protocol' *
bedrock/firefox/templates/firefox/mobile.en-US.html:  {{ css_bundle('firefox-mobile-protocol') }}
bedrock/firefox/templates/firefox/mobile.en-US.html:  {{ js_bundle('firefox-mobile-protocol') }}
```

However, doing a checkout of that same commit locally, there are no such references:
```
$ git checkout 2e18467e303f2d3170f72b450c3d5556c5caec32
$ grep -r firefox-mobile-protocol *
$
```

The image above was built during https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/293/pipeline/24/ and
Looking at the docker build process in that pipeline, it looks like everything was cached from the previous build in docker. While I suspected a docker caching issue at first, it turns out those references are still there in the jenkins workspace:

```
~/jobs/bedrock_multibranch_pipeline/branches/run-integration-tests/workspace$ git rev-parse HEAD
2e18467e303f2d3170f72b450c3d5556c5caec32
~/jobs/bedrock_multibranch_pipeline/branches/run-integration-tests/workspace$ grep -r firefox-mobile-protocol *
bedrock/firefox/templates/firefox/mobile.en-US.html:  {{ css_bundle('firefox-mobile-protocol') }}
bedrock/firefox/templates/firefox/mobile.en-US.html:  {{ js_bundle('firefox-mobile-protocol') }}
```

I noticed that the jenkins checkout process includes the following:
```
git config core.sparsecheckout # timeout 10
```

http://schacon.github.io/git/git-read-tree.html#_sparse_checkout may be the issue, still investigating.

**Comment by jgmize** [comment]
The sparse checkout was not the issue. The issue was that we don't currently remove untracked files during the build process, and the `bedrock/firefox/templates/firefox/mobile.en-US.html` is untracked on this branch. I was under the impression that the `make clean` command that we do run during each build did this, but this is not currently the case.

**Comment by alexgibson** [comment]
Thanks @jgmize, I rebased on master and pushed to `run-intrgration-tests` and now all seems well again 👍

**Comment by jgmize** [comment]
Now that both #7045 and #7030 have been merged, I believe this is fully resolved.
