### ISSUE TITLE
Extract strings to Pontoon for https://www.mozilla.org/en-US/firefox/windows/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7057]

**Comment by alexgibson** [comment]
I chatted to Peiying here and the best way to translate these pages would be to:

1. Include `{% add_lang_files "firefox/new/quantum" %}` in the templates.
2. Wrap the new strings in l10n conditionals, falling back to the old headline.

This will mean that _all locales_ will be active for this page from the outset, but only those who have translated the new strings will see "Firefox fights for you on Windows."

**Comment by alexgibson** [comment]
As discussed with @rraue, there's an inherant SEO risk involved in this change, which I'm calling out here:

- Because these pages build upon the `/firefox/new/` template and share it's .lang file, we can't activate only those locales that have these new strings translated. Instead, we must activate these pages right away, for every locale.
- Due to the above, we have to use an l10n conditional in the templates to avoid showing mixed English content, and fallback to the old strings should a locale not have the new strings translated.
- Any locales that don't have the new strings translated, will be identical to `/firefox/new/`, so there's a risk of search engines flagging the pages as duplicate content.

Raphael says this is a definite risk, but not a blocker seeing as the requesting team deems this as high priority. Hopefully locales will translate the new strings quickly, but any that don't will likely be duplicate content pages.

As a side note: while making these three pages seemed like a quick and relatively low effort win originally, we should think carefully about how we approach this in the future. Issue https://github.com/mozilla/bedrock/issues/6798 may be worth revisiting.

/cc @ejregithub @hoosteeno

**Comment by rraue** [comment]
I agree, we can ship it like this, I will monitor the risk but we should move forward with #6798 to eliminate this and many more risks.

**Comment by alexgibson** [comment]
Strings have been pushed out to pontoon https://github.com/mozilla-l10n/www.mozilla.org/commit/7056a2046ccfe935f51dd3cc76e8a5d1617dfbce
