### ISSUE TITLE
Evaluate split.io

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7064]
@alexgibson, can you take a look at this application and comment in the doc? https://docs.google.com/document/d/1vkbuqK7onCPhDRm9BsnjFmQFluCRvi0hB4_qM4RKep4/edit#heading=h.xdhcjqwh13mn

**Comment by alexgibson** [comment]
Closing this based on our discussion today. Happy to evaluate further down the road if needed 👍

**Comment by alexgibson** [comment]
Reopening this issue as I'm spending some more time getting this running on demo

**Comment by alexgibson** [comment]
I took a go at writing and implementing an experiment.

You can enter into the experiment here: https://www-demo1.allizom.org/en-US/firefox/campaign/

The code can be found in this branch: https://github.com/alexgibson/bedrock/commits/split-io-demo

Next steps: I'm going to compile a list of questions for the meeting tomorrow.

**Comment by alexgibson** [comment]
@hoosteeno I was eventually able to get event metric data to show up in the dashboard for our test experiment. As suspected, it was because we needed to call `destroy()` before unloading the current page.

I added the answers we've since found to the questions section in the evaluation doc. Based on this, I'm going to close this issue as done, but I'm happy to discuss this evaluation further in person. Thanks.
