### ISSUE TITLE
The link to Lockbox's android app, actually points to the ios app.

### ISSUE THREAD

**Issue by AniketSK** [mozilla/bedrock#7103]
## Description

The iOS app link opens no matter if you click the Google Play or App Store icon.

### Steps to reproduce

Go to the code here https://github.com/mozilla/bedrock/blob/266208420d8ee11d1cf89652337ba7a2f8e816b7/bedrock/firefox/templates/firefox/accounts-2018.html#L103  and open the link. It's labelled Android but it's iOS.

### Expected result

Links to the android app.

### Actual result

Open the Apple App Store

### Environment

What browser and operating system are you using?

Not Applicable

**Comment by craigcook** [comment]
The adjust.com links are meant to be "smart" redirects, which work correctly on mobile platforms but they don't seem to know what to do on any device that isn't Android or iOS so it just goes to the first configured destination.

I think we have a few options:

1. Link each store badge directly to the specific store (without going through Adjust).
2. Display the badges but don't make them links.
3. Remove the badges from the modals.

I feel like showing the badges is a good thing, since it both clearly indicates which platforms an app is available for and also adds some authenticity. There's an argument for showing them but not making them links, but I think many users will expect them to be links and want to click them. So I would favor option 1 but could be convinced for option 2.

I'll talk to the team and see what we think is the best solution here. Thanks!

**Comment by alexgibson** [comment]
This was fixes as part of the work in https://github.com/mozilla/bedrock/issues/7214
