### ISSUE TITLE
Simplify the /ru/firefox/new/ Yandex page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7117]
## Description

Last year we had to create a [special version](https://www-dev.allizom.org/ru/firefox/new/?geo=ru) of the `/ru/firefox/new/` page, that changes both imagery and messaging if the user is geo-located in Russia, in order to display Yandex specific messaging.

The way this page is constructed is both brittle and has performance issues (since it relies on a client side geo-lookup before deciding what messaging to display). Maintaining the page in this way is also time consuming, and there's a risk of accidental breakage in the way we swap out content and messaging in the DOM.

One solution we talked about was creating a `/ru-RU/` locale, specific for Russia. This could then feature a Yandex version of the page, whilst the regular `/ru/` locale could display the regular Firefox download page.

**Comment by rraue** [comment]
I think that would be a better solution than the one we have right now and way better to read for crawlers. We have to do the hreflang right, but that should be doable. It is just the /new page, right?

**Comment by alexgibson** [comment]
> It is just the /new page, right?

Yes correct

**Comment by alexgibson** [comment]
Another way to simplify this (now outdated) page could also be to:

- Split this out into two separate pages, at two different URLs (say the regular `/new` and `/new/yandex/`)
- Use a [cloudflare worker](https://github.com/mozmeao/www-workers) to redirect people physically localed in Russia from one to the other.

**Comment by hoosteeno** [comment]
@alexgibson what does success look like on this? Would you be up for writing success criteria? With those, I think this is ready for solutioning.

**Comment by alexgibson** [comment]
@hoosteeno from a product point of view, is building this page to live at /ru-RU/firefoix/new/ a viable solution? Or do we have to do this using geo-location?

**Comment by alexgibson** [comment]
Update: we met with the product/search team on friday and agreed on the following:

- We'll split this out into two pages, `/ru/firefox/new/` and `/ru/firefox/new/yandex/`.
- We'll use geolocation (preferably a cloudflare worker), to redirect from one URL to the other, if the visitor is geo-located in Russia.
- We don't want to use the locale-only solution (ru-RU), because revenue generated from searches is tied to physical location.

**Comment by alexgibson** [comment]
@rraue any concerns with the above, assuming we set the canonical for the yandex URL to point to the regular ru page?

**Comment by rraue** [comment]
Problem is then, that in russia (google and yandex) the regular /new will show up and if I remember right this was not what we wanted.

**Comment by alexgibson** [comment]
> Problem is then, that in russia (google and yandex) the regular /new will show up and if I remember right this was not what we wanted.

People in Russia will be redirected to the Yandex page

**Comment by rraue** [comment]
That might work for Google, but with Yandex I am not sure, as their crawler will have a russian IP therefor will be redirected and then via canonical be told the original is where it will get redirected again. Most likely Yandex will then ignore the canonical and everything should be fine. But tehre is a risk. Yandex cant update their search results, their links yes but the search results are algorithmic.

**Comment by alexgibson** [comment]
So if we had two separate URLs, what would be your suggested solution for indexing?

Fwiw, I don't see any evidence that the current solution surfaces the Yandex copy in their search results:

![image](https://user-images.githubusercontent.com/400117/74156742-e137b900-4c0e-11ea-82e5-ab28395ef66d.png)

**Comment by rraue** [comment]
Exactly but didnt we want the yandex copy in search?

**Comment by alexgibson** [comment]
What I’m trying to say is the current solution doesn’t work well now, so can using separate urls make the results better? What would be your proposed hreflang solution if this was viable?

**Comment by alexgibson** [comment]
After talking this through with @rraue on Zoom it's more clear that using two separate URLs could potentially cause some issues with regard to indexing, even though people would be seeing the right content. Also given the current solution that's in production today also doesn't work well with indexing (see screenshot above), using the `ru-RU` locale may be worth some further consideration.

@rraue is going to add some more information here as to why he thinks it may work better than using geo-location.

**Comment by hoosteeno** [comment]
Next steps on this are @rraue to research whether any simplification option can work with search, considering the geolocation requirements.

**Comment by rraue** [comment]
What I understand for now:

1. If we want to simplify this page, we need two different urls, one for the normal build and one for the yandex build
2. We need to redirect users with a Russian IP to the yandex build page

If we do 1. we need to make these pages crawlable and clear whats the purpose of these two pages. And as the yandex build is just for Russians in Russia, a new locale included in our hreflang setup will do the best work so it can be indexed by search engines and its clear where it should rank (in Russia) and where not (not in Russia). [I gathered some data to show, that the setup in bedrock is very solid](https://docs.google.com/document/d/1YfQaAfjo_s30vnWHzZa9gPaa9zwxckM7TcmGVvdlnJU/edit?usp=sharing). 

We need to do 2. as search traffic is only 50% of the traffic from Russia to /new. To not confuse crawlers we need to make small changes to our hreflang setup:

- [ ] The x-default needs to change to the url version without locale, so crawlers can test different locations and accept language headers to understand our setup. This change needs to be done on all pages on bedrock, not just on /new

- [ ] We need to build /ru-RU/ and we need at least the homepage for /ru-RU/ (can be a complete copy of /ru/) as well, so it can link to /ru-RU/firefox/new/ (the yandex build) and...

- [ ] We need to add Russia to the /locales/ page linking the homepage /ru-RU/ there so it can be easily crawled. 

This should be good for crawlers to recognize and "understand our setup. Because of the redirect 100% of users from Russia will land on the right page and we have two pages, so our setup is simplified.

There is a risk left we need to monitor, if rankings change in google and Yandex, but I assume it will work.

**Comment by alexgibson** [comment]
@rraue this sounds well reasoned to me.

@hoosteeno thoughts? We'd need to do the three items above first, which we can tackle in separate issues.

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/8512

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/8513

**Comment by hoosteeno** [comment]
Is the ultimate output here -- which appears to be a new homepage, a refactored download page, changes to /locales, and a global meta tag -- a simplification? Seems like more moving pieces in more places.

**Comment by alexgibson** [comment]
> Seems like more moving pieces in more places.

This solution might be better for crawlers, but it is still complicated. The other option is we decide not to persue this course of action, and just commit to updating a complicated page.

**Comment by alexgibson** [comment]
Right now I’m swaying to saying all this work is probably greater effort than just updating the current page to Protocol, and keeping the logic as-is.

**Comment by alexgibson** [comment]
I've slept on this and I still agree, the solution here is no less complex than what we alreadfy have. There would be more moving pieces, and should any of them break the effects may not be obvious immediately.

I'm going to close this as wontfix, and open a new issue to port the existing yandex page to Protocol.

I really appreciate everyone's time and effort helping to think this complicated problem through.
