### ISSUE TITLE
pre-download FxA CTA for Firefox users modal - Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7232]
The copy and design here is final, from https://github.com/mozilla/bedrock/issues/7201

"here's the sketch file with the modal design and final copy FxA-modal-:[new.sketch.zip](https://github.com/mozilla/bedrock/files/3278364/FxA-modal-.new.sketch.zip)"

**Comment by alexgibson** [comment]
@hoosteeno @mrkwvr @claychaffin this is now up on demo, please review thanks.

https://www-demo5.allizom.org/en-US/firefox/new/

Note: you need to be using Firefox and **signed-out** of an account to see the modal.

**Comment by claychaffin** [comment]
Thanks. Comments: for consistency, please use title case for "Content Blocking" and capitalize "Blocking" everywhere they appear. Please delete the exclamation point in the button copy "Got It!" so it reads "Got It" . Last, please — do we know who wrote the copy (so I can consult them if needed)-- and is there a copy deck? I'd like to capture the changes in the deck.

**Comment by claychaffin** [comment]
Are we still be able to add a comma to the copy at this point? This would be a new add, it’s not in the copy deck.  I’ve always wanted to add this comma, but wasn’t able to before because the brand guidelines didn’t permit the serial comma; those guidelines have now been reinterpreted and thus we now have latitude to add the serial comma on a case by case basis. The ask: I'd like to add a comma after "Lockwise" so the subhead will read "...protect passwords with Firefox Lockwise, and more." I think this will make the line easier to understand.

**Comment by alexgibson** [comment]
I will add the comma, thank you
