### ISSUE TITLE
Inconsistent Capitalization in Product names

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/bedrock#7291]
Hi there,

I noticed on https://www.mozilla.org/en-US/firefox/accounts/ that the "b" in Firefox Browser isn't capitalized while the rest of the products are.

![nitpick](https://user-images.githubusercontent.com/1578674/59040977-c02ff480-8845-11e9-9ae0-8b9de5b1b19d.png)

**Comment by teonbrooks** [comment]
a good point was raised in Slack that "browser" in this case is not a product name but the rest are. I am not sure where this falls. feel free to close it if this was intentional

**Comment by craigcook** [comment]
This was intentional. We're not treating "Firefox browser" as a proper name here, it's just a descriptive term to distinguish Firefox-the-browser from the other products under the Firefox umbrella.

As this family of products and services evolves it's possible that we'll need to come up with a distinct proper name for the Firefox browser in the future, but for now the browser is still just "Firefox."

Thanks!
