### ISSUE TITLE
/new download does not work in Web Light

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#7401]
## Description

In Google Search Console I found a report about [Web Light](https://support.google.com/webmasters/answer/6211428?hl=en&ref_topic=2370586) results for www. It states we got around 60k clicks in the last 12 month with this "feature" of Google for low internet connections on mobile phones. 

### Steps to reproduce

I checked /new as it gets the most traffic from these results and the download does not work in this web light page (https://googleweblight.com/i?u=http%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Fnew%2F&s=2). I tested it on my mac (chrome and firefox) and on my iphone (chrome and firefox).

If the link does not work, [here is a description how to test Web light results](https://support.google.com/webmasters/answer/6211428?hl=en&ref_topic=2370586)

### Expected result

Clciking on download usually takes me to the appstore on my iphone and starts the download on my mac

### Actual result

Desktop takes me to [market://details?id=org.mozilla.firefox&referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org](market://details?id=org.mozilla.firefox&referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org) and the page doesnt resolve. Mobile does this:
![IMG_BEDC6AD880D3-1](https://user-images.githubusercontent.com/36700618/60891678-14bbfa80-a25e-11e9-9550-d999d6d942f3.jpeg)
![IMG_D867C2A095B3-1](https://user-images.githubusercontent.com/36700618/60891679-14bbfa80-a25e-11e9-8799-f9733bba84c6.jpeg)

### Environment

 Tested it on my mac (chrome and firefox) and on my iphone (chrome and firefox).

**Comment by rraue** [comment]
60k clicks on mobile does not sound very much, but in the [doc on Web Light there is  a description on opting out](https://support.google.com/webmasters/answer/6211428?hl=en&ref_topic=2370586) of Web Light and unless tehre is an easy fix and anyone knows how Google transforms these pages in Web Light, I would just propose we opt out for all /new pages:

> If you do not want your pages to be transcoded, set the HTTP header "Cache-Control: no-transform" in your page response. If Googlebot sees this header, your page will not be transcoded.

**Comment by alexgibson** [comment]
So it appears when Google renders the "light" version of this web page, whatever renders the HTML appears to identify itself as Android. That's why the download button uses a protocol that does not work on either iOS or macOS: 

market://details?id=org.mozilla.firefox&referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org

We have some custom code that creates that link here: https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-utils.js#L16-L26

We could remove that code, but even then the button that gets rendered would be the Android link to https://play.google.com/store/apps/details?id=org.mozilla.firefox&referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org

Another solution other than opting out entirely, would be to replace the regular download button with a pair of app store buttons for both iOS and Android.

**Comment by hoosteeno** [comment]
@alexgibson Is your suggestion to replace the download button for all Android-like UAs, or is there some way we can target Web Light?

If "all Android", do you have any background on why we haven't done so previously?

**Comment by alexgibson** [comment]
@hoosteeno I see two possible options to try and solve this. 

1. For mobile devices (iOS and Android) we show both an App Store button **and** a Play Store button. We would need to show both buttons because the web light feature appears to use an Android-like UA string when rendering the HTML result, even for iOS. This is just another example of why relying on UA detection is a brittle game.
2. We opt out of the web light feature altogether, becuase we have too much reliance on UA detection (this would be unfortunate and less wanted imho).

**Comment by maureenlholland** [comment]
Closing as not planned since Google appears to have retired Web Light user agent: 

> December 19 [2022]: Removed the [Web Light documentation](https://developers.google.com/search/docs/crawling-indexing/mobile/web-light) and retired the [Web Light user agent](https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#retired). We introduced Web Light to enable us to serve faster, lighter pages to people searching on entry-level devices. While this feature has worked as intended and enabled broader access to the richness of the web, increased affordability of more powerful smartphones has diminished the need for such functionality. We remain committed to evolving and refining the Search experience to meet the changing needs of our users.
