### ISSUE TITLE
Replace English language images on features/adblocker/ 

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#7414]
## Description

Considering that [features/adblocker/](https://mozilla.org/firefox/features/adblocker) will be localized (#7112), we should consider swapping out the English-language screenshots for images that would be helpful to all locales.

<img width="643" alt="Screen Shot 2019-07-10 at 2 31 41 PM" src="https://user-images.githubusercontent.com/30483988/61006699-c838f380-a31f-11e9-86cf-80938e030ab6.png">

**Comment by Shivansh2407** [comment]
Is this issue fixed?

**Comment by amychurchwell** [comment]
@dzingeek do we have an approach we could take for this issue or should this be marked as a WONTFIX?

**Comment by dzingeek** [comment]
@amychurchwell I am going to consult with the creative team on this and get back to you. Might not be until next week though.

**Comment by alexgibson** [comment]
@craigcook is this still relevant today for the feature pages redesign? If not, can we close this out?

**Comment by craigcook** [comment]
> @craigcook is this still relevant today for the feature pages redesign? If not, can we close this out?

Still relevant, since we're so far keeping the same content and images, just wrapping it in a new template. Producing a lot of localized images probably isn't practical but we might be able to do them for a few of the top locales. But even that is a lot of work. So while localizing is the right thing to do I just don't think we can.

I'm inclined to close this for now but maybe we can rethink this page.
