### ISSUE TITLE
WNP  69 - Design for new page w. modular layout/capability for reuse

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7456]
Description: Design a new WNP 69 with a modular system of reusable components

**Comment by ejregithub** [comment]
@mrkwvr - can you please post links (or images directly in this issue) to that latest designs?

**Comment by mrkwvr** [comment]
initial design for WNP 69. copy is placeholder![FX-WNP-69.png](https://images.zenhubusercontent.com/5caf3c03b1a2d93c3b8e816d/ed96a752-d799-4066-b64a-e99973ffc791)

**Comment by ckinswood** [comment]
Two thoughts: 

1) The drop-shadowed CTA box looks like a modal or "pop up" to me, which makes the page feel like an ad. I love the full-bleed color CTA section on the /new page and would love to see something similar here. 
2) The secondary section is small text floating in a large white space and I think that is contributing to my sense of the page as "unfinished". I have like the more contained "cards" or "blocks" featured in previous WPNs and /new or about:welcome.  
3) We are discussing making the "release notes" footer a full sentence with a link to release notes and I'm interested in how that will affect design. It's obviously not the main focus of the page, but I think more emphasis might not hurt. The current three option utility bar feels smaller or more like an after thought.

**Comment by dzingeek** [comment]
@ckinswood a few things to note.

1. The box + drop shadow is part of our system and it has seemed to work pretty well in the past especially around signing up for an account. 
2. A few reasons this (the current) WNP has worked better than past WNPs is because we initially made it feel less like an ad and more like it's in the product (getting out of the users way). We also focused on the user for content and offered them value (something they want). _these are my person opinons on the why_
3. Too many cards start to make all cards meld together and then nothing stands out. we need to make sure this page has focus and hierarchy.

**Comment by hoosteeno** [comment]
@LaurenNiolet as The Decider on this, could you make the call on the feedback above? We need to move forward with this one.

**Comment by LaurenNiolet** [comment]
Let's move forward with it as is. I think while @ckinswood has good feedback, let's let the web team make the call on those details.

**Comment by ckinswood** [comment]
Sounds great! And thanks @dzingeek for walking through the logic with me.

**Comment by ckinswood** [comment]
Sounds great! And thanks @dzingeek for walking through the logic with me. 

Finally, per conversations with @hoosteeno @LaurenNiolet and @claychaffin, we are requesting a second "secondary" block to the signed-in state. We will pull the copy (already localized) from a previous WNP.

**Comment by ejregithub** [comment]
Design here is done, signed off on by Lauren during our review meeting today. Closing
