### ISSUE TITLE
Revive the MoFo fundraising banner from 9/3 through 9/14

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7477]
## Description

MVP is to revive the previously used MoFo fundraising banner from August 26 (Monday) through Sept. 6th (Friday.) - a separate card will be filed for the removal.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live on the specified date, 9/3 (originally 8/26)

#### Tasks
- [ ] Revive the MoFo fundraising banner from #7296 taking it live on 9/3

**Comment by hoosteeno** [comment]
Since we keep resuscitating this work, can we put it behind a switch so it's an easy on/off.

**Comment by craigcook** [comment]
We filed https://github.com/mozilla/bedrock/issues/7185 a while back to make this a more permanent feature, though it's not fully specced out.

**Comment by Errolyn** [comment]
@hoosteeno will this banner be using the same copy as last time?

**Comment by hoosteeno** [comment]
@WillatMozFdn, can we land the very same banner we previously used? If so, this is a very straightforward ask. Thanks!

**Comment by Errolyn** [comment]
I have a branch with the banner added back in. I can put up a demo if that would be helpful?

**Comment by Errolyn** [comment]
Also what are the analytics requirements for this banner?

**Comment by ejregithub** [comment]
This is verbatim to the previous banner. Analytics should already be in there - please ask @craigcook for details

**Comment by craigcook** [comment]
There are some hidden fields in the form that we update to identify the campaign. Last time it was `apr2019banner` so this time I guess that would be `aug2019banner`? We can check with Will if that works or if they want something else.

**Comment by WillatMozFdn** [comment]
hey gentlemen, apologies for the delay responding.  Yes, same banner verbatim -- I had some grand ideas about testing but I don't think those can come to fruition in time.  @craigcook indeed, please update the hidden field (which I _think_ drives the utm_campaign value, please correct me if I'm wrong) ...but let's make it "sept2019banner" ... because, I need to ask you guys if it's ok to **push this back calendar-wise about 8 days, and run it from Sept 3 through the 14th**?  I would really like it to be active when we send out our fundraising emails for this campaign, and we recently had to push those back by about a week.  Let me know if any problems with that plan?  Thanks!!!

**Comment by WillatMozFdn** [comment]
@Errolyn yes please on the branch for a demo ... just want to check and make sure everything's linking correctly and verbage still current.  (99% sure it is, but never hurts to double-check.)  Thanks!

**Comment by Errolyn** [comment]
Here is the Demo!  https://bedrock-demo-errolyn.oregon-b.moz.works/en-US/

**Comment by ejregithub** [comment]
We have sign off from the Approver, Will, in Slack. Noting that here. Also, i update the go live and removal dates according to Will's request on[ August 14th](https://github.com/mozilla/bedrock/issues/7477#issuecomment-521475480)
