### ISSUE TITLE
/mobile page instrumention/analytics

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7860]
We need to be sure we have page interaction and links properly accounted for and measured.

The request the Growth Team is to change, move away from, using Adjust links for mobile device application store links (iOS and Android, AppStore and GooglePlay).  

Guy has presented the following links,[ in this doc](https://docs.google.com/document/d/1dTewRuidMPQA5Q-b-eHNY9AIx6nxPWmpFG1q9N3eXkg/edit):

Fennec (Google Play): https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en
Firefox iOS (App Store): https://apps.apple.com/us/app/firefox-private-safe-browser/id989804926

With the reasoning that: "Optimally (for SEO/ASO) the links should be direct to the app stores with UTM tracking as they pass more value and authority versus redirects. The Adjust links are also 302 (temporary redirects) vs 301 (permanent redirects) which also means that they pass less value."

**Comment by Errolyn** [comment]
An update on this: because we are using adjust links we have to do some tracking down of the utms since they are being added via adjust not any of our code. I am going to finish and push the rest of the changes for the page and handle this in a separate pr.  (unless someone has a list of the utms we need to use handy)

**Comment by alexgibson** [comment]
Mobile page is live, closing
