### ISSUE TITLE
Determine approach for migrating existing localizations

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7877]
## Description

When migrating existing legacy content (mission.html and mission.lang become mission.html and mission.ftl), we want to port the localizations as well (bringing over existing localizations from .lang into .ftl files). 

* We need to make sure it's done in a way that does not trigger a ton of new work for Pontoon localizers
* We don't want to carry over all the cruft that has accrued in .lang files

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] In a meeting between pmac and Pike, we have figured out how to code this so that...
- [ ] The fluent files for reference English are well structured
- [ ] No existing localizations are lost
- [ ] The fluent files for all the localizations follow the improved structure from reference English

**Comment by alexgibson** [comment]
The definition of a process in which these migrations will happen is still somewhat in flux, and seems to have become a bit of a blocker currently. @pmac has written some scripts in bedrock for migrating .lang files to .ftl, migrating jinja templates, and also migrating existing localizations, so that they are ready to submit as a PR to the L10n repo.

That work seems to fit most of what's defined above, but @pike called out some ways in which we need to improve the quality of migrated .ftl files, which are captured in https://github.com/mozilla/bedrock/issues/8045.

There also still seems to be some consensus that we need to change some of what we've already implemented, to better suit the needs of Pontoon; but I'm not the best person to define what those needs are. I've asked others to try and help articulate here.

**Comment by pmac** [comment]
Here's what I have so far for a flow chart. See if this gels with what we've been saying @alexgibson @Pike 

![Basic Flowchart](https://user-images.githubusercontent.com/19176817/68242369-62fbc300-ffde-11e9-879e-d508d246c7f7.png)

**Comment by alexgibson** [comment]
Thanks @pmac! In terms of how data gets from bedrock to each l10n repository, I think I follow along ok here, although I'm still a little confused about how data should flow between www-l10n and the l10n-team repo. If I'm interpreting this right, there would be a PR opened against the l10n-team repo, but the www-l10n repo would already contain the FTL files and metadata?

**Comment by Pike** [comment]
The chart looks good to me, too.

Yes, when we have a migration recipe, we generate two exports, one into `www-l10n` and one into `l10n-team`.

Once the PR on `l10n-team` is merged, the next automation kicks in that exports from `l10n-team` into `www-l10n`. Given the "once" can be days, we need to do both.

I'm also assuming that the next automation does automatic activation based on the rules we have. The activation step in the `www-l10n` part is to ensure we don't deactivate by chance. Right, @pmac?

**Comment by alexgibson** [comment]
> Once the PR on l10n-team is merged, the next automation kicks in that exports from l10n-team into www-l10n. Given the "once" can be days, we need to do both.

Given that it might be X days before the l10n-team PR gets reviewed and merged, what happens if something needs to change in bedrock in the meantime (say we migrate a page, and the next day someone asks to add a new string?). Would this be handled by the same automation, or would this be a case of needing to be extra viligent?

**Comment by pmac** [comment]
> Once the PR on `l10n-team` is merged, the next automation kicks in that exports from `l10n-team` into `www-l10n`. Given the "once" can be days, we need to do both.

Exactly.

> I'm also assuming that the next automation does automatic activation based on the rules we have. The activation step in the `www-l10n` part is to ensure we don't deactivate by chance. Right, @pmac?

Also right. I'll be adding the other automation (l10n-team -> www-l10n) to the chart next.

> I'm still a little confused about how data should flow between www-l10n and the l10n-team repo.

Data will only flow from l10n-team to www-l10n. The only exception to this flow is when we're porting existing translations, when there will be direct flow from bedrock automation to www-l10n. There should never be direct flow from www-l10n > l10n-team.

**Comment by alexgibson** [comment]
I think we have this wrapped up - automation is done, and migration docs exist: https://bedrock.readthedocs.io/en/latest/fluent-conversion.html
