### ISSUE TITLE
Not passing through utm parameters from upstream referrals on /firefox/accounts/

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8001]
## Description

The page at www.mozilla.org/firefox/accounts/ is not passing through parameters coming from upstream referrers. It should be.

We have worked on this several times in 2019, most recently at https://github.com/mozilla/bedrock/issues/7585. We should review that work to understand if this bug relates to that in any way.

### Steps to reproduce

1. Visit about:welcome in a *Firefox Profile that is not signed in to Sync*.
2. Click the "Learn More about the Benefits" link at the bottom of the firstrun experience. 
3. Note the parameters on the URL: `https://www.mozilla.org/en-US/firefox/accounts/?utm_campaign=firstrun&utm_medium=referral&utm_source=activity-stream&utm_term=trailhead-join`
4. Fill in the Sync sign-up form (perhaps with a fake email address) and submit.
5. Note the parameters on the URL: `https://accounts.firefox.com/signup?action=email&context=fx_desktop_v3&service=sync&entrypoint=mozilla.org-firefox-accounts&form_type=email&flow_id=7c45f2ee51998ba8ae782391e1fbf4813174e8253668742d916bc0afd77fa440&flow_begin_time=1571857270270&device_id=78ad24a987b64c338da60447a29a7c70&utm_source=mozilla.org-firefox-accounts&utm_medium=referral&utm_campaign=trailhead-fxa-embedded-form&style=trailhead&email=flibbijy%40mailinator.com`\

### Expected result

The second URL should have the utm_source, utm_campaign, utm_medium, and utm_term that the first URL has. 

### Actual result

The second URL has the default utm parameters from this page.

**Comment by amychurchwell** [comment]
@hoosteeno 
I have decided to update `mozilla-fxa-form.js` to check for existing params on the url before using the ones in the [hidden form inputs](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/macros.html#L224-L259).

rough draft:
```
// track external UTM referrals

var urlParams = new window._SearchParams().utmParams();
var attributionData = Mozilla.UtmUrl.getAttributionData(urlParams);

var utms = ['utm_source', 'utm_campaign', 'utm_content', 'utm_term', 'utm_medium'];

for (var i = 0; i < utms.length; i++) {
    if (attributionData.hasOwnProperty(utms[i])) {
        console.log(fxaForm.querySelector(`input[name="${utms[i]}"]`));
    }
}
```

my goal is to replace the corresponding form input value with the utm value from the URL if it is present. The thing is, sometimes the input is `null` because it is not rendered if that value isn’t passed to the macro:

```
{% if utm_content %}
      <input type="hidden" name="utm_content" value="{{ utm_content }}" id="fxa-email-form-utm-content" />
{% endif %}
```

**question:** 
is an acceptable solution to pass a default utm value? something like `utm_content='not-set'`?
This allows for the corresponding input to be available to set a value to if one is present in the URL and a value hasn't been passed through the macro.
Would this muddy analytics or create confusion?
