### ISSUE TITLE
ImageReplaced mixin bug on Safari

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8084]
## Description

Small images at large breakpoint in Safari on firefox/privacy/products

### Steps to reproduce

Go to https://www.mozilla.org/en-US/firefox/privacy/products/ in Safari on a browser at 1056px  or larger.

### Expected result

<img width="916" alt="Screen Shot 2019-11-05 at 13 50 00" src="https://user-images.githubusercontent.com/854701/68249223-342c1f80-ffd3-11e9-90bd-3d0002de6eb7.png">

### Actual result

<img width="914" alt="Screen Shot 2019-11-05 at 13 50 07" src="https://user-images.githubusercontent.com/854701/68249230-3a220080-ffd3-11e9-9b5b-7dd6440b7f32.png">

### Environment

MacOS & Safari

**Comment by alexgibson** [comment]
@stephaniehobson  I did some digging and it turns out this may be a Protocol bug. It's also evident on /firefox:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/400117/68290767-6b0c3f00-0080-11ea-8ea1-16ce2c010d21.png">

It seems to be an issue with our `image-replaced` mixin. For some reason, Sarari doesn't makes the heading with larger, and doesn't respect the `overflow: hidden;` value.

Testing locally, using a negative value of `-120%` seems to work as expected.

Quite why Safari is behaving this way though, I have not yet understood?

**Comment by alexgibson** [comment]
@stephaniehobson I opened a PR with a fix for both pages. I *think* it's happening because it's within a grid layout. Oddly it only happens sometimes, and often only on resize.

I filed a Protocol issue to investigate improving our current mixin: https://github.com/mozilla/protocol/issues/519
