### ISSUE TITLE
Display bug on /firefox in IE10

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8085]
## Description

Hero title over laps hero image in IE10.

### Steps to reproduce

https://www.mozilla.org/en-US/firefox/ in IE10

### Expected result

<img width="1199" alt="Screen Shot 2019-11-05 at 13 51 59" src="https://user-images.githubusercontent.com/854701/68249322-75243400-ffd3-11e9-89a5-42a695b880aa.png">

### Actual result

<img width="1174" alt="Screen Shot 2019-11-05 at 13 39 02" src="https://user-images.githubusercontent.com/854701/68249328-79e8e800-ffd3-11e9-9c6a-975b4811119b.png">

### Environment

Windows 7 & IE10

**Comment by stephaniehobson** [comment]
Can't use calc on an element with `display:flex` in IE10 or 11.

**Comment by alexgibson** [comment]
It looks like the fallback page is also effected:

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/400117/69817783-43c60f00-11f3-11ea-843b-be739050cd05.png">

**Comment by GauravPandey892** [comment]
I would like to work on this issue. 
I have checked and it is still a bug on IE10.
Furthermore, the page looks really different from what it should look like in IE9 (I have attached the photos for IE9). I would like to work on that as well.
Since this would be my first technical based open source contribution I might need some guidance but will try my best to solve this issue.
![1](https://user-images.githubusercontent.com/42074265/92398854-ecbc7580-f146-11ea-8608-55ca70ffc75d.PNG)
![2](https://user-images.githubusercontent.com/42074265/92398858-ededa280-f146-11ea-8830-293c366b433a.PNG)
![3](https://user-images.githubusercontent.com/42074265/92398862-efb76600-f146-11ea-8bc2-c18859b7e8e8.PNG)

**Comment by krush11** [comment]
Hi, can you tell me which file would be needing edits to fix these issues? I would like to work on this

**Comment by tanmayj2020** [comment]
Hi , I would like to work on this issue. This will be my first contribution and please help me with this

**Comment by stephaniehobson** [comment]
I'm sorry, I don't have time to help with this. @alexgibson can you help or can we remove the help wanted tag?

**Comment by alexgibson** [comment]
As our contributing guide says, Mozilla employees may not always have time to mentor issues, but pull requests are always welcome.

https://github.com/mozilla/bedrock/blob/master/.github/CONTRIBUTING.md

The HTML file for this issue is here: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/home/index-master.html

The CSS file is here: https://github.com/mozilla/bedrock/blob/master/media/css/firefox/home/master.scss

Please only submit a patch if you know what needs doing, and have a copy of IE10 available to test.

**Comment by krush11** [comment]
I have tried but i didnt find any way to install IE10, only IE11 is available. Also since IE is now upgraded to Edge i dont think this issue has any point

**Comment by janbrasna** [comment]
The page has been removed since, and replaced with another one that works just fine in IE10.
_(With a few visual glitches in FxA form and footer alignment, nothing blocking users from interacting with it. Dropdowns work, language switching work etc.)_

![Screen Shot 2024-06-17 at 10 24 11](https://github.com/mozilla/bedrock/assets/1784648/0a4db74c-0d90-47a3-bf46-a87f21e89204)

Can be closed now as this got resolved by #14349

**Comment by alexgibson** [comment]
Thanks @janbrasna, closing!
