### ISSUE TITLE
Toggle icons on enterprise sla cut off

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8259]
The toggle icons on https://www.mozilla.org/en-US/firefox/enterprise/sla/#services are being cut off.

<img width="785" alt="Screen Shot 2019-12-04 at 15 03 55" src="https://user-images.githubusercontent.com/854701/70189147-5040e080-16a7-11ea-9888-5ceb29e81b60.png">

**Comment by craigcook** [comment]
the `background-size` here is being overridden by the `background` shorthand later in the cascade https://github.com/mozilla/bedrock/blob/master/media/css/firefox/enterprise/sla.scss#L144

My mistake. Easy fix BUT I also can't remember why I copied it over from Protocol instead of just using the Protocol component directly... there may have been a reason at the time that is no longer the case. Maybe it hadn't been added to Protocol yet? In which case the real fix for this is using the component properly now.
