### ISSUE TITLE
Docker installation not working

### ISSUE THREAD

**Issue by imskr** [mozilla/bedrock#8365]
## Description
When building it locally using docker it is showing errors!

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

`sudo make clean run`

### Expected result

What should happen?

### Actual result

find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '__pycache__' -exec rm -rf {} +
rm -f .coverage
rm -rf docs/_build/
rm -rf static_build/
rm -f .docker-build*
git clean -d -f
make pull
make[1]: Entering directory '/home/shubham/Github/bedrock'
git submodule sync
Synchronizing submodule url for 'vendor-local/src/legal-docs'
git submodule update -f --init --recursive
Submodule path 'vendor-local/src/legal-docs': checked out 'd53597836ca64da68698710675a2620735fd2ac9'
GIT_COMMIT=  pull release app assets builder app-base
/bin/sh: 1: pull: not found
make[1]: [Makefile:45: pull] Error 127 (ignored)
touch .docker-build-pull
make[1]: Leaving directory '/home/shubham/Github/bedrock'
up assets app
make: up: Command not found
make: *** [Makefile:51: run] Error 127

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
NAME="Pop!_OS"
VERSION="19.10"

**Comment by vinay-deshmukh** [comment]
The following worked for me:

1. Run `docker-compose`. This will prompt you to install this command, and then install it.

2. Try running the `make clean run` command again. It should give you an error like:

```
[vinay@localhost bedrock]$ make clean run
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '__pycache__' -exec rm -rf {} +
rm -f .coverage
rm -rf docs/_build/
rm -rf static_build/
rm -f .docker-build*
git clean -d -f
make pull
make[1]: Entering directory '/home/vinay/Desktop/bedrock'
git submodule sync
Synchronizing submodule url for 'vendor-local/src/legal-docs'
git submodule update -f --init --recursive
Submodule path 'vendor-local/src/legal-docs': checked out '6b1e21261a54a21c8104c74f46a8d44c90f5ce8c'
GIT_COMMIT= /usr/bin/docker-compose pull release app assets builder app-base
Pulling assets (mozmeao/bedrock_assets:latest)...
**ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?**

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
make[1]: [Makefile:47: pull] Error 1 (ignored)
touch .docker-build-pull
make[1]: Leaving directory '/home/vinay/Desktop/bedrock'
/usr/bin/docker-compose up assets app
**ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?**

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
make: *** [Makefile:53: run] Error 1
```


3. Make sure that the docker service is running by:
```
[vinay@localhost bedrock]$ sudo service docker status
[sudo] password for vinay: 
Redirecting to /bin/systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2020-07-18 15:42:10 IST; 10min ago
     Docs: http://docs.docker.com
```

In case it's not running, you can follow [this tutorial](https://developer.fedoraproject.org/tools/docker/docker-installation.html) to start the service.

4. Finally, run the `make clean run` command with sudo privileges:

`sudo make clean run`

After running this command, a lot of files are being downloaded, which I assume are the necessary docker images. Will update this comment, if any other fixes are needed.


---------------------------


The reason you need `sudo` before `make` is because the Makefile calls the `docker-compose` command, and since the docker daemon requires sudo privileges to run. More information [here](https://developer.fedoraproject.org/tools/docker/docker-installation.html)

**Comment by robhudson** [comment]
It's been a couple years since this report was opened and many of us on the dev team use Docker. Going to close but feel free to re-open with specific issues.
