### ISSUE TITLE
Capturing work: Migrate bedrock from Gulp to Webpack and add ES6

### ISSUE THREAD

**Issue by Errolyn** [mozilla/bedrock#8392]
## Description

We are changing out gulp with webpack. All tasks handled by gulp should be moved to the equivalent tech in webpack.

**Comment by alexgibson** [comment]
@Errolyn looking at your PR this seems like a pretty large change that touches many files, which may be a little difficult to land given the frequency of code changes that can happen in bedrock. If you'd like to discuss ways to make this easier I'd be hapy to try and help :)

As it stands this is a pretty meta issue, and I do wonder if breaking this work down into some distinct tasks / items may help? For large technical changes like this, we also like to record desisions in an [ADR](https://bedrock.readthedocs.io/en/latest/architectural-decisions.html). This may be a good thing to add here, so that we can understand why we're making the switch, and what the consequences are (if any).

I'm excited to see this work come to fruition :)

**Comment by alexgibson** [comment]
@Errolyn I'm not sure if this is something you’re still working on, but it is something I’m keen to explore further and put back on the roadmap. If the scope of this change is proving too large to make it land-able, then I let’s meet to discuss a path forward some time? 🙂

**Comment by Errolyn** [comment]
That sounds great, the site was changing to much to fast to keep pace with.
So I got to the point that the time I could spend on it was completely
consumed with rebasing.

**Comment by alexgibson** [comment]
Ok, let's close this issue for now and we'll circle back on how to approach this again in the future.
