### ISSUE TITLE
Request for technical detail, visitor data

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8409]
## Description

We need to understand what information bedrock is currently capable of detecting a about a user when a user visits the site (WMO). The ask is to create a list of all those data points with details about them and comments on the significance of each and any caveats (like DNT), along with a description of 'how it works'

[Stub Attribution](https://bedrock.readthedocs.io/en/latest/stub-attribution.html) (what information does this provide, how does it work, does it work only for Windows)

----
How, outside of Stub Attribution, which data, are and how, gathered for:
User agent
IP Address
Browser Information
other

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] A list of all things we can learn about a user visiting WMO is document

**Comment by alexgibson** [comment]
The following is a list of information that mozorg is technically **capable** of collecting. We don't collect everything here, automatically, for every page we visit. Many things here, particularly the UITour API information, we only use on an as-needed basis, only on certain pages.

## Information available cross-browser, for all user agents:

- `navigator.userAgent` (browser name & version).
- `navigator.platform` (OS name and version).
- All session data in [Google Analytics](https://analytics.google.com).
- All session data in [Convert](https://convert.com) (experimental pages only).
- Geolocation data via [Cloudflare](https://www.cloudflare.com) (country code, not IP address).

## Information available from Firefox users (via [UITour](https://firefox-source-docs.mozilla.org/browser/components/uitour/docs/UITour-lib.html))

App Info:

- `canSetDefaultBrowserInBackground` – Whether the application can be set as the default browser in the background without user interaction.
- `defaultBrowser` – Whether the application is the default browser. Since Fx40.
- `defaultUpdateChannel` – Update channel e.g. ‘release’, ‘beta’, ‘aurora’, ‘nightly’, ‘default’ (self-built or automated testing builds)
- `distribution` – Contains the distributionId property. This value will be “default” in most cases but can differ for repack or funnelcake builds. Since Fx48
- `profileCreatedWeeksAgo` – The number of weeks since the profile was created, starting from 0 for profiles dating less than seven days old. Since Fx56.
- `profileResetWeeksAgo` – The number of weeks since the profile was last reset, starting from 0 for profiles reset less than seven days ago. If the profile has never been reset it returns null. Since Fx56.
- `version` – Version string e.g. “48.0a2”

FxA:

- `setup` – Whether FxA is setup on this device. If false, no other properties will exist.
- `accountStateOK` – Whether the FxA account state is OK. If false, it probably means the account is unverified or the user has changed their password on another device and needs to update it here. In that case many other properties will not exist.
-  `numOtherDevices` – Number of devices connected to this account, not counting this device.
- `numDevicesByType` – A count of devices connected to the account by device ‘type’. Valid values for type are defined by the FxA server but roughly correspond to form-factor with values like ‘desktop’, ‘mobile’, ‘vr’, etc.
-  `accountServices` – Information about services attached to this account. These services may be enabled on devices or applications external to this browser and should not be confused with devices. For example, if the user has enabled Monitor or Lockwise on one or more devices - including on this device - that service will have a single entry here.
- `browserServices` – Information about account services attached to this browser, and with special support implemented by this browser. You should not expect every accountService connected in this browser to get a special entry here. Indeed, what services, and in what circumstances they may appear here in the future is largely TBD.

Account services:

-  `id` – The service ID. A list of attached service IDs can be found on our telemetry documentation site.
- `lastAccessedWeeksAgo` – How many weeks ago the service was accessed by this account.

Sync: 

- `setup` – Whether sync is setup
- `desktopDevices` – Number of desktop devices
- `mobileDevices` – Number of mobile devices
- `totalDevices` – Total number of connected devices

Search:

- `searchEngineIdentifier` – The default engine’s identifier
- `engines` – Identifiers of visible engines

FHR:

- `getTreatmentTag`: Retrieved the value for a set FHR treatment tag.

**Comment by alexgibson** [comment]
It looks like it mkight still be possible to set the default browser via this API call:

https://firefox-source-docs.mozilla.org/browser/components/uitour/docs/UITour-lib.html#Mozilla.UITour.setConfiguration

**Comment by hoosteeno** [comment]
Confirmed, that API call works on Win8 and Win10. On 10 it just opens up the system dialog; can't actually modify it. So we should probably plan to couple its usage with some light instructions.

**Comment by alexgibson** [comment]
@hoosteeno these API calls may be relevant to the above:

`canSetDefaultBrowserInBackground` – Whether the application can be set as the default browser in the background without user interaction.
`defaultBrowser` – Whether the application is the default browser. Since Fx40.

**Comment by alexgibson** [comment]
I think we have whenwe need here, closing this out.
