### ISSUE TITLE
 Newsletter preferences Thank You page update - Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8539]
## Description

Code the changes in design from the card #8499 that @cgonz0 has specified

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Newsletter preferences UX improvements are in place/live

#### Reviews (of coded page on demo)
- [ ] Dev (code)
- [ ] Brand
- [ ] Team Lead

**Comment by alexgibson** [comment]
@cgonz0 here's a first draft of the newsletter confirmation page.

Some things to note:
- I'm using the default card styling that's in protocol for the three promos. That does differ slightly from what's in your mockups.
- For the "Back to preferences" link, we're assuming people have just come from the preferences page. The link actually uses `history.back()`, so it will go back to whatever page someone came from.

If you have any feedback then please lets discuss. Thanks

https://www-demo2.allizom.org/en-US/newsletter/updated/

**Comment by cgonz0** [comment]
thanks @alexgibson - this looks great

I think the text you have here was in an old mock - perhaps from one of the many variations in the Sketch file?
Please see the final copy [here](https://github.com/mozilla/bedrock/issues/8499) - or in the copy [doc](https://docs.google.com/document/d/1sl9-oS7BadcITkt2udV_PuJoeYRlN7FdxVYnzDbKFZI/edit#). Success msg, headers, and card copy will need updating.
___________________________________
Spacing - 
Can we decrease the space above the main header (c-updated-block)
and increase space below second header(c-updated-block-header) 
Both to 48px please.

@<768px
Please decrease spacing above main header to 24px
Header font size increase to 32px

Couple other things:
I’m wondering if it’s weird to have a CTA on a card since essentially the whole thing is clickable - OR I know this is a straight protocol component, but maybe it makes sense to remove underline from header on hover and just keep it on link? Could we do that?

It seems we keep the left/right padding pretty wide on the notification bar - even when the width is very narrow - it can be fine for now - but I guess even halving it (at 24px) could help fit the text better

I think the back link should be all good in this particular case, unless you see a major issue.

**Comment by alexgibson** [comment]
@cgonz0 thank you! Comments below:

> I think the text you have here was in an old mock - perhaps from one of the many variations in the Sketch file?

I didn't have access to the copy doc until now thanks. I'll get this updated.

> Can we decrease the space above the main header (c-updated-block)
and increase space below second header(c-updated-block-header)
Both to 48px please.

I may well not be following correctly here, but the space below the second header is currently 96px. I'm assuming you mean decrease the space, and set both above and below the header to 48px. Let me know if that's not what you mean?

> Please decrease spacing above main header to 24px
Header font size increase to 32px

I've adjusted the space above the main header. The font size is our stock Protocol typescale, so I'm hesitant to go adjusting this on a per-page basis. If there are things you wish our design system did differently, then I encourage you to file an upstream [Protocol issue](https://github.com/mozilla/protocol/issues/new/choose), so that we can work these types of changes into the site more uniformally.

> I’m wondering if it’s weird to have a CTA on a card since essentially the whole thing is clickable - OR I know this is a straight protocol component, but maybe it makes sense to remove underline from header on hover and just keep it on link? Could we do that?

It is a little odd yeah. The current card component in Protocol assumes the whole card is a clickable link, so it makes the secondary blurb a little redundant. That said, what we have here still works, so maybe this is better than starting to create something custom for a one off page like this?

> It seems we keep the left/right padding pretty wide on the notification bar - even when the width is very narrow - it can be fine for now - but I guess even halving it (at 24px) could help fit the text better

This is the default sizing for notifications across the site. It's pretty easy to change, but again I'd encourage we do it uniformally rather than on a per-page basis.

> I think the back link should be all good in this particular case, unless you see a major issue.

Agree, I think for this particular use case it should be fine. I don't believe there's any other way to get to this page.

I've pushed the updats above to demo: https://www-demo2.allizom.org/en-US/newsletter/updated/

**Comment by cgonz0** [comment]
hey @alexgibson 
thanks for the changes - i'm good with everything for now - but will keep track of things/changes we may need for the future. i do think we got a little mixed up on the spacing - maybe i didn't specify correctly, but let me start from scratch to not complicated it further:)

c-updated-block-header
margin-top: 24px;

.c-updated-block .c-updated-block-content
margin-top: 96px;

.c-updated-block h2
margin-bottom: 48px;

hopefully that is clearer and you can increase/decrease spacing on whichever classes make more sense, but generally trying to get to how this spacing looks below:

<img width="1280" alt="Screen Shot 2020-03-17 at 8 13 23 AM" src="https://user-images.githubusercontent.com/29640968/76871461-50b15180-6828-11ea-956a-fb730861c694.png">

thanks!

**Comment by alexgibson** [comment]
Updated thanks: https://www-demo2.allizom.org/en-US/newsletter/updated/

**Comment by cgonz0** [comment]
> Updated thanks: https://www-demo2.allizom.org/en-US/newsletter/updated/

looks great! thank you
