### ISSUE TITLE
WNP 74 - Analytics

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8547]
#### Success Criteria
Instrumentation required in the page for data reporting is determined and shared w. dev
Dashboard/report is built and provided to stakeholders

**Comment by ejregithub** [comment]
@sghoseWI - I think @craigcook will have applied whatever is required for GA/GTM in his PR and there's naught to do there. This card is about getting data reporting for the performance of the page post-launch and providing that in a vehicle/medium (dashboard) to stakeholders.

**Comment by craigcook** [comment]
I'm using these params on all CTA links: 
```
utm_source=www.mozilla.org-whatsnew74
utm_medium=referral
utm_campaign=feb2020
```

The main CTA link also has a `src=external-www.mozilla.org-whatsnew74` param which I believe is something addons.m.o uses.

https://www-demo3.allizom.org/firefox/74.0/whatsnew/all/ for review and verification. Let me know if I need to change anything or do anything in addition.

**Comment by ejregithub** [comment]
@sghoseWI - if you created a dashboard/doc with performance data for  WNP74, please link that here (and close this issue).

**Comment by sghoseWI** [comment]
@ejregithub Since this is not an FxA related CTA for WNP74, I'll be monitoring progress using GA.  Please feel free to send any stakeholder my way and I can pull a static report for them.   

For dynamic reporting, we can use the CRO dashboard here: https://datastudio.google.com/reporting/1b_GlPJqn2wcBOmVzeNE0s3n13ciTE3RC/page/lEiEB/edit (this needs to be filtered to landing page CONTAINS "/firefox/74.0/whatsnew/all/"). The relevant pages in the dynamic dashboard are pages 1 and 2.

I'll also be reaching out to the AMO team to see what kind of add-ons specific data they may be receiving on their end that I might not have available to me yet.
