### ISSUE TITLE
Experiment: Add download call-out to bottom of /system-requirements

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#8647]
## Description

Add a call-out component at the bottom of [/system-requirements](https://www.mozilla.org/en-US/firefox/73.0/system-requirements/) (similar to [release-notes](https://www.mozilla.org/en-US/firefox/74.0/releasenotes/)) to test affect on download conversion.

<img width="1324" alt="Screen Shot 2020-03-10 at 11 34 00 AM" src="https://user-images.githubusercontent.com/30483988/76365039-94b1cd00-62e3-11ea-9d50-3919430353be.png">

https://trello.com/c/A6QrAkhX

---

#### Test Plan

https://docs.google.com/document/d/1wmLD2vSXd4SYuMsIMCMRgTZj4mRTAmTBOQrvb0c1fSY/edit?usp=sharing

#### Tasks
- [x] Code demo for design review.
- [x] Code experiment.

**Comment by alexgibson** [comment]
Something that may be worth considering in this experiment: a large portion of the non-Firefox traffic that lands on this page are people on older systems, who may not be able to install Firefox.

Instead of download buttons these users see the following:

![image](https://user-images.githubusercontent.com/400117/76408416-d5155780-6384-11ea-83ca-1ba4b37c60c8.png)

The requirements link goes to this page.

**Comment by amychurchwell** [comment]
@alexgibson Thanks for surfacing this! This could definitely create a really frustrating loop.
I'm thinking a potential solution is hooking into `is-modern-browser` to display this CTA?

**Comment by alexgibson** [comment]
@amychurchwell perhaps, but maybe it’s something that we don’t need to worry about too. I just wanted to call it out incase there’s not as big an opportunity here as it first might seem. Perhaps there’s enough eligible traffic to make the CTA worthwhile still 👍
