### ISSUE TITLE
Sticky Navigation: Design

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8674]
The epic at https://github.com/mozilla/bedrock/issues/8676 talks about implementing sticky navigation to replace global navigation bars on all pages that have global navigation. This card is about the design.

Tasks:
- [x] Create the spec for UX - @justinkropp and add it here.

Success Criteria:
- [x] Sticky navigation designs are attached to this issue

Approvals:
- [x] Dev
- [ ] UX Lead
- [ ] PM

**Comment by justinkropp** [comment]
Regarding the implementation of a sticky navigation, here are some design and interaction specs for guidance:

An example for the ideal behavior for this nav(on desktop) can be [viewed here](https://wicky.nillia.ms/headroom.js/), *with a tweak*:

Rather than immediately starting to slide up on scroll, I'd like to delay the initial slide of the nav until the user scrolls down the page a bit. This initial delay will give the user time to get familiar with the content within the nav. When the user does start to scroll, this should trigger the nav's drop-shadow.

![fx-homepage-1312.png](https://images.zenhubusercontent.com/5e3b061054691a8602dab50b/2367ccd1-ca64-4221-956b-53c703eae3a7)

On pages that linclude any sub-nav or in-page navigation directly under the main nav, that sub-nav should also be sticky and should remain fixed to the top of the viewport when it is scrolled into that position by the user. Similar to [this example](https://codepen.io/jstnkrpp/pen/GRJwXeK).

[@alexgibson](https://github.com/alexgibson) brought up [an issue](https://github.com/mozilla/bedrock/pull/8601#issuecomment-592450038) that occurs on small viewports. To mitigate any potential issues on smaller viewports, I think we should avoid making the nav sticky on mobile and have it behave as it does today.

![fx-homepage-480.png](https://images.zenhubusercontent.com/5e3b061054691a8602dab50b/6ad06e4c-f777-4ac0-8573-a606b2812b5c)
![fx-homepage-480 open-nav.png](https://images.zenhubusercontent.com/5e3b061054691a8602dab50b/95269a27-2f35-45a5-b9cd-b145e75f7837)
![fx-homepage-480 sub-nav.png](https://images.zenhubusercontent.com/5e3b061054691a8602dab50b/5a25626a-35cc-4b15-901b-927315778fd5)

If this doesn't make sense, please reach out with any questions. Also, whomever picks this up -- let's have a quick zoom chat to go over it.

**Comment by alexgibson** [comment]
Some edge cases for discussion with @justinkropp later today:

1. What should happen if the nav is not the top most element on the screen? For example when the fundraising banner is visible: https://www-dev.allizom.org/en-US/

2. What should happen to existing sticky bars that appear on scroll, such as on the www.mozilla.org homepage? https://www.mozilla.org/en-US/

3. How should the nav be styled alongside existing (non-sticky) sub navigation? https://www.mozilla.org/en-US/firefox/enterprise/ and also https://www.mozilla.org/en-US/internet-health/

**Comment by alexgibson** [comment]
@hoosteeno both myself and @justinkropp met today to talk through the edge cases linked above, and in the interest of getting this sticky nav out the door we propose the following:

- I'll implement the sticky feature of the primary navigation in Protocol, and then update bedrock to use it once available.
- Because we don't yet have a sub navigation component in Protocol, making the existing sub navs we have in place on www.mozilla.org interact with the primary nav is going to be tricky. To un-complicate things, we propose to temporarily remove the sticky behavior of existing sub navs on www.mozilla.org, until we can design and implement a sub nav in Protocol.

To boil that down further:
- We'll remove the existing sticky nav on the [home page](https://www.mozilla.org/en-US/) entirely, since those CTAs will be redundant once the primary nav is also sticky.
- We'll keep the sub nav on pages like [internet health](https://www.mozilla.org/en-US/internet-health/) and [enterprise](https://www.mozilla.org/en-US/firefox/enterprise/), but they won't be sticky until the still-to-be-created Protocol component exists.

Does this sound ok? Please let me know if you would like to talk this through or have questions.

**Comment by hoosteeno** [comment]
It sounds good to me. One question: On the pages with subnav, are we saying there will not be anything sticky, or only that the subnav will not stick to the top nav when the top nav transitions to sticky?

**Comment by alexgibson** [comment]
We're saying the sub-nav will not be sticky, where as the primary nav will be.

**Comment by alexgibson** [comment]
We've moved passed design here into code. Can this issue be closed out?
