### ISSUE TITLE
Epic: Sticky Navigation

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8676]
## Description

The CRO team recently tested a sticky navigation bar on /firefox which had a strong positive effect on conversion rates on the page (https://docs.google.com/document/d/1yoyFVnvFU_5sDCCzM08_DQ05n-sa8U_iMpysCLdDEcM/edit#). We should design and build a sticky navigation element that will replace our static navigation.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Sticky navigation design is approved by devs
- [x] Sticky navigation code is deployed in production for all locales

**Comment by justinkropp** [comment]
@hoosteeno Here are some design/interaction specs for guidance:

The ideal behavior for this nav on desktop can be [viewed here](https://wicky.nillia.ms/headroom.js/), with a tweak:

_Rather than immediately starting to slide up on scroll, I'd like to delay the initial slide of the nav until the user scrolls down the page a bit. This initial delay will give the user more time to get familiar with the content of the nav._

@alexgibson brought up [an issue](https://github.com/mozilla/bedrock/pull/8601#issuecomment-592450038) that occurs on small viewports. To mitigate this issue, I would suggest that the mega-nav drawer should take up the entire viewport when open and that the content inside that mega-nav should be scrollable. 

On pages that linclude any sub-nav or in-page navigation directly under the sticky main nav, that sub-nav should also be sticky and should remain fixed to the top of the viewport when it is scrolled into that position by the user (I hope that makes sense). Similar to [this example](https://codepen.io/jstnkrpp/pen/ygNOmE).

**Comment by alexgibson** [comment]
> @alexgibson brought up an issue that occurs on small viewports. To mitigate this issue, I would suggest that the mega-nav drawer should take up the entire viewport when open and that the content inside that mega-nav should be scrollable.

Note: many mobile / tablet devices (especially older models) historically have poor support for overflow scrolling content like this. It could likely render the contents of the draw that appear outside of the viewport to either be inaccessible at worst, or difficult to scroll down to at best).

An alternative (and perhaps more compatible) solution might be to only make the nav sticky on more modern browsers (using feature detection). But even then, behaviour on different mobile/tablet browsers can vary quite a lot.

**Comment by justinkropp** [comment]
> An alternative (and perhaps more compatible) solution might be to only make the nav sticky on more modern browsers (using feature detection). But even then, behaviour on different mobile/tablet browsers can vary quite a lot.

I like this approach. What do we classify as the more modern browsers?

**Comment by hoosteeno** [comment]
Maybe...

        All evergreen browsers (Firefox, Chrome, Safari, Edge, Opera, etc.)
        IE11 and above.

https://bedrock.readthedocs.io/en/latest/browser-support.html

**Comment by alexgibson** [comment]
Our browser support model is based on the idea of _progressive enahncement_, as opposed to building experiences that work in "browser X and above". The idea is to build a baseline of functionality that works everywhere, even on old browsers, and then to _enhance_ the experience for more modern browsers. For core website functionality, such as navigation, I think this is particularly important to pay attention to when we design it.

As a possible solution, rather than think about browser versions, it might be best to think about features. We're building a sticky navigation that relies on scrolling. The web standard we should look to be using here is likely [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). Using that API as a feature detect for making things sticky is probably the way to go. Older browsers would degrade gracefully.

**Comment by justinkropp** [comment]
> The idea is to build a baseline of functionality that works everywhere, even on old browsers, and then to enhance the experience for more modern browsers. 

👍
