### ISSUE TITLE
HTML is not being served compressed

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8983]
## Description

HTML should be compressed with gzip for perf reasons.

### Steps to reproduce

1) Open devtools  network tab
2) Visit www.mozilla.org
3) Click on the HTML request
4) Switch to the Headers tab
5) Look for "content-encoding" in the response.

### Expected result

Should be gzipped.

### Actual result

Not compressed

cc: @MEAOCloud

**Comment by metadave** [comment]
cc @mozilla/meaocloud

**Comment by pmac** [comment]
We believe that our CDN may not be doing this even with compression turned on due to the [BREACH and CRIME attacks](http://breachattack.com/) on compressed HTTPS responses. I do not believe that bedrock is susceptible to these attacks as there is no user generated content on the site. I think this project would do a good job for us:

https://github.com/friedelwolff/django-compression-middleware

**Comment by pmac** [comment]
Had to revert the changes to try to work out some incompatibilities with our CDN.

21b8e4331f191a94f57f13f3806253280394c6e9

**Comment by pmac** [comment]
This has been fixed again by making some changes at the CDN that enable it to convert our ETags to "weak" and do brotli or gzip compression itself.
