### ISSUE TITLE
Fluent string update requires a new ID

### ISSUE THREAD

**Issue by peiying2** [mozilla/bedrock#9056]
## Description

Describe the issue that you're seeing.
Fixing a bug should involve adding a new string ID, not making changes with existing ID. By reusing the same ID, there is no warning when the placeable or variable is different between source and target language.

### Steps to reproduce
(I missed this one during the review): firefox/switch.ftl
https://bugzilla.mozilla.org/show_bug.cgi?id=1648377
- switch-share-to-facebook = Share to Facebook
+ switch-share-to-facebook = Share to { -brand-name-facebook }

### Expected result

Add a new string and remove the old one. Or add an updated string. 

@alexgibson

**Comment by alexgibson** [comment]
Hmm, so maybe I'm a bit confused here - but i thought only changes where the context or meaning of a sentance changed required a new ID?

Here we changed the original string to use a placeable instead of a hard coded string, so it's not a breaking change to any of the existing trnalations.

Can you help me understand what issue this causes? Locales are free to use placeables or not, it's up to them as far as I understand.

**Comment by peiying2** [comment]
English: switch-share-to-facebook = Share to { -brand-name-facebook }
Current Italian translation: switch-share-to-facebook = Condividi su Facebook

The above translation didn't trigger a warning, when the target language doesn't use { brand name }. 

A big part of the migration for the community is to clean up the files after the conversion. Some don't get picked up in the conversion for a variety of reasons. In Pontoon, there is a warning for such mismatch: https://pontoon.mozilla.org/projects/mozillaorg/ (orange color). 

For some products, the mismatch breaks the build. For mozilla.org, does a localized string with missing placeable/variable get pushed to production?

**Comment by alexgibson** [comment]
> For some products, the mismatch breaks the build. For mozilla.org, does a localized string with missing placeable/variable get pushed to production? This is an existing file, so it may not show the issue well. If it is a brand new file, I wonder what the behavior of a mismatch would do to production push. Would the error check script stops such string from moving forward.

Perhaps I'm misunderstanding something about the way Pontoon works, but for mozilla.org there's really not much of an issue here. Some strings may use a placeable in en, but some locales may not in their translation. You can see this in many places throughout the migrations already.

It feels a little odd to require a new string ID here, as the meaning of the string hasn't changed imho. But if it's needed mainly to trigger a warning in Pontoon, then I can revert the original string and add a new one.

Let me know if that's what you want, or if I'm misunderstanding?

**Comment by flodolo** [comment]
The meaning of the string hasn't changed, but a translation without a term generates a warning in toolchains.

So, suddenly all locales will have warnings because of this source change. Either we fix all locales in the process of updating en-US, or we use a new ID.

In the specific case, this change seems also to have triggered a bug in Pontoon where the string doesn't show a warning at all, when it should.

**Comment by alexgibson** [comment]
> In the specific case, this change seems also to have triggered a bug in Pontoon where the string doesn't show a warning at all, when it should.

Ok, if this is causing an issue then let's help undo it for now 👍

**Comment by alexgibson** [comment]
@peiying2 @flodolo r? https://github.com/mozilla/bedrock/pull/9057
