### ISSUE TITLE
Create a design treatment for conditional messaging on /download/thanks/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9137]
## Description

In order to extend our messaging capabilities to users trying to download Firefox, we'd like to move platform specific messaging that's currently contained in our download buttons, to the [/firefox/download/thanks/](https://www.mozilla.org/en-US/firefox/download/thanks/) page. 

Doing so will help to simplify our existing download button code (see https://github.com/mozilla/bedrock/issues/8860), as well as to create a single, consistent place to provide messaging to our visitors who are downloading Firefox.

Examples of existing messages:

- "Your system may not meet the requirements for Firefox, but you can try one of these versions:" (follows with multiple download options).
- "Please follow [these instructions](https://support.mozilla.org/kb/install-firefox-linux) to install Firefox." (shown to Linux users with ARM processors).
- "[Mozilla no longer provides security updates for Firefox on Windows XP or Vista](https://support.mozilla.org/kb/end-support-windows-xp-and-vista), but you can still download the final Windows 32-bit version below."
- "Your system doesn't meet the [requirements](https://www.mozilla.org/firefox/system-requirements/) to run Firefox"
- "You’re using an insecure, outdated operating system [no longer supported by Firefox](https://support.mozilla.org/kb/end-support-windows-xp-and-vista)"
- Another example may be conditional messaging shown only to users on ChromeOS (see https://github.com/mozilla/bedrock/issues/8006).

Designing an extensible treatment that can be used to communicate the messages above is a dependency for the following issues:

- https://github.com/mozilla/bedrock/issues/8006
- https://github.com/mozilla/bedrock/issues/8860
- https://github.com/mozilla/bedrock/issues/9102

---

#### Success Criteria
- [ ] Specify a component that contains the information we need to present (which probably goes to Protocol, if it's not already there)
- [ ] Specify how that component applies to /thanks (e.g., "display component with no dismiss button, hide all success messaging") 

#### Approvals
- [ ] The Accountable
- [ ] Brand - design?
- [ ] Brand - copy?
- [ ] Team Lead
- [ ] Others?

**Comment by alexgibson** [comment]
/cc @justinkropp 

Let me know if you would like to talk through any of the above ^

**Comment by alexgibson** [comment]
Perhaps the existing notification bar component in the page might be a good lever for many of these messages? 

https://protocol.mozilla.org/patterns/molecules/notification-bar.html

**Comment by hoosteeno** [comment]
Examples of how these messages show up now, just for reference:

<img width="816" alt="Screen Shot 2020-07-15 at 10 26 30 AM" src="https://user-images.githubusercontent.com/94519/87570366-c8cc3e80-c685-11ea-9f60-c893aaed7bf9.png">
<img width="1014" alt="Screen Shot 2020-07-15 at 10 26 19 AM" src="https://user-images.githubusercontent.com/94519/87570372-cbc72f00-c685-11ea-9735-97f522392167.png">

**Comment by justinkropp** [comment]
@alexgibson After some research into possible solutions I'm leaning towards two options for displaying the conditional message. These are the options:

- an overlay that will show the content of the conditional message that is triggered on page load
- an overlay that will show the conditional message that is triggered on click (of the download button)

Would it be technically feasible to trigger the message after the user has clicked  on the button?

If the first option is pursued, a user would see the message as soon as they hit the page -- whether or not they were intending to download. They may have landed on the page after a search and are just looking to learn a bit more. I'd rather not impeded that from happening.

The second option feels like a more attractive options because we avoid the situation above and we strengthen the connection between what the message says and the action they just tried to complete (download). This option feels more explicit.

I'm going to put together a wireframe to better illustrate what this experience might look like.

**Comment by hoosteeno** [comment]
> If the first option is pursued, a user would see the message as soon as they hit the page -- whether or not they were intending to download. They may have landed on the page after a search and are just looking to learn a bit more. I'd rather not impeded that from happening.

The /thanks page is not indexed so it's not a search landing page. The only way to get there is to click a button for download, and the default behavior is to trigger a download as soon as the page is loaded (which pops open an OS modal in some browsers). Do you think popping open an info modal on pageload instead seems reasonable?

> The second option feels like a more attractive options because we avoid the situation above and we strengthen the connection between what the message says and the action they just tried to complete (download). This option feels more explicit.

I think this doesn't capture the overall desired outcome, which is to move the decision about what to do when the download button is clicked away from the button, off the page where the button is, and onto the /thanks page. Do you think we should revisit that initial plan?

**Comment by justinkropp** [comment]
> I think this doesn't capture the overall desired outcome, which is to move the decision about what to do when the download button is clicked away from the button, off the page where the button is, and onto the /thanks page. Do you think we should revisit that initial plan?

If a user is always going to hit the /thanks page after a download attempt -- no matter their platform/browser version/etc -- then I agree that the initial plan would be best: serve them a modal on page load.

**Comment by alexgibson** [comment]
If we were worried about people landing on this page without first clicking the button then, we could always pass a query parameter via the button link. But I think Justin is right here in that we can pretty safely assume people land here via the assumed action, as the page is not indexed via search. 

Even if someone did get to /thanks/ by some other means however, their intention may well still be to download, and omitting this information could result in a broken experience when trying to install the product. With this in mind, the content seems to me like perhaps the most important information on the page. It still needs to be there, imho.

**Comment by justinkropp** [comment]
@alexgibson Below is an initial pass at a possible approach. 
----
<img width="1457" alt="Screen Shot 2020-07-22 at 9 22 48 AM" src="https://user-images.githubusercontent.com/1461798/88184242-739da900-cc00-11ea-9820-567e3d531c24.png">
This approach (in this example going from /new to /thanks to SUMO) would rely on a modal-dialog to present the conditional messaging and any relevant links. We talked about the drawbacks to this approach being the use of JS, which may not degrade gracefully in older browsers. The overlay opacity also presented a similar issue, but you mentioned you could mitigate that with a workaround.
----
<img width="1446" alt="Screen Shot 2020-07-22 at 9 22 12 AM" src="https://user-images.githubusercontent.com/1461798/88184522-ce370500-cc00-11ea-96c2-50e91edcb31d.png">
This approach is similar in style, but doesn't utilize a modal-dialog or overlay. Instead, the conditional messaging is presented in-page, but in a card that has a similar "feel" to a modal. And instead of using an overlay, could we drop the opacity of the underlying content? I'm assuming that this approach would take advantage of z-index and absolute positioning to achieve the desired layout/effect (shrug). 
----
Initial thoughts?

**Comment by alexgibson** [comment]
> This approach is similar in style, but doesn't utilize a modal-dialog or overlay. Instead, the conditional messaging is presented in-page, but in a card that has a similar "feel" to a modal. And instead of using an overlay, could we drop the opacity of the underlying content? I'm assuming that this approach would take advantage of z-index and absolute positioning to achieve the desired layout/effect (shrug). 

I think this approach would be my preffered avenue to explore over the modal, for the reasons we discussed in the meeting. Some feedback on this version though:

> Instead, the conditional messaging is presented in-page, but in a card that has a similar "feel" to a modal

This almost looks / feels like the emphasis box, which is an existing component: https://protocol.mozilla.org/patterns/molecules/emphasis-box.html

> And instead of using an overlay, could we drop the opacity of the underlying content?

We could, but seeing as it's in-page content it would still need to meet accessibility guidelines.

> I'm assuming that this approach would take advantage of z-index and absolute positioning to achieve the desired layout/effect (shrug).

Seeing as this is in-page content and not a modal, we'd need to ensure that all existing content is still readable and accessible. That may mean the box flows into the regular space of the web page, as opposed to using absolute positioning where it can obscure other content (else it may as well just be a modal still, but without the overlay).

**Comment by justinkropp** [comment]
> Seeing as this is in-page content and not a modal, we'd need to ensure that all existing content is still readable and accessible. 
I'm not sure if that in-page content would have much value for this user. The new language on the /thanks page will allude to a successful download as well as next steps(installation). I'd like to avoid showing the user a message about an interrupted download attempt and at the same time showing them messaging that sounds like a successful download (below the modal/emphasis box).

**Comment by alexgibson** [comment]
> I'd like to avoid showing the user a message about an interrupted download attempt and at the same time showing them messaging that sounds like a successful download (below the modal/emphasis box).

In situations where this messaging would be seen, we have capability to hide conflicting "success" messaging - in which case this it would become the main page content for the user. With that in mind, I don't think we need to worry too much about positioning it over the page, or fading out other content (since it would not compete)?

**Comment by justinkropp** [comment]
I empathize with your position in wanting to keep some of that content accessible, but I'm gonna push back on that a bit. I think the goal of this message is explicit in that is asks the user to act or flat out prohibits them from completing an action. As such, a user shouldn't have access to content that isn't relevant here or that they cannot act on.

From [NNG](https://www.nngroup.com/articles/modal-nonmodal-dialog/):
> A modal dialog is a dialog that appears on top of the main content and moves the system into a special mode requiring user interaction. This dialog disables the main content until the user explicitly interacts with the modal dialog.
_I know that this isn't a modal-dialog in the way that we're talking about it, but the intent is the same._

For reference, the updated /thanks page is going in this direction:
![thanks-1312-windows@2x](https://user-images.githubusercontent.com/1461798/88215233-56310500-cc29-11ea-9f09-8300bc3a0bd3.jpg)

**Comment by alexgibson** [comment]
I think we need to try and re-align here in maybe, because it feels like the UI treatment that’s being suggested here is really a modal. If that’s the direction we want, then imho we should call a spade a spade, so to speak. The second treatment feels a bit too similar to a modal to me, just without the overlay.

To try and give an example as to why it’s important for the content to be accessible still: We show a warning message to XP/Vista users that Firefox is unsupported on their system. This would appear in the new box we’re designing, but we still want to allow them to auto-download.

**Comment by justinkropp** [comment]
Yes, let's sync up over Zoom and talk through this.

**Comment by ejregithub** [comment]
@justinkropp @hoosteeno @alexgibson - I booked this sync meeting for tomorrow (Thursday July 23)

**Comment by justinkropp** [comment]
There's been a shift in the design of the `/thanks` page this week. The install instructions section is being dropped due to the complex nature of maintaining its accuracy across platforms. Instead, the `/thanks` page will simply show copy along the lines of "Thanks for downloading, now install". 

This shift in design makes our treatment of these conditional messages much easier. The updated designs are attached. 

----

<img width="1312" alt="download" src="https://user-images.githubusercontent.com/1461798/89041646-bb64b480-d313-11ea-9a73-18b0a10bd2d0.png">
<img width="1312" alt="text" src="https://user-images.githubusercontent.com/1461798/89041650-bc95e180-d313-11ea-8fb8-c192c071d9f7.png">

----

1. In the case where a user **can't** continue with a download, we'll direct them to the appropriate section on SUMO.
2. In the case where a user **can**  continue with a download, we'll provide them with the appropriate download button.
3. In the case where we don't know what platform/browser they're using, instead of providing them with a range of download options on this page I'd rather just provide a link to the `[/all](https://www.mozilla.org/en-US/firefox/all/#product-desktop-release)` page.

**Comment by alexgibson** [comment]
These treatments look good to me, thanks @justinkropp 

> In the case where a user can continue with a download, we'll provide them with the appropriate download button.

One small note here is that in this scenario the download would still initiate automatically, so the user wouldn't need to click the button twice (once on /new and once on /thanks).

**Comment by alexgibson** [comment]
I think the design direction is close enough here that we can close this issue. Once this moves into code we can iterate on the finer details and messaging.

**Comment by justinkropp** [comment]
Thanks for the clarification on the screen showing the download button. Once you get to a stopping point in code, I'd like to take a final look before launch.
