### ISSUE TITLE
Update Firefox for Android image on /firefox/new/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9337]
## Description
The Android browser image is now out of date on https://www.mozilla.org/en-US/firefox/new/

![image](https://user-images.githubusercontent.com/400117/91413989-cf80d080-e843-11ea-95b5-bc6ab9bfceb5.png)

---

#### Success Criteria
- [x] Image is updated to reflect the latest Android Browser design.

**Comment by alexgibson** [comment]
Note the image in the banner may also need updating:

![image](https://user-images.githubusercontent.com/400117/91414921-25a24380-e845-11ea-8750-13fc3c06e417.png)

**Comment by justinkropp** [comment]
@alexgibson The banner could likely be replaced by the one Craig is working on: https://github.com/mozilla/bedrock/issues/9302

**Comment by hoosteeno** [comment]
@justinkropp can you update on the status of this?

**Comment by justinkropp** [comment]
I am working with product to get the most recent Android Browser Chrome to use in these updated images. ETA for completion of this work is end of week (Sep 25, 2020).

**Comment by justinkropp** [comment]
I've updated both the browser chrome and the page design of the shown website. One other change I made was to how the devices are cut off at the bottom; rather than using a hard edge to cut off the bottom of the image, I'm using a gradient to soften that transition.

----

<img width="1444" alt="Screen Shot 2020-09-24 at 1 58 23 PM" src="https://user-images.githubusercontent.com/1461798/94182046-5b4f4200-fe6e-11ea-9347-d01611ed449e.png">

----

If you don't see any issues with this, I can provide the isolated asset as an SVG or PNG.

**Comment by justinkropp** [comment]
If we're able to change out the above device image asset, I'd like to also update the browser image above so that they both have the same gradient treatment to crop the image.

----

<img width="1444" alt="Screen Shot 2020-09-24 at 2 01 59 PM" src="https://user-images.githubusercontent.com/1461798/94182317-cf89e580-fe6e-11ea-9b77-02727e68326b.png">

**Comment by hoosteeno** [comment]
@justinkropp we need the raw asset in the above comment. Can you attach?

I'm moving this back to ready state so a dev can pick it up.

**Comment by justinkropp** [comment]
Attached are the two updates images, as referenced above:
----
<img width="516" alt="Ad Blocker" src="https://user-images.githubusercontent.com/1461798/94701196-5b39c100-030a-11eb-8371-d97266d6aaea.png">
----
<img width="516" alt="Fenix Devices" src="https://user-images.githubusercontent.com/1461798/94701219-61c83880-030a-11eb-9dac-c52746532b91.png">

**Comment by hoosteeno** [comment]
This is ready for development.

**Comment by stephaniehobson** [comment]
The browser banner image has not been updated, but that was not part of the success criteria for this issue. I will create a separate issue for that.
