### ISSUE TITLE
Add sticky promo to /firefox

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#9406]
## Description

We should implement a winning experiment design on /firefox using the new sticky promo component.

"Based on mozilla.org traffic volume between 4/30/20 and 5/27/20, we estimate that implementing the winning shorter copy and logo treatment into production on /firefox will lead to **~1.25M incremental non-FX desktop downloads per year.**"

![image](https://user-images.githubusercontent.com/30483988/93247010-7de0ad00-f742-11ea-8277-018b00f40563.png)

**Comment by amychurchwell** [comment]
Blocked by https://github.com/mozilla/bedrock/issues/9357

**Comment by hoosteeno** [comment]
This is a good card. I'd like to ask @justinkropp to review possible surfaces and suggest whether the scope of this should be limited to /firefox, or whether it should include other obvious browser download pages like /new.

**Comment by amychurchwell** [comment]
Maybe the fallback content for firefox users should be the list of products?
![image](https://user-images.githubusercontent.com/30483988/93250198-4f190580-f747-11ea-8411-96443b06374a.png)

**Comment by justinkropp** [comment]
The sticky promo should, ideally, be able to be placed on any of our pages without much friction. I like the above idea of using the larger sticky card to promote our product suite on `/firefox`. I also think we could use it to promote these same products on our `/browsers` page. 

We could also run an experiment and use it to promote Mozilla VPN on our `/mobile` page.

**Comment by hoosteeno** [comment]
@justinkropp thanks. 

I think we need a deeper analysis here. The sticky card has some amazing potential use cases, but they are complex. The complexity is caused by overlapping contexts:
* our #1 pitch to non-Fx users should be the browser
* our #1 pitch to Fx users may be a different product
* our #1 pitch to anyone looking at a product page should be the product on the page

So we probably need to specify the surface, the audience, and the message for a few of our higher potential surfaces. It doesn't have to be comprehensive, but if we're going to put the card somewhere, let's cover as much ground as we can without breaking experiences. Off the cuff, I'd say...

* non-Fx users on /firefox, /new and /browsers get a browser card
* Fx users on /firefox, /new and /browsers get a multi-product card

**Comment by justinkropp** [comment]
Thanks @hoosteeno. For the multi-product card, could we replace Send with VPN? Or do you think that'd be the wrong play here?

**Comment by amychurchwell** [comment]
@justinkropp that makes sense to me. I am going to start stubbing this out today, I'll be sure to run it past you for design review before shipping.

**Comment by justinkropp** [comment]
Thanks @amychurchwell 👍

**Comment by amychurchwell** [comment]
@maxxcrawford How do you feel about picking this up? Will require a demo for design review. :)

**Comment by maxxcrawford** [comment]
Consider this assigned! I'm all about a design review. 😎
