### ISSUE TITLE
Fetch contentful data and store in bedrock db.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9458]
* Grab cards from Contentful API (sync API?) 
* Get images specified (image API)
* Run any required post-processing (optimizing?)
* Store images in S3
* Store card data in bedrock db

**Comment by pmac** [comment]
1. We'll use the Contentful Content API to fetch updated pages, layouts, and cards every 5 minutes from the bedrock clock pod, like we do with all external content.
2. When we receive an updated card we'll fetch the associated image.
	- we'll fetch the image at certain dimensions depending on the card size and aspect ratio
	- we'll potentially further process the image and store it in s3 with all of bedrock's other media
	- we'll store the path to the image in s3 in the database with the rest of the card data
3. If there is new data the database will be uploaded and all running bedrock instances will be updated with the new data

**Comment by hoosteeno** [comment]
👍 

Just noting that we have a meeting with Contentful SE's this week where we can pressure test the plan above, so changes will not be surprising.

**Comment by slightlyoffbeat** [comment]
This issue was related to building our POC. Its my understanding that we were able to achieve fetching data and storing outside of contentful, so I'm closing for now. I have, however, captured the question of best practices around this so that we can gain additional insight from the solution architect.
