### ISSUE TITLE
Test a hybrid localization scenario; document

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9459]
* Imagine a DE homepage and an EN homepage, with completely different cards and layouts
* Imagine they share the top CTA, and it is localized

**Comment by hoosteeno** [comment]
Questions from our doc:

How does Contentful's built in localization integrate with our workflows?
How do we localize content cards or other things that only appear in 1 locale?
How do we localize things that span locales (e.g. a homepage banner)?
How do we mix cross-locale and single-locale content on a page?
If we use Contentful’s built-in localization, what are our options in case a locale has no content?

**Comment by slightlyoffbeat** [comment]
My research:

Assuming english is set as the default language, you cannot have a piece of content that only has German. It must also have english.

you can set whether to ignore required fields by language. Contentful suggests you do this for any language other than the default language, otherwise you MUST have all languages any time there is a required field.
you can get around this by disabling required fields for all languages, but this would probably create more problems than fix.
you could put jibberish in the english field when doing a DE only card, but this also feels like a hack?

After a few tests, my recommendation would be to
use contentful's built in translation for anything that has already has an english 1:1 counterpart (you can select different different images and copy, and even links, but it should still be roughly 1:1).
We run our own system on a case-by-case basis. In the case of homepages and cards, I recommend we have a dropdown language field for cards (EN, FR, DE, etc). This would be used when the content manager is searching for cards to add to a page. If they know they are working on the DE page, then they can specify that the card language is equal to DE, etc.

**Comment by slightlyoffbeat** [comment]
My early recommendations using the question format from above:

**How does Contentful's built in localization integrate with our workflows?**
I can't answer that one.

**How do we localize content cards or other things that only appear in 1 locale?**
We put it all in the default language field. Cards are considered a special use case since which cards show up differ from language to language.

**How do we localize things that span locales (e.g. a homepage banner)?**
We use the built in localization system that contentful provides. This is because this piece of content shows up across all locales (even if the image/copy differs)

**How do we mix cross-locale and single-locale content on a page?**
- Cards is one content type
- Homepage assets is another content type.
- If you want to edit cards, you open something like "homepage cards - EN" and you selecet layouts, insert cards, etc.
- If you want to edit the rest of the homepage content you open up "Homepage global" and make the changes there (using contentful's localization features for non-EN languages).

**If we use Contentful’s built-in localization, what are our options in case a locale has no content?**
- for homepage cards, we simply fall back to a default layout that doesnt' use cards if it isn't EN, FR, or DE. That's what we do now. 
- for everything else, we fall back to the default language set in contentful.

**Comment by hoosteeno** [comment]
pmac agrees with the approach above.

**Comment by slightlyoffbeat** [comment]
We found an approach that works for us. We also asked the contentful team quite a few times about this approach, and they were not able to offer a better suggestion than what we decided to move forward with in our POC. 

I've captured this question in case our solutions architect has additional insight or suggestions, but i'm closing this for now.
