### ISSUE TITLE
Code singular navigation

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9466]
Let's code up the singular navigation that was designed in https://github.com/mozilla/bedrock/issues/9286. 

---
#### Success
- [x] Code is launched on demo and approved by UX
- [ ] Nav is approved by marketing leads
- [ ] Merged, pushed, in l10n

**Comment by hoosteeno** [comment]
@craigcook Here's a final copy doc: https://docs.google.com/document/d/1itYgUIVud_i7D69ci93KinVekCDOE-pm5R7vH9bN_Pc/edit?usp=sharing

**Comment by justinkropp** [comment]
@hoosteeno Which marketing leads need to approve this? Or has it already been approved by them.

**Comment by craigcook** [comment]
Demo server: https://www-demo1.allizom.org/

Current status: Working my way [through the list](https://docs.google.com/spreadsheets/d/1GBLl1q69YEpK2i-BPXefaFVE8DYVNH_n9dsASsm4Iig/) adding subnavs to pages, hoping to wrap that up and have a PR ready for review in the next day or so. This will be a big PR because it's touching so many pages, and we'll want to test the the nav thoroughly across browsers so code review may take some time.
