### ISSUE TITLE
Integrate contentful data with bedrock UI

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9469]
Once content and images are fetched from contentful, they will be stored in Bedrock's DB (or in S3 for the images). We then need to render them at request time. This card is about making sure that rendering step works (for our "prod" instance, not for the content preview instance)

**Comment by pmac** [comment]
This should be the most straight-forward piece of the project. We are already fetching external content card data and displaying it on the home page. We will simply need to fetch the data for display from the new contentful data tables instead of the old ones populated by the [www-admin repo](https://github.com/mozmeao/www-admin).

We will have to update things because of the new data model and because the layouts are now part of the model, but that should just be a bit more HTML template work if we get the data model right.

**Comment by maureenlholland** [comment]
might be missing context here, but I think this is working fine in production (as evidenced by VPN pages and en home)
