### ISSUE TITLE
Review event architecture proposal from Adswerve

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9474]
## Description

We need to review [the new event architecture](https://docs.google.com/spreadsheets/d/1_u62OJvMKmnp8zEwfWPNWvB1qHs5-yHy6j_o7DEncK0/edit#gid=1839564644) and verify it's what we want to implement on www.mozilla.org. 

---

#### Success Criteria
- [ ] We have reviewed and either approved or commented in detail about what needs to change

**Comment by rraue** [comment]
On it, I have a question about the concept for Tamara. I asked in the sheet and as soon as I got this I think I can review it fully.

**Comment by rraue** [comment]
I reviewed this and lets wait for the call tomorrow, but I think we are set. I'd liek a dev having a look if we are missing something we regularly implement. @alexgibson?

**Comment by alexgibson** [comment]
I don't have permission to comment in the doc, so here are some general notes:

**Master Settings Variable: CD32: win10User** - The closest thing we have to this currently is some outdated detection for Win 10 S mode, which is now reporting inaccurately (see https://github.com/mozilla/bedrock/issues/8139). I'm unclear if this should mean we want to capture Windows 10 users in general (doesn't GA do this automatically?), or if it should be referencing S Mode? If it's the latter, we probably want to imrove our detection so that it's more accurate.

**Scroll Tracking** - This is something we can do on an as needed basis, but it's not something we have set up on all pages. It can be done, but there can be a performance hit so we should choose wisely.

** Conversion Click: CD11: Funnel Cake** - Wouldn't this be on a download conversion? (I'm assuming it means the user is downloading a funnelcake build)

** Send to Device: CD11: Funnel Cake** - Not sure what funnelcake is doing here as they are desktop only.

**Content Card Impressions** - Does this mean an impression that fires as cards are lazy loaded? This might not be something that's as easily measurable when we switch to use native lazy loading (https://github.com/mozilla/bedrock/issues/8752). Also potentially overlaps with scroll tracking.

**Form Abandonment** - We don't have all that many forms on the website that involve multiple steps or inputs, so we should think a little carefully as to how we define abandonment in code.

**Comment by alexgibson** [comment]
My only other comment is that I don't quite know what the new custom dimensions types being added to the master setting variable stand for. Some of those sound like they need explaination and / or discussion.

**Comment by hoosteeno** [comment]
@rraue can you add the latest docs as links here?

**Comment by rraue** [comment]
Here is the implementation tec spec from Adswerve: https://docs.google.com/presentation/d/1KufGHgp6dwIkE-7F1ythcISPTzR8xJdXXfLuz9sRSJI/edit#slide=id.p
