### ISSUE TITLE
Add VPN to global nav under products.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/bedrock#9553]
## Description

We should list VPN as one of our products in the global nav.
vpn.mozilla.org

**Comment by craigcook** [comment]
It's the card on the right, under Products in the Firefox nav and under Firefox in the Mozilla nav. But I totally missed it at first because it looks like an ad and my brain has been trained to ignore things that look like ads.

Not having a good place for VPN in our architecture is what motivated updating the navbar to be a singular, actually-global navigation system (#9286) instead of this awkward split between Mozilla and Firefox. And thankfully the new nav doesn't have those pseudo-ad cards.

**Comment by amychurchwell** [comment]
@craigcook oh my gosh, I totally missed it too. I will close this issue because it sounds like this problem is being addressed. Thanks Craig.

**Comment by craigcook** [comment]
Banner Blindness strikes again! https://en.wikipedia.org/wiki/Banner_blindness
