### ISSUE TITLE
Create a link to Mozilla VPN advisories on the known vulnerabilites page

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#9659]
Now that the [first advisory for VPN](https://www.mozilla.org/en-US/security/advisories/mfsa2020-48/) has landed, we can add a "Mozilla VPN" link to the "Product Advisories" section of the [known vulnerabilities](https://www.mozilla.org/en-US/security/known-vulnerabilities/) page. This might be a tad tricky because it looks like we'll have to include all of the VPN products under one page (VPN for iOS, Windows, and Android).

**Comment by dveditz** [comment]
As of sometime last year all the clients come from common source, so it's fine to treat them the same. We can annotate individual advisories if they only affect one platform or another. [I'm here to file this bug because a bit over a year later we've had our second advisory... not high paced for sure!]

While we're updating this page, could we also move "Firefox OS" and "SeaMonkey" into the "Older" section?

**Comment by dveditz** [comment]
Also not sure how much it matters, but the mozilla-vpn page isn't in the sitemap.

**Comment by pmac** [comment]
Thanks for the bump. I'll get this on our board. The site-map issue is a good catch as well.

**Comment by pmac** [comment]
To fix the sitemap we should just need to add a line to [this variable](https://github.com/mozilla/bedrock/blob/master/bedrock/sitemaps/utils.py#L24).
