### ISSUE TITLE
Transparency Report H2 2020 [By Feb 31]

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9918]
## Description

H2 2020 report: https://docs.google.com/document/d/1nMU5luFkACU1hlQFm3wdM-iN9wg6rst8ToQckvUsIa8/edit?ts=601465f4#

Updates to transparency report landing page: https://docs.google.com/document/d/1owdF8cnUj8nbaSlsPzpW_xrqPu-ZYUPgvxxM3Kc6sfs/edit#heading=h.ebcn5arljv1

**Updates to [H1 2020 report](https://www.mozilla.org/en-US/about/policy/transparency/jan-jun-2020/):**

Please change the numbers in the personal data requests section and add a "*" after the title and a correction below with the date of publication as follows: 

Personal Data Requests*

In the Reporting Period, we received 1,653 requests.

Service | Received
-- | --
Mozilla | 601
Pocket | 1052

* This data was corrected on [date we publish].
---

**Contact:** Daniel Nazer

#### Success Criteria
- [x] Publish to demo for review prior to launch
- [ ] Updates are live Wed 17 Feb.
- [ ] Communicate live date with comms prior to pushing to production.

**Comment by hoosteeno** [comment]
From email:


 A few small edits:

1.

Capitalize "United States" in the first sentence of the "Legal Process" section for the overall transparency report page

2. 

For the correction in the H1 personal data requests:

Add a "*" before the correction and make the date next Wednesday, i.e.:

* This data was corrected on 17 February 2021.

3.

In the H2 report, the Copyright section should have 0 rather than 7 for "other services".
