### ISSUE TITLE
Small text change to Mozilla newsletter signup page at /newsletter

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/bedrock#9935]
## Description

We need a small change to the verbage on https://www.mozilla.org/newsletter/  ... to communicate a BENEFIT to the potential subscriber when they sign up for our Mozilla newsletter.  Currently the second sentence is focused on "us" when it needs to be focused on the reader/potential subscriber, and answer the question, "what's in it for me? Why should I let you into my inbox?".

OLD (to be deleted): "Subscribe to updates and keep current with Mozilla news. It’s the perfect way for us to keep in touch!"

NEW (to be added): "Subscribe here to keep current with Mozilla news, take action for a healthier internet, and get smarter about your online life."

---

#### Success Criteria
- [ ] Descriptive text on https://www.mozilla.org/newsletter/ has been changed.

**Comment by lokeshn011101** [comment]
Hey! I just tried to make the required change by changing the text in `l10n/en/mozorg/newsletters.ftl` and in `lib/fluent_migrations/newsletter/index.py` but nothing seems to change when I refresh the page(running on docker). Can anyone help me with this so that I can create a merge request? I am new to Open Source and I am trying to contribute for the first time. Thanks in advance!
